### ISSUE TITLE
BSOD after file open

### ISSUE THREAD

**Issue by ajaxovic** [dokan-dev/dokany#366] opened 2016-10-10 12:08 UTC
# Environment
 * Windows version: Win10Pro x64
 * Processor architecture: Inter Core i7-6700HQ
 * Dokany version: 1.0.0
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [ ] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the latest version (https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.

# Description
Hello All! I'm referencing closed debug on winsshfs app [here](https://github.com/Foreveryone-cz/win-sshfs/issues/78#event-817492164). It was labeled as dokan problem. I think, issue #344 is not same as mine, because browsing with file explorer works. So, here is problem:

I installed dokany version [1.0.0](https://github.com/dokan-dev/dokany/releases/tag/v1.0.0) and winsshfs version [1.6.1.13 devel RC5](https://github.com/Foreveryone-cz/win-sshfs/releases/tag/1.6.1). Then, successfully mounted my server. With total commander, navigating to some file and press F4 for edit = BSOD. Here is minidump:

[101016-9390-01.zip](https://github.com/dokan-dev/dokany/files/519427/101016-9390-01.zip)

Thanks for your work and for your help!

# Logs
Please attach in separate files: mirror output, library logs and kernel [logs](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan).
In case of BSOD, please attach minidump or dump analyze output.

**Comment by Liryna** [comment] 2016-10-10 13:33
Hi @ajaxovic ,

This seems to be the same that https://github.com/dokan-dev/dokany/issues/345 but you faced a BSOD.
When you F4, notepad open and it is at the save that it BSOD ?

**Comment by ajaxovic** [comment] 2016-10-10 14:30
No, without saving. I just press F4, empty notepad win appears and immediately BSOD. Without any action. **But I have some new update**: It works only on files that already been on server. I can create file, do multiple open/close, update content. But when I edit some other file, that I did not create through mount point, windows crash.

**Comment by Liryna** [comment] 2016-10-10 14:33
Humm can you just try to install development tools. (Uninstall, install again but click on options but and check to install additional files).
https://github.com/dokan-dev/dokany/releases/tag/v1.0.0

Try the mirror https://github.com/dokan-dev/dokany/wiki/Use%20Mirror%20example

Look if you can reproduce the issue with it

**Comment by Kerbox** [comment] 2016-10-10 16:10
Using Avira Antivirus?

**Comment by ajaxovic** [comment] 2016-10-11 07:10
**Confirmed:** Disable Avira real-time protection, all works. Enable Avira real-time protection, BSOD.

**Comment by Liryna** [comment] 2016-10-11 08:16
I just installed free Avira and dokan 1.0.0.
I was not able to make it BSOD 😢 

My avira version is 15.0.20.59

Can you try to run the mirror and reproduce the issue with it ?

**Comment by ajaxovic** [comment] 2016-10-11 09:16
Sadly, I can't reproduce error with mirror. All types of mount works. Maybe issue is connected with network connection. 

Just to clarify, I'm mounting my Linux server with SSH using IKEv2 tunnel.

**Comment by Liryna** [comment] 2016-10-11 09:17
If you add `/n` option to the mirror, it will mount it as network. can you give another try ?

**Comment by ajaxovic** [comment] 2016-10-11 09:22
I tried all options / mount types. Without problems...

**Comment by Kerbox** [comment] 2016-10-11 09:25
Are you running the latest Avira and a fully updated win 10? Just to eliminate a buggy Avira driver as the cause.

**Comment by ajaxovic** [comment] 2016-10-11 09:31
Yes, all up-to-date

![versions](https://cloud.githubusercontent.com/assets/11288002/19265653/41130b50-8fa6-11e6-9937-e8f5955dd364.png)

**Comment by Kerbox** [comment] 2016-10-13 20:43
I haven't been able to reproduce your crash. As far as I can tell from the dump, the Avira minifilter driver is passing a null pointer as first argument to RtlEqualSid, causing a bug check and BSOD. Perhaps you could open a support ticket with Avira?

**Comment by Kerbox** [comment] 2016-10-15 18:33
Would you feel comfortable opening a test account on your ssh server?

**Comment by marinkobabic** [comment] 2016-10-16 09:27
It would be helpful to have some logs. Did not analyze the dump but it seems to me that in specific case the Security Descriptor of the file is not set and so the BSOD is caused.

**Comment by ajaxovic** [comment] 2016-10-17 07:05
Hello, sorry for response delay, I was out of internet. 

Yes, I can give you test ssh account, but not in this public way. Could you send me an e-mail on webmaster@oubcom.net?

I can provide some logs, which ones?

**Comment by Kerbox** [comment] 2016-10-17 16:20
I sent you an email with my public key (23:91:b5:ae:6c:1e:8c:2e:bf:8d:73:f6:e4:53:dc:4a).

If I still can't reproduce it, you may need to provide additional logs as described [here](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan)

**Comment by ajaxovic** [comment] 2016-10-18 06:01
I sent you a mail with instructions. I hope you will be able to reproduce it...

**Comment by Kerbox** [comment] 2016-10-19 10:24
I have reproduced the issue, and will try to figure out the problem when I have some time to spare.

**Comment by Kerbox** [comment] 2016-10-19 17:03
The problem seems to be that winsshfs returns success [here](https://github.com/Foreveryone-cz/win-sshfs/blob/1.6.1/Sshfs/Sshfs/SftpFilesystem.cs#L1383), even though they don't provide the requested information (in this case, the OWNER_SECURITY_INFORMATION). Avira doesn't double check it in their driver before using it.

So should we bounce back the issue to winsshfs, or should we double check that the security descriptor is valid [here](https://github.com/dokan-dev/dokany/blob/master/sys/security.c#L163)?

**Comment by Liryna** [comment] 2016-10-19 17:24
Good job @Kerbox for tracking this !

Does the security descriptor returned by winsshfs was valid ? (empty but valid ?) 

I agree maybe we can make a check in the dokan side. Something like `IsValidSecurityDescriptor ` (don't think there is a function in the kernel side) and return STATUS_NOT_IMPLEMENTED if it is a wrong descriptor.

The best would be to check if request information are in the security descriptor but this would be more hard...

**Comment by Kerbox** [comment] 2016-10-19 17:28
The security descriptor is invalid, in that it has 0 in the owner field, even though it was owner that was requested and it returned SUCCESS.

In DokanCompleteQuerySecurity, you can do 
`RtlValidRelativeSecurityDescriptor(EventInfo->Buffer, EventInfo->BufferLength, irpSp->Parameters.QuerySecurity.SecurityInformation);`
and perhaps return STATUS_INVALID_PARAMETER. This works for me.

**Comment by Liryna** [comment] 2016-10-19 17:29
Ahhhh ! 👍 Perfect !!! Didn't know this function 😄 
You can make a PR if you would like ❤️

**Comment by Liryna** [comment] 2016-10-19 17:59
Fix from @Kerbox has been merged in master https://github.com/dokan-dev/dokany/commit/1121f48ff7ad5a956f7e7bdd670a736edbec81b9

Thank you @Kerbox again !

**Closed by Liryna** 2016-10-19 17:59 UTC
Labels: Informations required

**Comment by ajaxovic** [comment] 2016-10-20 08:07
Great job, thanks!!!
