### ISSUE TITLE
Mirror.exe wont stay running  (again)

### ISSUE THREAD

**Issue by psiberfunk** [dokan-dev/dokany#937] opened 2020-10-21 22:12 UTC
# Environment

- Windows version: Windows 10 Pro, v2004 build: 19041.572
- Processor architecture: x64
- Dokany version: 1.4.0.1000 debug build (DokanSetupDbg.exe).
- Library type (Dokany/FUSE): Dokany
- Dokany command: "C:\Program Files\Dokan\Dokan Library-1.4.0\sample\mirror\mirror.exe" /r \\ds920\video /d /s /l v >out.txt 2>err.txt
 
# Check List
  - [ X] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [ X] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [ X] I can always reproduce the issue with the provided description below.
  - [ X] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ X] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description

This issue looks almost exactly like the supposedly [fixed issue #779](https://github.com/dokan-dev/dokany/issues/779) , but i'm seeing almost the exact same behavior now as that user was seeing on the most recent version of Dokany: mirror.exe won't stay running/mounted for very long.  It seems to die at exactly the same place as 779 did with a truncated mirror.exe log with no clear reason for failure

 (see attached).

I've attached the mirror debug logs for my command .   When I tried to capture the debug data for the kernel, following the instructions carefully, I got the attached popup (screenshot) in DebugView with no output exactly at the same time as the command existed on the command line.

When I then ALSO turned on **verbose kernel logging** I got a huge stream of output in addition to the popup, which I have attached (in this case I clicked "ignore" on the popup so I could grab the output once it stabilized).  Note that the Debug View seemed to keep logging more and more errors long after the command was done and even way after the number of seconds that had caused the command to crash in terms of timestamp.  Dokany kept causing kernel log statements trying even after mirror.exe died.. which happened at ~18-20 seconds by my watch or so... I trimmed the log output at 605 seconds, well beyond any failure time.

Do you need more data to troubleshoot ?

# Logs

Attached Mirror logs from the command above.  
[err.txt](https://github.com/dokan-dev/dokany/files/5418250/err.txt)

Attached screenshot of Debug View error
![Try1](https://user-images.githubusercontent.com/19777571/96769724-7fd70500-13ad-11eb-8082-6cb71ccb237f.png)

Attached Kernal verbose debug logs
[dbgview.log](https://github.com/dokan-dev/dokany/files/5418933/dbgview.log)

**Comment by psiberfunk** [comment] 2020-10-22 01:08
P.s.  in the kernel log I think the problem starts right before this time stamp'd line, which lines up roughly with when there were issues on the wall clock:

22.66893005	[DokanFS]   Send Unmount to Service : \Volume{d6cc17c5-1738-4085-bce7-964f1e9f5de9}

**Comment by psiberfunk** [comment] 2020-10-22 02:12
Another note:  I thought the filename containing commas might be the issue, so i modified the folder and file names and then rebooted, but to my surprise another run of donkany and kernel dump produced the same (old, no longer existing) file names.. it's almost as if it was cached somehow.. but I thought donkany doesnt have a cache.

**Comment by psiberfunk** [comment] 2020-10-22 04:28
So, after uninstalling and reinstalling the program trying to access the files, which seemed to have had some sort of cache memory, the problem has gone away, but only after removing and/or renaming the "problem files".  I think what's going on here is an issue related to file names.. DOKANY seems not to like either **,** (comma) or **'** (apostrophe) characters in the files.

**Comment by Liryna** [comment] 2020-10-22 06:20
Hi,

This looks like a simple mirror crash. Would you be able to build the mirror from source and attach a debugger to see what is happening?
What is the software that produces this crash? Is there a way I can reproduce it?

**Comment by psiberfunk** [comment] 2020-10-22 18:42
Unfortunately i'm not sure I have the skills / tooling to build from source .  The software that produced the crash was backblaze looking through the files and folders.  I might be able to replicate the behavior with a similarly named file and folder and just browsing with windows explorer.  Would that help ?  

I haven't tried mirroring a local folder vs network path..  I;'ll note that the minute I changed the folder name to exclude commas and apostrophes the problem disappeared and mirror.exe no longer crashed.

**Comment by Liryna** [comment] 2020-10-22 18:43
@psiberfunk Yes! that would be helpful to have the exact step by step and also know if that possible to reproduce on local folder :) !

**Comment by psiberfunk** [comment] 2020-10-22 22:57
Update: I think this may be a file name length issue rather than commas or any special characters.  Here's why:

I can make this problem reproduce using the following setup:   

1.  Extract the attached zip folder structure and dummy test file into an SMB-mountable folder  (in this case, I used \\ds920\docker because it was convenient) 
[xxxxxxxxx (xxxx-xxxx) - xxx xxxxxxxx xxxxxxx xx xxxxxxx, xxxxxx 1,2,3,4 xxx xxxxx - xxxx xxxxxx xxxxxx xxxx.zip](https://github.com/dokan-dev/dokany/files/5426325/xxxxxxxxx.xxxx-xxxx.-.xxx.xxxxxxxx.xxxxxxx.xx.xxxxxxx.xxxxxx.1.2.3.4.xxx.xxxxx.-.xxxx.xxxxxx.xxxxxx.xxxx.zip)

2.  Use Dokany to mount:  "C:\Program Files\Dokan\Dokan Library-1.4.0\sample\mirror\mirror.exe" /r \\ds920\docker /l w

3.  Use windows explorer to open and traverse the directory structure and then attempt to open the empty text file.  You'll get an error and the Dokany process will exit as before, and the drive will immediately become unmounted (see Failure screenshot, here).
![Failure](https://user-images.githubusercontent.com/19777571/96938174-b8eba400-1497-11eb-83bb-2ccb25668b0f.png)

**Important Notes on what does not cause failures**:

-  When I placed the long-named' text file in the root of the mount point (without the two enclosing folders), the error did not happen.
- When I shortened the text file name (in the "inside the two folders" case) to **xxxx.txt** , the error did not happen.
- When I tried the same experiment with placing the extracted zip file structure at C:\ and mounting as a local folder, the error did not happen.

**Comment by Liryna** [comment] 2020-10-23 06:02
@psiberfunk Mirror code has an option at the top of the code to enable long length path. It is not a dynamic option so it needs to be rebuilt after the change.
Could you try that?

**Comment by psiberfunk** [comment] 2020-10-23 12:54
Is there a precompiled binary somewhere to grab to try and see if this is the issue ?  Dumb question:  why would it not be on by default ?

**Comment by Liryna** [comment] 2020-10-23 13:01
There is a high change that this is the issue see #464 . It is not enabled by default because long path only exist since Win10 and would use unneeded memory on other platforms limited to old MAX_PATH.
We are looking for a contribution to improve the situation #511

**Comment by SirTerrific** [comment] 2020-10-23 19:46
Hi,
I have the same issue with backblaze. I don't want to use a windows 7 or a windows 8 to fix the issue :(

**Comment by Liryna** [comment] 2020-10-23 19:48
@SirTerrific So we need someone to contribute for the previous linked ticket

**Comment by psiberfunk** [comment] 2020-10-23 20:09
Could an alternative be just bumping memory usage by default until that other ticket is  fixed ? It will slightly degrade the memory performance but it will improve stability , which I think is the more desirable, is it not ?

**Comment by Liryna** [comment] 2020-10-23 21:11
@psiberfunk If change should be made is to have dynamic path and not allocate just more memories.

Also for information, the issue is actually based in backblaze. They should be using the MaximumComponentLength  supported by the volume (in your case 255) before trying to use longer path.
https://github.com/dokan-dev/dokany/blob/master/samples/dokan_mirror/mirror.c#L1336

**Comment by psiberfunk** [comment] 2020-10-23 21:30
I would agree in principle , but the problem reproduces with windows explorer too ...

**Comment by Liryna** [comment] 2020-10-23 21:42
@psiberfunk I agree that's why it needs to be fixed with the describe solution. Would you be able to contribute to definitely solve it?

**Comment by psiberfunk** [comment] 2020-10-23 22:24
Unfortunately I’m only mildly technical .. writing code (and certainly good code ) is outside my skill set sadly :(

**Comment by SirTerrific** [comment] 2020-10-24 04:22
I have the same error on a Windows 8.1

**Comment by Liryna** [comment] 2020-10-24 07:14
Closing this as it is duplicate to the ticket above.
For anyone facing the issue and would have the time to make a pull request, please do not hesitate! I will be glad to review it.

**Closed by Liryna** 2020-10-24 07:14 UTC
