### ISSUE TITLE
Insufficient system resources exist to complete the requested service

### ISSUE THREAD

**Issue by opendedup** [dokan-dev/dokany#6] opened 2015-02-17 00:31 UTC
When copying large files I receive "Insufficient system resources exist to complete the requested service" during the copy. The filesystem I am writing uses cloud storage on the backend so is pretty slow. It seems to fail to get memory with "AllocateEventContext" not sure why but it seems to be out of memory at that point.
When the writes are fast this error does not occur.

**Comment by Maxhy** [comment] 2015-02-17 07:45
Ok thanks for the report.
 - Does this is also happening on legacy Dokan version?
 - If not and as we try to by synced with DokanX for now, could you confirm this bug also occurs on DokanX project?

Thank you.

**Comment by opendedup** [comment] 2015-02-28 17:54
It does appear in dokanx. It seems to happen when IO is slow but its difficult for me to confirm

**Comment by Liryna** [comment] 2015-02-28 22:38
I had the same issue on dokan when the IO was very slow (or during Debugging for exemple).
For me, you don't need to read/write exactly the amount of data the system is asking you.
But you need the read/write the number of data you are able to perform in a appropriate time. (Do not forget to return the size of your data)
Right after, the system will call you until the read/write is complete.

I am not a expert on this but for me it would make sense.

**Comment by marinkobabic** [comment] 2015-06-29 18:42
In your case the irp request timed out. You can increase the timeout and recompile the driver.

**Comment by Liryna** [comment] 2015-07-20 19:05
@opendedup Since there is no update from you, I will close the issue.

**Closed by Liryna** 2015-07-20 19:05 UTC

**Comment by m00fighter** [comment] 2015-09-20 17:52
I can confirm seeing this issue.

Situation -- I am using FiSSH to access folders from a Debian 8 server from a Windows 7 laptop. FiSSH in turn appears to be using Dokan (I would guess 0.6 or 0.74, I have Dokan Library 0.74 listed under installed programs, but there is a 0.6 versioned DokanNet.dll in the FiSSH directory).

Occurrence -- a data synchronization application, acting as a bridge between portable terminals and a Linux server, written in .NET 3.5, issues the System.IO.File.Copy(source,dest,overwrite) command. Network connections go through a 3G router, and are encapsulated in a PPTP VPN connection (mentioning since both might introduce latency).

Error -- Upon copying a 20 MB file, an exception is thrown with the message "Insufficient system resources exist to complete the requested service."

Surprise -- Upon closer study, the file actually *DOES* arrive at its destination. :O 

I am currently in the process of implementing a block-by-block copy algorithm intead of relying on the immensely convenient File.Copy() call.

**Comment by m00fighter** [comment] 2015-09-20 18:02
P.S. More info: the file does arrive at its destination, but some of its content does not.

It breaks approximately at 2/3 of its length, and from there on, does not contain data, only null (0x00) characters.

**Comment by joepperkins** [comment] 2015-09-20 18:09
Can you specify the exact offset when it fails and is it consistently the same offset?


-------- Original message --------

**Comment by marinkobabic** [comment] 2015-09-20 19:24
@m00fighter
If the timeout is reached during the write operating the os will result in the message above. In the newest version of dokan you will be able to run ResetTimeout so that dokan will keep waiting for the response of your write operation. The method can be executed multiple times.

**Comment by andreyloktev** [comment] 2015-09-21 17:44
@marinkobabic

**Comment by m00fighter** [comment] 2015-09-21 23:01
@joepperkins - thanks for the tip, I will switch it back for a while to find out. :)

@marinkobabic - that would be a good idea, but I can't do it. :) My application isn't aware of which filesystems are local and which virtual, and it doesn't use the Dokan API directly - it uses a filesystem mounted with FiSSH. At this point, I have found my way around the problem by switching away from the .NET System.IO functions to Shell32.dll functions.

**Comment by fds13** [comment] 2015-09-23 14:02
@marinkobabic - How can I do that? It's possible by the Dokan DotNet Wrapper? Can you help me? Thank you!

**Comment by marinkobabic** [comment] 2015-09-23 14:05
@fds13 
The new version is not available yet, so the method is not there. Liryna has the responsibility for creation of a new build.

**Comment by fds13** [comment] 2015-09-23 14:18
Ok @marinkobabic, thanks! Waiting anxiously the new version!

**Comment by Liryna** [comment] 2015-09-23 14:21
Yes, I wanted to add NTSTATUS in the release but I have some issue with it :(
I will probably make a 7.5.0 during this week.

**Comment by fds13** [comment] 2015-09-23 14:34
Great notice @Liryna 

The NTSTATUS would be the ResetTimeout that marinkobabic cited?

**Comment by Liryna** [comment] 2015-09-23 14:34
nop

**Comment by fds13** [comment] 2015-09-23 14:37
But this new release (0.7.5) will bring some fix to the trouble of copy large files?

**Comment by Liryna** [comment] 2015-09-23 14:39
This have still not be investigated with all the work we have to :cry:

**Comment by fds13** [comment] 2015-09-23 14:42
Ok, I understand.

Thanks for attention.

A hug!

**Comment by fds13** [comment] 2015-09-24 13:15
@m00fighter 
Hello buddy.

How do you did that? Can you help?

Thank you!

**Comment by m00fighter** [comment] 2015-09-24 14:09
Can you clarify please: did you want to know how I caused the problem, or how I managed to resolve it for myself?

**Comment by fds13** [comment] 2015-09-24 14:12
Sorry.

I would like to know how you solved the problem with the Shell32.dll functions.

Thank you very much!

**Comment by m00fighter** [comment] 2015-09-24 14:33
No problem. :) I coded two functions which call the Shell32 API to replace the System.IO functions. Source comes below:

----------------- source --------------

'Declare shell file operation data structure.

Private Structure SHFILEOPSTRUCT
        Public hwnd As Long
        Public wFunc As Long
        Public pFrom As String
        Public pTo As String
        Public fFlags As Integer
        Public fAborted As Boolean
        Public hNameMaps As Long
        Public sProgress As String
    End Structure

'Declare function for invoking shell file operations.

Private Declare Function SHFileOperation Lib "shell32.dll" _
        Alias "SHFileOperationA" (ByVal lpFileOp As SHFILEOPSTRUCT) As Long

'Operation function codes.

Private Const FO_MOVE = &H1
Private Const FO_COPY = &H2
Private Const FO_DELETE = &H3
Private Const FO_RENAME = &H4

'Operation behaviour flags.

Private Const FOF_SILENT = &H4
Private Const FOF_NOCONFIRMATION = &H10
Private Const FOF_NOCONFIRMMKDIR = &H200
Private Const FOF_NOERRORUI = &H400


'
' Function for calling a shell file copy operation.
' Should always overwrite, untested!
'

Public Function ShellFileCopy(ByVal src As String, ByVal dest As String) As Boolean

        Dim lRet As Long
        Dim lFlags As Long
        Dim sfo As SHFILEOPSTRUCT

	'Compose a bitmask or suitable flags.

        lFlags = lFlags Or FOF_SILENT
        lFlags = lFlags Or FOF_NOCONFIRMATION
        lFlags = lFlags Or FOF_NOCONFIRMMKDIR
        lFlags = lFlags Or FOF_NOERRORUI

	'Fill in data structure.

        With sfo
            .wFunc = FO_COPY
            .pFrom = src & vbNullChar & vbNullChar
            .pTo = dest & vbNullChar & vbNullChar
            .fFlags = lFlags
        End With

	'Call operation, check return code.

        lRet = SHFileOperation(sfo)
        ShellFileCopy = (lRet = 0)

End Function



'
' Function for calling a shell file copy operation.
' Should always overwrite, untested!
'

    Public Function ShellFileMove(ByVal src As String, ByVal dest As String) As Boolean

        Dim lRet As Long
        Dim lFlags As Long
        Dim sfo As SHFILEOPSTRUCT

	'Compose a bitmask or suitable flags.

        lFlags = lFlags Or FOF_SILENT
        lFlags = lFlags Or FOF_NOCONFIRMATION
        lFlags = lFlags Or FOF_NOCONFIRMMKDIR
        lFlags = lFlags Or FOF_NOERRORUI

	'Fill in data structure.

        With sfo
            .wFunc = FO_MOVE
            .pFrom = src & vbNullChar & vbNullChar
            .pTo = dest & vbNullChar & vbNullChar
            .fFlags = lFlags
        End With

	'Call operation, check return code.

        lRet = SHFileOperation(sfo)
        ShellFileMove = (lRet = 0)

End Function

**Comment by m00fighter** [comment] 2015-09-24 14:34
(Tip: the selection of operation behaviour flags is large and diverse, I only declared the one which interested me.)

**Comment by fds13** [comment] 2015-09-24 14:43
Thanks a lot!

I will take a look and try adapt it to c#.

See ya!

**Comment by fiddyschmitt** [comment] 2022-01-13 04:48
Coming from another angle, is there a registry setting for explorer (or Windows) which specifies the timeout before `Insufficient system resources exist to complete the requested service` is displayed?
