### ISSUE TITLE
Drive letter cannot be reclaimed after killing process with current_session option specified

### ISSUE THREAD

**Issue by kenshinsh** [dokan-dev/dokany#332] opened 2016-09-09 23:26 UTC
# Environment
- Windows version: windows 7 64-bit
- Processor architecture: x64
- Dokany version: 1.0.0 rc4
- Library type (Dokany/FUSE): Dokany
# Check List
- [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
- [x] I can always reproduce the issue with the provided description below.
- [x] I have updated Dokany to the latest version (https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
# Description

Hello,
I noticed an issue that the network share does not get released by the operating system when the user space process gets killed off via the task manager when user_current option is specified.

To reproduce the issue:
1. run command: mirror.exe /r D:\test -l p /d  /s /n /c /u \test\share
2. observed the network share is mounted
3. open task manager and kills mirror.exe
4. re-run the same mirror.exe command and observes that the same drive letter is no longer available

I have tried the same step without /u and I was able to reclaimed the same drive letter after a few seconds of wait time.

I have attached the mirror.exe output with and without current_session specified.
# Logs

[mirror_output_with_current_session.txt](https://github.com/dokan-dev/dokany/files/464987/mirror_output_with_current_session.txt)
[mirror_output_without_current_session.txt](https://github.com/dokan-dev/dokany/files/464990/mirror_output_without_current_session.txt)

**Comment by Liryna** [comment] 2016-09-10 05:57
Hi @kenshinsh ,

Thank you for your report !

I have been able to reproduce your issue.
You don't specialy need the network option to make it happen. Mounting a device with current session and killing it does not clean the mount point as it does with global mount point.

**Comment by Maxhy** [comment] 2016-09-14 19:58
Looks like this is coming from https://github.com/dokan-dev/dokany/blob/2c6ca3a6594741d0edc5c21f7116ffffee9fa579/sys/timeout.c#L326 as the timeout thread is running in system context.
Not sure about how we should handle this specific case. Maybe by storing the global dosdevice path with session information (eg. `\Sessions\0\DosDevices\M`) on device extension, but I don't think kernel mode naming supports it, neither how to get it if it does. @marinkobabic?

**Comment by marinkobabic** [comment] 2016-09-14 22:57
Option 1:
Have an additional thread running not in system context which has the responsibility to remove the symbolic link. Thread will only exist if the not MountGlobally is true.

Option 2:
Before doing drive letter check in user mode call a cleanup method on driver and this request will remove remaining letters for the current session.

**Comment by Maxhy** [comment] 2016-09-15 05:28
That's two other solutions :smile:. I thought about option 1 but I currently don't know how to do as you suggested in code. It may require some investigation.
Option 2 could do the trick if we keep references to a list of 'mount point to be removed' when the drive is mounted on current session. It's not perfect as the unavailable dos device will remains until the user try to mount the drive again ; but better than nothing.

**Comment by marinkobabic** [comment] 2017-05-30 20:53
This pull request https://github.com/dokan-dev/dokany/pull/523 uses the above mentioned option 2

**Comment by Liryna** [comment] 2017-10-01 10:26
The fix https://github.com/dokan-dev/dokany/pull/523 has been merged to the master.

**Closed by Liryna** 2017-10-01 10:26 UTC
Labels: bug
