### ISSUE TITLE
Exact Audio Copy crashes with Dokan installed

### ISSUE THREAD

**Issue by Snack-X** [dokan-dev/dokany#545] opened 2017-07-02 11:59 UTC
# Environment
 * Windows version: Windows 10
 * Processor architecture: x64
 * Dokany version: 1.0.3
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [x] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description

I'm not sure whether Dokan is problematic or EAC is, but EAC is crashing when Dokan is installed and file select modal is being opened.

To reproduce:
* Install Exact Audio Copy (without Dokan installed)
* Run EAC, and launch file select modal by selecting menu EAC - Profiles - Save Profile (any file select modal opening action will work)
* EAC does not crash
* Install Dokan
* Run EAC, and select the same menu
* EAC crashes

I can reproduce this situation within VirtualBox VM and host machine, both stable build(1.0.3) and snapshot build(1.0.3-207 by the time of writing).

If EAC is problematic, then EAC will need a fix.

# Logs

I have a minidump file produced on my host machine, but it is too big to attach on GitHub issue (over 400MB) and it may contain sensitive information about myself, so I'm not gonna attach it in here. If dump file is needed, I will send it via email.

If further step is needed, I will provide more informations.

**Comment by Liryna** [comment] 2017-07-02 12:21
Hi @Snack-X ,

It crash even without having a filesystem mount ?

**Comment by Snack-X** [comment] 2017-07-03 01:58
It crashes without any Dokan dependent software and any further setup about Dokan. Just installing Dokan (and mandatory reboot) will make EAC crash.

**Comment by PatrickMis** [comment] 2017-08-24 23:21
I can confirm everything written above. Here is the information from the event log:

Faulting application name:  EAC.exe, version: 0.0.0.0 [random], time stamp: 0x00000007
Faulting module name: dokannp1.dll, version: 1.0.3.1000, time stamp: 0x58d51fd7
Exception code: 0xc0000005
Fault offset: 0x000012e4
Faulting process id: 0x%9
Faulting application start time: 0x%10
Faulting application path: %11
Faulting module path: %12
Report Id: %13

**Comment by Liryna** [comment] 2017-08-26 14:20
@Snack-X @PatrickMis I installed EAC and could reproduce the issue with last release. I did a test with last commit and could not make it happen 👍 
![sans titre](https://user-images.githubusercontent.com/4311419/29742066-7f2eff16-8a78-11e7-8f35-c59917c11e1a.png)

**Comment by Rondom** [comment] 2017-08-26 16:23
I can still reproduce this with snapshot build [DokanSetup-1.0.3.1225.exe ](https://ci.appveyor.com/project/Maxhy/dokany/build/1.0.3-225/job/xse2v78tfc6ehqnq/artifacts).

* save profile => EAC exits
* load profile => EAC crashes

**Comment by maciozo** [comment] 2017-09-11 15:33
Happened to me as well with Dokan 1.0.3.1000

EAC would crash as soon as you press the copy button (before it even asked where to copy to).

**Comment by Liryna** [comment] 2017-10-11 12:21
Would probably need to contact Exact Audio Copy to see if there is a way to know at which point the software crash.

**Comment by Rondom** [comment] 2017-10-11 12:35
Have you tried uninstalling the network provider as follows?

dokanctl.exe /r n

**Comment by jnheinz** [comment] 2017-11-09 14:44
I ran into this problem.  Uninstalling Dokan allowed EAC to stop crashing.  The only thing I can think of, is it seems to happen when a Browse/Explore window pops up.  I do have a bunch of network drives -- all valid & connected.  Did @Liryna test it with network drives?

**Comment by Rondom** [comment] 2017-11-09 19:50
I can confirm that I had network shares mounted as well, when I reproduced it.
@jnheinz Have you tried the suggestion I my previous comment?

**Comment by Liryna** [comment] 2017-11-12 18:44
@Rondom 👍 well found ! Only network provider installed without kernel driver make it crash.
I am looking what is happening here now.

**Comment by Liryna** [comment] 2017-11-12 19:33
OK I see what is happening here.
EAC is listing the network provider and open dokannp1.dll that is on the list directly. It does not use the network provider interface, but directly a Loadlibrary. EAC is 32 bits and dokannp1.dll is 64 bits. EAC do not seem to check if Loadlibrary fail and crash. I have installed the 32 bits dokannp1.dll instead of the 64 bit to be sure it is this and I could save a profile without crash.
![image](https://user-images.githubusercontent.com/4311419/32702477-2989557c-c7e8-11e7-8fe9-a043c9786ec3.png)

I have contacted EAC by mail (eac [at] exactaudiocopy [dot] org) and hope will get an answer. There is nothing on dokan that can be done unfortunately.

Thank you guys for your report and @Rondom from pointing that I looked at the wrong direction 👍

**Comment by Liryna** [comment] 2017-11-25 09:25
There is still no answer by mail and I could not create an account he EAC forum. Does someone could point this issue on the EAC forum ❤️  ?

**Comment by Liryna** [comment] 2017-12-30 21:43
Sorry guys, I really got no answers from EAC 😢 
I will close this issue unfortunately.

**Closed by Liryna** 2017-12-30 21:43 UTC
Labels: Wontfix

**Comment by xzenor** [comment] 2018-02-08 20:21
I'm having the exact same issue. Such a shame this will apparently never be fixed...

**Comment by Liryna** [comment] 2018-03-03 12:46
Hi everyone,

dokannp1.dll x86 and x64 are now installed on x64 platform in system32 & syswow64 folder windows https://github.com/dokan-dev/dokany/commit/405c71eb1070c7c01d512b9e8eeece6b99afabbf
I made a couple of test and this fix the crash of EAC 🏆 EAC see correctly the device online and can load/save cfg without issues at all 🚀

**Comment by sigma2017** [comment] 2025-01-17 20:36
We are in 2025 and latest EAC is 1.8
Issue still persists!!!
I am using winfsp in order to mount a webdav server with rclone, there is no other way.
rclone is not working without winfsp installed (with no config whatsoever, just installed)

https://www.reddit.com/r/musichoarder/comments/12e1bmc/eac_exact_audio_copy_crashes_upon_accessing/

**Comment by Liryna** [comment] 2025-01-17 20:45
@sigma2017 The issue is resolved since 2018. I can confirm this is still the case. If you do have an issue, please open a new one with a clear description and logs.

![Image](https://github.com/user-attachments/assets/517a1e58-0ff8-4f48-819d-2fb86c558728)
![Image](https://github.com/user-attachments/assets/009a99e9-6582-49c0-bab7-8ef13f48263b)
