### ISSUE TITLE
Access denied!

### ISSUE THREAD

**Issue by onexzero** [dokan-dev/dokany#1046] opened 2022-01-15 06:19 UTC
Feature request can skip this form. Bug report **must** complete it. `Check List` must be 100% match or it will be automatically closed without further discussion. Please remove this line.

# Environment
 * Windows version: Windows 10
 * Processor architecture: AMD 5800X
 * Dokany version: 2.0.0
 * Library type (Dokany/FUSE): DokAny
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [ ] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
This issue is related with [Data corruption occured!! #1045](https://github.com/dokan-dev/dokany/issues/1045)].
Sorry i don't know how to reopen closed issue.

I did a fresh install of Windows, Dokany, office, everything for testing. So I don't think there are any interfering programs at all.
Test results are attached. As you can see in the attached video, sometimes the file takes a very long time to open.
Also, if you do SAVE consecutively or SAVE-AS, an Access denied error occurs. Please test with the test file attached to issue #1045.

# Logs
Please attach in separate files: mirror [output](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#mirrorfs), library logs and kernel [logs](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#get-logs).
In case of BSOD, please attach minidump or dump [analyze output](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#crash-report-bsod).

[aclmissing.LOG](https://github.com/dokan-dev/dokany/files/7874362/aclmissing.LOG)

https://user-images.githubusercontent.com/31300523/149611505-14b5e802-905f-4f53-905b-7b557c751541.mp4

[accessdenied.LOG](https://github.com/dokan-dev/dokany/files/7874363/accessdenied.LOG)

https://user-images.githubusercontent.com/31300523/149611524-3dc182c2-3732-4cbd-b93b-ea48bfa6fcea.mp4

**Comment by onexzero** [comment] 2022-01-15 07:17
The problem of taking time to open the file seems to be due to forgetting to disable the Office add-in. I've re-attached the test results.
[full.LOG](https://github.com/dokan-dev/dokany/files/7874452/full.LOG)

https://user-images.githubusercontent.com/31300523/149613244-6637a2c4-f083-4063-9277-4fd896f074fc.mp4

**Comment by Liryna** [comment] 2022-01-15 14:36
This is a permission issue. Please try by mirroring a folder on your desktop like `C:\Users\dokan\Desktop\MyMirror`

**Comment by onexzero** [comment] 2022-01-15 15:14
As you said, I tested again and the SAVE problem was solved. However, the SAVE-AS problem remains.
This is the result of opening 1111.pptx, saving it as 2222.pptx and 3333.pptx, and then opening 3333.pptx. 
![screenshot](https://user-images.githubusercontent.com/31300523/149626856-497d7d3d-b723-4fa6-8155-0c2b2e160b37.png)

**Comment by onexzero** [comment] 2022-01-15 15:22
If you open 1111 and SAVE-AS to 2222 and 3333, close the editor and double-click 1111 and 3333 to open the "Repair" window in powerpnt.

**Comment by onexzero** [comment] 2022-01-15 15:27
It doesn't always happen, but it does happen with a high probability when you open 1111 and 3333 repeatedly.

**Comment by onexzero** [comment] 2022-01-15 15:33
After further testing, the same phenomenon also occurs with the 2222. There seems to be a problem with reading the file. 
[openerror2.zip](https://github.com/dokan-dev/dokany/files/7875277/openerror2.zip)

**Comment by onexzero** [comment] 2022-01-15 15:46
After SAVE 1111.pptx several times in a row, when I close the editor and reopen it, the file does not open. It seems that there is a problem with the file itself as it does not open even after being copied to the desktop.

**Comment by Liryna** [comment] 2022-01-20 03:21
Such large office files are very tricky as they are super heavy to load but they do work. [Cache Manager](https://github.com/dokan-dev/dokany/discussions/1047) could speedup such situations.
Do you still have the issue without `/d` and `/n` ?
![Animation](https://user-images.githubusercontent.com/4311419/150266067-d520a099-9d20-483d-ae27-6635c5ed482a.gif)

**Comment by onexzero** [comment] 2022-01-20 05:16
Testing with the mirror samples provided is just to confirm stability. The program I am developing is slow because it expresses the file system on the web server, so it cannot be operated without the /n switch. (Programs such as Power Point perform very small byte-by-byte reads, It takes a relatively long time). Currently developing using v1.5 and there are no major problems. However, when upgrading to Dokany v2.0.x, power point or word crash occurs when SAVE or SAVE-AS is performed. It's a guess, but there seems to be a problem in the rename process.

**Comment by onexzero** [comment] 2022-01-20 05:30
The problem occurs when running mirror.exe with the /n switch, but it doesn't seem to be a problem with the /n switch. This is because when the /n switch is present, when opening a file, popwerpoint first downloads the file with INETCACHE and then opens it.
 And when saving, if the original file is orgname.pptx
Rename orgname.pptx to xxxx.tmp, create a new yyyy.tmp, record the file contents, and rename yyyy.tmp back to orgname.pptx, but a crash occurs during this process.

**Comment by onexzero** [comment] 2022-01-20 07:02
These my driver's output.
As you can see no errors with dokan v1.5.
but with v2.0 Power point crashes. Error occurs various form.
[v2-error.LOG](https://github.com/dokan-dev/dokany/files/7902968/v2-error.LOG)

https://user-images.githubusercontent.com/31300523/150289466-7c442752-4e30-4349-a652-1d7e6be207ad.mp4



https://user-images.githubusercontent.com/31300523/150289433-cd956ad0-20a9-4310-a7bd-eef70395b174.mp4

**Comment by Liryna** [comment] 2022-01-20 12:58
You should be implementing a caching on your application or look to contribute to Dokan to add support for the cache manager which would help in your situation of reading remote files.

Since the issue is not on Dolan, I am closing the issue.

**Closed** 2022-01-20 12:58 UTC

**Comment by onexzero** [comment] 2022-01-21 01:20
It seems to be possible to solve the problem by using Cache without using /n. However, I have a feeling that the root cause of the problem is not likely to be in the /n switch. Anyway, thanks for the reply.
