### ISSUE TITLE
Deadlocks/Hangs on Windows 7 32/64 bit with Mirror

### ISSUE THREAD

**Issue by RustyHacksaw** [dokan-dev/dokany#403] opened 2016-11-25 15:54 UTC
# Environment
 * Windows version: 7 
 * Processor architecture: 32/64 bit 
 * Dokany version: 1.0.1.1000
 * Library type (Dokany/FUSE): dokany/mirror
 
# Check List
  - [X] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [X] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [X] I can always reproduce the issue with the provided description below.
  - [X] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [X] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
I used the standard release first and then downloaded and installed the debug version.  Both exhibit the same behaviour, on 64 bit windows.
Mount a local folder with 'mirror /r c:\localdir /l m: /c'
There seems to be general stability issues on windows 7 ... I mounted the mirror, then navigated to it and then around to various other directories on my system and back to the mirror and explorer became unresponsive with the grey loading bar slowly moving.  The next test was to drag  in two or three files at a time, letting each copy complete before starting the next.  After 3-5 repetitions explorer will deadlock and a reboot is necessary to clean it up, the process can't be killed.  

I attached windbg to the explorer process and there were a dozen or so threads all waiting in calls to CreateFile, so it seems like there might be a deadlock in there somewhere.  I also got a blue screen on 32 bit windows:

Problem signature:
  Problem Event Name:	BlueScreen
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033

Additional information about the problem:
  BCCode:	50
  BCP1:	E9EEEEEE
  BCP2:	00000000
  BCP3:	82B0EA62
  BCP4:	00000002
  OS Version:	6_1_7601
  Service Pack:	1_0
  Product:	256_1

[minidumpWER.zip](https://github.com/dokan-dev/dokany/files/613521/minidumpWER.zip)

# Logs
Please attach in separate files: mirror output, library logs and kernel [logs](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan).
In case of BSOD, please attach minidump or dump analyze output.

# Support
 - Usage: <personal> - <testing>
 - Your personal priority to solve this issue: <med/high>
 - Support ability: <programming C, can create pull request / deeptesting / investigate driver issue />

**Comment by ed-miller** [comment] 2016-11-25 16:58
I agree. Same behavior tested. It seems to be a problem with locking. Especially when copy exe files to mirrored drive. Explorer access exe files to read for icons and hang. ApiMonitor shows up to 5 threads go inside to NtCreateFile & NtOpenFile -> dokan1.sys and never reach MirrorCreateFile.

**Comment by RustyHacksaw** [comment] 2016-11-25 17:51
Ah, yeah, now that you mention the icon thing, I did notice a weird behaviour with that too.  I had copied some files that were SVN managed with the .svn directory and when the SVN icon overlays were loaded it cause all icon loading in explorer to break and eventually explorer locked up too.

**Comment by Liryna** [comment] 2016-11-25 18:21
@RustyHacksaw Thank you for the report! 

There is a pull request that should fix this behavior but I am still waiting some answer on it.

**Comment by ed-miller** [comment] 2016-11-25 18:46
I have created a debug of the moment when dokan1.sys stops working:
![explorer freeze](https://cloud.githubusercontent.com/assets/9975199/20633517/c39a2828-b347-11e6-9e3d-efd7eb29fd41.PNG)

**Comment by Liryna** [comment] 2016-11-26 10:40
Hi @ed-miller ,

Thank you for the logs !
Can you enable this define https://github.com/dokan-dev/dokany/blob/master/sys/dokan.h#L362-L364 and comment the 3 others just before. It will give some debug output about lock/unlock FCB that should be the issue here.
Also I have merge the PR, can you test with it and see if it improve the behavior here ?

**Comment by ed-miller** [comment] 2016-11-26 12:47
Hi Liryna,
I tested new commit and it seems to solve this issue. But after copy >10000 files parallel with 5 threads, the mirror start to hang up for about 60 secondes on every forder listing. Opening the files for reading and writing was without delay.

System: Intel i7, 4Ghz, 16 GB Ram, 512 GB SSD, Win7x64, 

Log during copy of files:
[WIN7x64-dokan-debug.zip](https://github.com/dokan-dev/dokany/files/614221/WIN7x64-dokan-debug.zip)

**Comment by ed-miller** [comment] 2016-11-26 12:53
Log for 40 Seconds of folder listing:
[WIN7x64-dokan-folder-listing.zip](https://github.com/dokan-dev/dokany/files/614232/WIN7x64-dokan-folder-listing.zip)

**Comment by Liryna** [comment] 2016-11-26 13:05
@ed-miller Looks like there is some timeout. Do the behavior improve with more thread ?

**Comment by ed-miller** [comment] 2016-11-26 13:07
Hi Liryna,
I tested new commit and it seems to solve this issue. (The delay in folder listing was caused by a shell extension.)

**Comment by Liryna** [comment] 2016-11-26 13:22
I see 😃 ! Perfect !
Can this be closed so ?

**Comment by ed-miller** [comment] 2016-11-26 15:32
I will do more stress tests and will tell you.

**Comment by RustyHacksaw** [comment] 2016-11-28 16:57
I have tested the latest changes and they seem a lot more stable, I haven't experienced any deadlocks or bluescreens with the same testing I did before, seems like it's fixed!

**Comment by ed-miller** [comment] 2016-11-28 17:01
The deadlock problem seems to be solved, but unfortunately the kernel is not stable. Under multithreaded stress tests I got BSOD twice.

**Comment by Liryna** [comment] 2016-11-28 17:03
Thank you @RustyHacksaw and @ed-miller for your feedback.

@ed-miller do you have a way to reproduce the BSOD ? Do you think it is new BSOD that come with last changes ?

**Comment by ed-miller** [comment] 2016-11-28 17:07
Its hard to say whether this BSOD comes from latest changes. With the older versions I had never a BSOD before.

**Comment by marinkobabic** [comment] 2016-11-28 17:40
Please post the result of !analyze -v of the dump file. This may give us
more details.

**Comment by Liryna** [comment] 2016-12-05 08:59
@ed-miller have you been able to get a dump BSOD analyse ?

**Comment by ed-miller** [comment] 2016-12-05 12:14
As soon as i have time, i will try to get BSOD dump

**Comment by cdarau** [comment] 2016-12-19 03:51
Hello,

I wanted to posted the same issue. Since I already have the logs and a slightly different scenario, I'll post it underneath hoping it'll help you fix the problem:

# Environment
 * Windows version: Windows 7 Enterprise SP1
 * Processor architecture: x64
 * Dokany version: 1.0.1.1000
 * Library type (Dokany/FUSE): Dokany

# Description
I mount a folder from my desktop with command:
`mirror.exe /r c:\users\<username>\desktop\<foldername> /l <driveletter>:`

It has several files within it. Then I open Windows Explorer and navigate to `<driveletter>:`. While being opened, I open another instance of Windows Explorer and navigate to the same folder, but through its absolute path (`c:\users\<username>\desktop\<foldername>`). In this second instance of Windows Explorer, I delete one of the files. Then, in the first instance of Windows Explorer I refresh and the freeze happens.

It can't be reset without restart. Both the cmd from which the mirror launched and the instance of Windows Explorer that was refreshed are not responding and unwilling to stop/terminate.

# Logs
[KERNEL.TXT](https://github.com/dokan-dev/dokany/files/660032/KERNEL.TXT)
[LIBRARYLOG.TXT](https://github.com/dokan-dev/dokany/files/660033/LIBRARYLOG.TXT)
[PROCMONLOG.TXT](https://github.com/dokan-dev/dokany/files/660035/PROCMONLOG.TXT)

**Comment by Liryna** [comment] 2016-12-20 10:56
Hi @cdarau ,

The issue should be fixed with the merge of the pull request.
Can you test one of the last snapshot or build the master ?

**Comment by cdarau** [comment] 2016-12-21 03:00
Hello Liryna,

Unfortunately, I can't test this myself (it would take to much time for me). But since you probably already have the respective snapshot, wouldn't be possible to do a direct test of the scenario I've described and see if it happens? If I understand correctly from your discussion on this issue, you already have a version of dokan with the needed fix in place. So, if it's possible in a matter of minutes for you to test it, please do, because I would need a couple of hours to do it I guess, which I can't afford at this moment. Thank you in advance.

One question: do you have an estimate for when the next release will be available? I'm interested in such a release that would contain both this fix and #402.

Thank you very much!

**Comment by Liryna** [comment] 2016-12-23 20:42
Hi @cdarau ,

I don't really have much time with chritmas and such 😞 I will have normally the time for this and the release begining of january.

**Comment by freeplant** [comment] 2017-01-20 05:51
@Liryna We have encountered this problem in Seafile drive client too. Do you have any estimation on when the next release will be available?

**Comment by Liryna** [comment] 2017-01-23 08:52
Hi guys,

Sorry for the delay :sad did not have free time since beginning of the year and dokan release take sometimes with microsoft submission...here is the 1.0.2 -> https://github.com/dokan-dev/dokany/releases/tag/v1.0.2 👍

**Comment by freeplant** [comment] 2017-01-23 09:06
Thank you!

**Closed** 2017-02-04 07:20 UTC
Labels: bug, driver, Informations required
