### ISSUE TITLE
Invalid Game Executable

### ISSUE THREAD

**Issue by PacFox** [dokan-dev/dokany#866] opened 2020-01-29 07:05 UTC
# Environment
 * Windows version: Windows 10 Pro
 * Processor architecture: x64
 * Dokany version: 2.0.0-BETA2
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [x] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
I'm mounting with Mirror (using the mount manger option and running as Administrator) a network share as a local drive however when I launch a certain game it will error out and say "Executable is invalid: D:\Steam\steamapps\common\Halo The Master Chief Collection\MCC\Binaries\Win64\MCC-Win64-Shipping.exe". I can mount the network share as a mapped network drive and the same error will not occur.

# Logs
[mirror.log](https://github.com/dokan-dev/dokany/files/4126602/mirror.log)

**Comment by Liryna** [comment] 2020-01-30 12:01
Hi @PacFox ,

Have you tried using the version 1 ? Does the issue also happens ?

**Comment by PacFox** [comment] 2020-01-31 02:32
Hi @Liryna , I just tried with version 1.3.1.1000 and the same issue occurs.
[mirror.log](https://github.com/dokan-dev/dokany/files/4137282/mirror.log)

**Comment by Liryna** [comment] 2020-08-04 07:56
@PacFox I will close this issue as I might see what the issue is which is not exactly related explicitly to Halo. It will be fixed in another ticket later. Thanks again for your report.

**Closed by Liryna** 2020-08-04 07:56 UTC
