### ISSUE TITLE
Windows 10 build 16232 become unresponsive when using winsshfs/dokany

### ISSUE THREAD

**Issue by deadalnix** [dokan-dev/dokany#554] opened 2017-07-12 14:09 UTC
# Environment
 * Windows version: 10
 * Processor architecture: x64
 * Dokany version: 1.0.13
 * Library type (Dokany/FUSE): FUSE (I think).
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description

This is cross post of https://github.com/Foreveryone-cz/win-sshfs/issues/152 as I'm unsure if the problem come from winsshfs or dokany. 

The computer become unresponsive when mounting a remote filesystem using sshfs since windows 10 build 16232 . Application continue to run, and mouse still move on the screen, but it is impossible to interact with anything - click does nothing and typing on the keyboard does nothing.

I tried various version of dokany and got the same result, including the latest.

Everything works great with previous builds of windows 10. Currently download build 16237 to see if the problem persist there.

# Logs

Computer become unresponsive when the problem occurs, so not sure how to proceed here.

**Comment by deadalnix** [comment] 2017-07-12 17:06
I was able to test with windows build 16237 and it fails as well.

**Comment by marinkobabic** [comment] 2017-07-12 19:44
What are the steps to reproduce the issue? When windbg is attached using a
separate machine we should be able to discover the issue.

Does mirror work properly on those builds?

Am 12.07.2017 7:06 nachm. schrieb "deadalnix" <notifications@github.com>:

**Comment by deadalnix** [comment] 2017-07-12 20:22
Hi @marinkobabic ,

Thanks for helping.

Reading https://github.com/dokan-dev/dokany/wiki/Use-Mirror-example , it seems that mirror is supposed to be in the sample folder where dokan is installed. There is no such file there. I used the Dokan_x64.msi provided there: https://github.com/dokan-dev/dokany/releases/tag/v1.0.3

How do I get the mirror app ?

**Comment by marinkobabic** [comment] 2017-07-12 20:40
From my point of view it should be part of DokanSetupDbg.exe

Am 12.07.2017 22:22 schrieb "deadalnix" <notifications@github.com>:

**Comment by deadalnix** [comment] 2017-07-12 21:00
Ok let me try that.

**Comment by Diagonactic** [comment] 2017-07-12 21:19
This issue [also happens with Keybase](https://github.com/keybase/client/issues/7591)

It's confirmed with Windows Insider 16226, 16232 and 16237.  This means it will affect *all* Windows Insider users since 16232 was released to the Slow Channel (last week).  The latest Dokan driver as well as the one that is used in the current Keybase release are affected (just confirmed this about five minutes ago)

**Comment by Diagonactic** [comment] 2017-07-12 21:31
Somewhat interesting that 16226 was the one that brought [OneDrive files on demand](https://blogs.windows.com/windowsexperience/2017/06/13/onedrive-files-demand-now-available-windows-insiders/) implying they made some changes in Explorer and related components to support that.

**Comment by zanderz** [comment] 2017-07-13 22:16
I was able to verify that [windows insider build 16232](https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewadvanced) (thanks for the tip @Diagonactic) freezes with Dokany v1.0.3 when running mirror.exe. Will work on getting a debug trace.

**Comment by zanderz** [comment] 2017-07-13 23:21
I got the following - seems a little sparse?
Note the machine doesn't quite freeze all the way, but it's pretty much useless.
```
[\\DESKTOP-2UKD7KJ]
00000001	0.00000000	[DokanFS] ==> DokanCreate
00000002	0.00000292	[DokanFS]   Create: ProcessId 4688, FileName:(null)
00000003	0.00000401	[DokanFS]     IdType = DGL
00000004	0.00000511	[DokanFS]   IdentifierType is not vcb
00000005	0.00000729	[DokanFS]   Create: FileName:(null), status = 0x00000000
00000006	0.00000875	[DokanFS]   status = 0x0
00000007	0.00000985	[DokanFS]   status = STATUS_SUCCESS
00000008	0.00001094	[DokanFS] <== DokanCreate
00000009	0.00005835	[DokanFS] ==> DokanCreate
00000010	0.00005981	[DokanFS]   Create: ProcessId 4688, FileName:(null)
00000011	0.00006054	[DokanFS]     IdType = DGL
00000012	0.00006163	[DokanFS]   IdentifierType is not vcb
```

**Comment by Diagonactic** [comment] 2017-07-14 01:05
> Note the machine doesn't quite freeze all the way, but it's pretty much useless.

Yes, that's exactly the behavior. 👍 

I was initially impressed that the mouse kept moving (and for a while Firefox continued to function, but it eventually fell over like the rest of the apps).  But the mouse becomes, literally, the only thing that functions after a short while.  I guess the days of a true "hard lock" in Windows are behind us, but this is as close as one gets to it.

**Comment by nobitagamer** [comment] 2017-07-14 07:13
Yes, me too, i must go back to previous Windows version and uninstall (in my case is KeyBase) the software. after that update Windows to latest version will work again.

**Comment by Liryna** [comment] 2017-07-14 07:53
Thank you @zanderz for the log 👍 There is really only this ? 😮 wow
@marinkobabic can you look at this issue ? ❤️

**Comment by marinkobabic** [comment] 2017-07-14 15:36
Will take a look 😁

Am 14.07.2017 09:53 schrieb "Liryna" <notifications@github.com>:

**Comment by zanderz** [comment] 2017-07-14 19:42
That one was made with dbgview. This time I was able to attach windbg remotely and got this log with a basic mirror test:
[dokandbg.TXT](https://github.com/dokan-dev/dokany/files/1149516/dokandbg.TXT)
It quickly repeats IOCTL_MOUNTDEV_QUERY_DEVICE_NAME and STATUS_BUFFER_OVERFLOW over and over.

**Comment by marinkobabic** [comment] 2017-07-14 20:46
Makes it any difference if you use the mount manager option?

Am 14.07.2017 21:42 schrieb "Steve Sanders" <notifications@github.com>:

**Comment by zanderz** [comment] 2017-07-14 23:31
Doesn't seem to make a difference. Here is another log from doing:
mirror.exe /r C:\Users /l /o M:
[dokandbg2.TXT](https://github.com/dokan-dev/dokany/files/1149863/dokandbg2.TXT)

**Comment by marinkobabic** [comment] 2017-07-15 01:32
if the following line

https://github.com/marinkobabic/dokany/blob/master/sys/device.c#L435

is changed to
```
status = STATUS_BUFFER_TOO_SMALL;
```
then all works perfect 😃

**Comment by Liryna** [comment] 2017-07-15 06:59
@marinkobabic Thank you for looking at it 👍 

This is a really weird change from windows.
Even `cdrom` driver sample use `STATUS_BUFFER_OVERFLOW` as we do https://github.com/Microsoft/Windows-driver-samples/blob/aa6e0b36eb932099fa4eb950a6f5e289a23b6d6e/storage/class/cdrom/src/ioctl.c#L4069 and the documentation only refer to `STATUS_BUFFER_OVERFLOW` https://msdn.microsoft.com/en-us/library/windows/hardware/ff560437(v=vs.85).aspx 

Do not know what to think about it. Is that the new way to do it ? Will it work on other systems versions ? Or just a mistake that Microsoft will change next testing version.

Does microsoft as a bug report for his beta build that we could use ?

**Comment by marinkobabic** [comment] 2017-07-15 08:12
Maybe we should just report it to Microsoft.

Because of this line here

https://github.com/marinkobabic/dokany/blob/master/sys/device.c#L411

 I think it may work also on other systems. No idea why we do it in two
different ways.

Am 15.07.2017 08:59 schrieb "Liryna" <notifications@github.com>:

**Comment by Liryna** [comment] 2017-07-15 10:43
Even reactos do the same 🤔 https://github.com/reactos/reactos/blob/31b47ad45e6384dd538ebfee33c4829945cf2eee/reactos/drivers/filesystems/btrfs/devctrl.c#L86

My understanding is  that `STATUS_BUFFER_TOO_SMALL` should be when the minimum memory of the IOCTL is not available and `STATUS_BUFFER_OVERFLOW` when extra memory is needed.

I do not use windows insider program does anyway know where to report this ?

**Comment by marinkobabic** [comment] 2017-07-15 13:18
Have reported it using Feedback Hub but I don't have any reference to the reported issue.

**Comment by phillijw** [comment] 2017-07-17 15:38
I've also reported this. Nobody has responded yet.

**Comment by benpye** [comment] 2017-07-17 17:12
Have you got a link to the feedback item?

**Comment by marinkobabic** [comment] 2017-07-17 17:39
No. I used the feedback hub. They do not provide any link so far I have
seen. You?

Am 17.07.2017 19:12 schrieb "Ben Pye" <notifications@github.com>:

**Comment by benpye** [comment] 2017-07-17 17:52
There should be a share link on the feedback item in the hub?

**Comment by benpye** [comment] 2017-07-17 18:19
See https://compass-ssl.microsoft.com/assets/ab/e5/abe590f3-accd-407d-8be5-3b8347957565.png?n=FeedbackHubURL1.png

**Comment by marinkobabic** [comment] 2017-07-17 18:28
Can you share your link here please?

Am 17.07.2017 20:19 schrieb "Ben Pye" <notifications@github.com>:

**Comment by Diagonactic** [comment] 2017-07-20 00:39
I located the link from Feedback hub that I commented on related to this issue -- it's the original from the Keybase Github issue.

On Windows 10, this link opens up in Feedback Hub, so I'm not entirely sure if it works without Windows 10 or not, but it's available [here](https://aka.ms/G7ds4a).

I've updated it to link to this GitHub issue, as well, though I've not seen any additional activity beyond my own and the original submitter on that particular feedback item.

**Comment by benpye** [comment] 2017-07-21 06:15
I've looked into this, I think Dokany may have a bug. Could someone try changing https://github.com/dokan-dev/dokany/blob/master/sys/device.c#L485 to a `<=` ?

**Comment by Liryna** [comment] 2017-07-21 08:34
@benpye `IOCTL_MOUNTDEV_QUERY_SUGGESTED_LINK_NAME` is not present in the logs provided by @zanderz 
`IOCTL_MOUNTDEV_QUERY_SUGGESTED_LINK_NAME` is only used with mount manager options enabled, here it is not the case.

**Comment by benpye** [comment] 2017-07-21 14:33
Ah, I am fairly sure that is still incorrect however.

**Comment by Liryna** [comment] 2017-07-21 14:41
👍 Yes, that’s right. Sorry had to write kick this morning. Thanks for the report I made a quick patch. https://github.com/dokan-dev/dokany/commit/9c9b55713d6701eabae9cd5405d1ea35ad6899d7

**Comment by zanderz** [comment] 2017-07-21 17:05
@lyrna @benpye This is a separate bug, right? There is still something strange on the Microsoft side? Or is this expected to be a solution?

**Comment by Liryna** [comment] 2017-07-21 17:08
@zanderz that's a separate bug, the code fixed is not used in our case here.

There is still something strange on the Microsoft side that we hope their support will give us an answer. 
Do we have a tracking number / link on someone open ticket ?

**Comment by marinkobabic** [comment] 2017-07-21 17:08
Yes. This bugs are not related.

Am 21.07.2017 19:05 schrieb "Steve Sanders" <notifications@github.com>:

**Comment by benpye** [comment] 2017-07-21 17:34
Looks like the same error is present in several places, looks like I linked to a different instance last night.

I believe the first one is causing this hang:
https://github.com/dokan-dev/dokany/blob/master/sys/device.c#L427
https://github.com/dokan-dev/dokany/blob/master/sys/device.c#L453

**Comment by phillijw** [comment] 2017-07-22 05:28
Not directly related, but the same windows preview version seems to be causing issues with Plex media server library updates which obviously scan/access disk. I would imagine it's caused by the same issue.

**Comment by deadalnix** [comment] 2017-07-22 11:58
Yes this windows update was a disaster. It broke dokani, vmware, and power management on my machine. So far, they fixed power management, vmware published a special version for it, but dokani is still not working :/

**Comment by benpye** [comment] 2017-07-23 04:17
Can anyone confirm if my second suggested fix rectified this issue?

**Comment by Rondom** [comment] 2017-07-23 12:08
Can you maybe create a pull request? AppVeyor produces a (test-signed) build automatically, which would enable a wider crowd to test your fix. If you do not have a PC with GIT installed at hand, you can even do your edits via the GitHub web interface.

(If you are not confident about your fix you can also fork this repository and register your fork with [ci.appveyor.com](https://ci.appveyor.com))

[In order to enable testsigned drivers, follow the instructions in the wiki.](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot)

**Comment by benpye** [comment] 2017-07-23 21:39
Thanks @Rondom , I was unaware PRs generated builds.

**Comment by ivorytir** [comment] 2017-07-25 01:46
Changed only this line https://github.com/dokan-dev/dokany/blob/master/sys/device.c#L427 in older dokany 0.8 and it resolved the hang in Win 10 build 16241 for me.

**Comment by Liryna** [comment] 2017-07-26 07:32
@benpye PR with a fix has been merged. https://github.com/dokan-dev/dokany/pull/559
I could not test personally (my VM do not want to get the insider update for a reason 😢 ) but by the code and the return of people, this seems to do the job.

I will try to make a release in the next days when gets some time.
@zanderz if you have the possibility to have a feedback from the community before this it would be perfect 👍 !

**Comment by Rondom** [comment] 2017-07-26 17:29
For those who want to test:
Latest build is available here: https://ci.appveyor.com/project/Maxhy/dokany/branch/master/job/jl8gpomo3im13ihp/artifacts

[You need to enable testsigned drivers, follow the instructions in the wiki.](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot)

**Comment by kauhat** [comment] 2017-07-26 20:00
Hey folks,

Build 1.0.3.1216 is working great for me on Insider build 170624-1334. Cheers!

**Comment by zanderz** [comment] 2017-07-26 22:05
I just built Dokan from current master and the freeze problem is solved on Win 10 build 16232. Thanks everyone! :thumbsup:

**Comment by phillijw** [comment] 2017-07-27 05:23
Win 10 build 16232. Keybase is no longer crashing BUT I am not seeing the drive it usually creates

**Comment by kauhat** [comment] 2017-07-27 07:30
@phillijw I believe I was having a similar issue when testing last night - I needed to disable Secure Boot in my BIOS before running the `cert/dokan-import.ps1` script.

**Comment by phillijw** [comment] 2017-07-27 14:08
@kauhat That reminded me that I didn't actually set up the certs and that's probably why it wasn't working. When I tried setting them up I wasn't having any luck whatsoever so I gave up

**Comment by zanderz** [comment] 2017-07-27 21:13
Here is our build in case someone wants to try an EV-signed one:
https://github.com/keybase/dokany/releases/download/v1.0.4.84/dokany.zip

**Comment by deadalnix** [comment] 2017-08-25 11:52
Looks like this fix has been ready for about a month. Will there be a relase of dokay that includes it in the near future ?

PS: Thanks to everybody involved here, great work.

**Comment by benpye** [comment] 2017-08-28 20:24
@deadalnix Looks like the keybase build should work? EV signed so you won't need test mode.

**Comment by Liryna** [comment] 2017-08-28 20:35
Will try to make a 1.0.4 this week 👍

**Comment by deadalnix** [comment] 2017-08-28 20:41
@benpye yes it does, but it feels a bit hacky to have to do that. It seems like a release would be needed anyway so win10 users can use it without getting their computer to crash and dig and end up here :)

@Liryna awesome. Thanks.

**Comment by benpye** [comment] 2017-08-28 21:51
@deadalnix The Dokany bug shouldn't cause a hang on 16273+.

**Comment by ivorytir** [comment] 2017-08-28 22:04
@benpye so Microsoft changed something and the current Dokany release doesn't hang anymore?

**Comment by fpqc** [comment] 2017-08-31 08:48
@Liryna You can always get a VM preloaded with a recent insider build of Win10 here:

https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by Liryna** [comment] 2017-08-31 08:49
@fpqc oh ! I have to keep this link 👍 thank you !

**Comment by Liryna** [comment] 2017-08-31 12:08
1.0.4 has been release https://github.com/dokan-dev/dokany/releases/tag/v1.0.4 👍 
If anyone can do the test it would be appreciate !

**Comment by runapp** [comment] 2017-09-15 11:17
@Liryna I'm not pretty sure about how the bug was performing before, but when I use 1.0.4 with winsshfs 1.6.1.13 devel RC5 on Win10 16278 it seems that the **Explorer and part of Winlogon** freeze. I say it because all things related to Explorer (file manager and desktop) stops working, as well as C-A-Del. However other programs keep running smoothly **until they got to do an IO operation about file listing** (Can be reproduced by Powershell).
From my point of view this is much like using sshfs on linux when recovered from a hibernation. The ssh link breaks and sshfs will stuck on getting data. I'll try debugging it using VM cause rebooting host machine is very painful...

**Comment by Liryna** [comment] 2017-09-15 11:26
@runapp This seems to be another issue from what you explain. Here the device would not even mount.
Does what you explain is the same as https://github.com/dokan-dev/dokany/issues/413 ?
Otherwise, can you open another issue ?

**Comment by runapp** [comment] 2017-09-15 11:47
@Liryna Nope, seems not the same as #413 .
I'll try to do it clean in VM and make sure it can be reproduced by everyone.
I think it's mostly the same as the OP's, except that my mouse and keyboard are still working.
PS: actually it begines from Win 16251. On the previous normal release, aka Win 10 1607, I was using old winsshfs stable with dokan 0.7.4, flawlessly. However this combination will still cause freeze on 16251.

**Comment by Liryna** [comment] 2017-10-01 10:05
From different feedback, this seems to be fixed now.
I will reopen if someone still do not get a proper behavior on preview build.

**Closed by Liryna** 2017-10-01 10:05 UTC
