### ISSUE TITLE
Windows Explorer hangs and Windows needs restart

### ISSUE THREAD

**Issue by g-fusion** [dokan-dev/dokany#623] opened 2017-11-20 15:35 UTC
Feature request can skip this form. Bug report **must** complete it. `Check List` must be 100% match or it will be automatically closed without further discussion. Please remove this line.

# Environment
 * Windows version: Win 10
 * Processor architecture: x64
 * Dokany version: 1.0.0 (final)
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
We have scenario when 1200-1400 big jpg files (~45-50MB each)  has to be displayed in Explorer and thumbnails is ON (in some system it is not by default on https://answers.microsoft.com/en-us/windows/forum/windows_7-pictures/cannot-preview-images-in-windows-explorer-or-my/75ebc2c3-1ff4-44da-b684-7dbdb5ac9576) . When loading is started, View in Explorer is switched to Extra Large icons and do a little bit of scrolling,  at some point entire Explorer hangs. At the end you end up to a point Windows restart. Issue reproduced with Mirror and logs attached. Any help is much appreciated. Just to mention that I could see "DokanFS" written in the logs despite Explorer hang before i restart the Windows.

# Logs
Please attach in separate files: mirror output, library logs and kernel [logs](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan).
In case of BSOD, please attach minidump or dump analyze output. [Images.zip](https://github.com/dokan-dev/dokany/files/1488153/Images.zip)

**Comment by Liryna** [comment] 2017-11-20 15:36
Hi @g-fusion ,

Which version of Dokan exactly are you using ?

**Comment by g-fusion** [comment] 2017-11-20 15:37
Hi Liryna,

Version is 1.0.0.5000

**Comment by Liryna** [comment] 2017-11-20 15:39
1.0.5 ?
Can you try with 1.0.3 see if this also happen ?

**Comment by g-fusion** [comment] 2017-11-20 15:40
Hi,

Will test and provide update. Do you need Debug logs as well if it happen to hang?

**Comment by Liryna** [comment] 2017-11-20 15:41
@g-fusion if you can get it, it would be nice !
Otherwise I will try to reproduce with a proper guide 👍

**Comment by g-fusion** [comment] 2017-11-20 15:50
Hi,

Just tested it. It seems to work. Do you need logs to compare?! I will some additional testing meanwhile.

**Comment by fanlonglong8500** [comment] 2017-11-21 03:34
I encountered the same problem，I found it deadlock in DokanDispatchCleanup -> FlushFcb -> CcFlushCache  .

**Comment by g-fusion** [comment] 2017-11-23 10:39
Hello,

I was wondering if any down-port can be done, to the driver that we are using? The reason is that once i put new driver 1.03 rev. some of the functionalities that we are using are affected. For example creating new Excel file is no longer possible also its upload or move as well. I mean adopt ing new driver is not that easily done out of the box.

**Comment by Liryna** [comment] 2017-11-25 14:04
@fanlonglong8500 fcb->SectionObjectPointers is init in SetFileObjectForVCB

@g-fusion I did tried to reproduce the issue with a picture (copy x1000 of 10mb), I could not reproduce this.
Since you say it works with 1.0.3 and after a review of the changes, there is a good chance that it was the lock I introduce in write that is probably used during the creation of the thumbnails  cache.
I reverted it already for another issue: https://github.com/dokan-dev/dokany/commit/b72f645e55b3a480a43a3fdac4b0d0a03fb54480

There is another lock added for set security but I do not expect it to create an issue here.

Are you able to test the fix with the snapshot:
https://ci.appveyor.com/project/Maxhy/dokany/branch/master/job/d3y3qs3c5mh03e9i/artifacts
https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot

**Comment by g-fusion** [comment] 2017-11-27 12:34
Hi,

Will take only those changes https://github.com/dokan-dev/dokany/commit/b72f645e55b3a480a43a3fdac4b0d0a03fb54480 and try to build driver and will report back. Small remark when reproduce, the images must be BIG > 40 MB each. With small ones i did not managed to reproduce it either.

**Comment by g-fusion** [comment] 2017-11-27 15:02
Hi,

The change https://github.com/dokan-dev/dokany/commit/b72f645e55b3a480a43a3fdac4b0d0a03fb54480 is not contained in 1.0.0.500 and 1.0.3 driver, how it can explain the behaviour i.e. on 1.0.0 it hangs and on 1.0.3 i does not. The DokanCompleteWrite() method does not have any difference there compared to master?! Also, having latest driver is not an option for us based on my previous memo, it is somehow incompatible working with office files (excel). I though having only your change, as downport, to 1.0.0 driver would be possible, but not sure if this is the real cause of the issue.

**Comment by Liryna** [comment] 2017-11-27 16:15
Hi @g-fusion ,

Oh, I tought you were using 1.0.5 and not 1.0.0
https://github.com/dokan-dev/dokany/issues/623#issuecomment-345733194

Forget about what I said before. Now I remember this issue has already been reported and fixed for 1.0.1
https://github.com/dokan-dev/dokany/blob/master/CHANGELOG.md#1011000---2016-11-04
Lots of changes for lock have been made, you may want to look at them if you wanna backport https://github.com/dokan-dev/dokany/compare/v1.0.0...v1.0.1
And specially about `CcPurgeCacheSection`

**Comment by g-fusion** [comment] 2017-11-28 15:57
Hi,

Did small test with drivers as follows:
1.   1.0.0 - Hang (reboot required)(
2.   1.0.1 - Runs smoothly 
3.   1.0.3 - Runs OK
4.   1.0.5(without change https://github.com/dokan-dev/dokany/commit/b72f645e55b3a480a43a3fdac4b0d0a03fb54480)- Runs OK, not that smooth as 1.0.1 while loading all the images
5.   1.0.5 (with change https://github.com/dokan-dev/dokany/commit/b72f645e55b3a480a43a3fdac4b0d0a03fb54480) - Runs OK, again not that smooth like 1.0.1

Maybe i have to check our impl. as well, because we are fetching images from network and working as Local Disk and reading is not sequential. Maybe if i am network driver it will be(if i remember my test in the past correctly). I saw something similar in context of FTP (https://github.com/dokan-dev/dokany/issues/210), but this is related i think to (https://github.com/dokan-dev/dokany/pull/307).  Any suggestions here? Should Network Drive will be better or not?

**Comment by Liryna** [comment] 2017-12-01 12:31
About smooth, https://github.com/dokan-dev/dokany/compare/v1.0.1...v1.0.3 has reviews of the FCB locks in the kernel.
Maybe there some locks that are heavier than on 1.0.1 BUT they were added to handle possible crash/BSOD.

You can see the lock usage by macro DokanFCBLockRW/DokanFCBLockRO

**Comment by Liryna** [comment] 2017-12-28 16:46
@g-fusion I close this. If you have any other question. Do not hesitate.

**Closed by Liryna** 2017-12-28 16:46 UTC
Labels: Question
