### ISSUE TITLE
Win7 - FindFirstFile with a file => full parsing of the parent directory until the mounted root

### ISSUE THREAD

**Issue by EpsilonXX** [dokan-dev/dokany#308] opened 2016-08-03 09:26 UTC
# Environment
- Windows version: Win7
- Processor architecture: x64
- Dokany version: RC3
- Library type (Dokany/FUSE): Dokany
# Check List
- [*] I checked my issue
- [*] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
- [*] I can always reproduce the issue with the provided description below.
- [*] I have updated Dokany to the latest version (https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
# Description

Hi ,

I've a question regarding the behavior of FindFirstFile with a file.
In RC3 ,(I didn't test with previous version) ,when you call a FindFirstFile with a file as an argument,
Dokan parses the directory of the file to find the match  (normal) but continues with the parent of the directory etc to reach the mounted root. (it doesn't happen with the Dokan 0.6)
Is it an expected behavior of Windows (for caching or something else)  or a bug introduced recently ?

For Instance ,I created these folders h:\TestFindFile\A\B\C\D\E\F\G\H with files a.txt,b.txt,c.txt,d.txt in the H folder and called
    WIN32_FIND_DATA fdata;
    HANDLE handle = FindFirstFile(L"Q:\A\B\C\D\E\F\G\H\b.txt", &fdata);
    FindClose(handle);

from the logs (see mirrorfindFileRC3.txt):
FindFiles :h:\TestFindFile\A\B\C\D\E\F\G
    FindFiles :h:\TestFindFile\A\B\C\D\E\F
       FindFiles :h:\TestFindFile\A\B\C\D\E
etc

It's a major performance issue when you have many files and folders inside.
Any ideas,

Thx
# Logs

[mirrorfindFileRC3.txt](https://github.com/dokan-dev/dokany/files/399066/mirrorfindFileRC3.txt)

**Comment by Liryna** [comment] 2016-08-06 09:22
Hi @EpsilonXX ,

I tested with your code sample and was not been able to reproduce the behaviour:
```
  WIN32_FIND_DATA fdata;
  HANDLE handle = FindFirstFile(L"M:\\A\\B\\C\\D\\E\\F\\G\\H\\b.txt", &fdata);
  FindClose(handle);
```

Mirror result:
```
C:\Users\liryna\Desktop\Debug>mirror.exe /r C:\Users /l m /d /s
## Attempting to add SE_SECURITY_NAME privilege to process token ##
  success: privilege already present
Dokan: debug mode on
Dokan: use stderr
AllocationUnitSize: 512 SectorSize: 512
device opened
###QueryVolumeInfo -001
mounted: m -> \Volume{d6cc17c5-1731-4085-bce7-964f1e9f5de9}
Mounted
###Create 0000
CreateFile : C:\Users\A\B\C\D\E\F\G\H
  AccountName: liryna, DomainName: DESKTOP-T9B1IFA
        ShareMode = 0x7
        FILE_SHARE_READ
        FILE_SHARE_WRITE
        FILE_SHARE_DELETE
        AccessMode = 0x100001
        FILE_READ_DATA
        SYNCHRONIZE
        FlagsAndAttributes = 0x0
        OPEN_EXISTING

CreateFile status = 0 - lastError = 0
###GetFileInfo 0000
GetFileInfo : C:\Users\A\B\C\D\E\F\G\H
        GetFileInformationByHandle success, file size = 0

        result =  0
  unknown type:54
        DispatchQueryInformation result =  c000000d
###GetFileInfo 0000
GetFileInfo : C:\Users\A\B\C\D\E\F\G\H
        GetFileInformationByHandle success, file size = 0

        result =  0
        FileStandardInformation
        DispatchQueryInformation result =  0
###FindFiles 0000
FindFiles :C:\Users\A\B\C\D\E\F\G\H
        FindFiles return 3 entries in C:\Users\A\B\C\D\E\F\G\H\*

index from 0
FileMatch? : . (b.txt,0,0)
FileMatch? : .. (b.txt,0,0)
FileMatch? : b.txt (b.txt,0,0)
  =>return single entry
index to 1
###Cleanup 0000
Cleanup: C:\Users\A\B\C\D\E\F\G\H

###Close 0000
Close: C:\Users\A\B\C\D\E\F\G\H
```

**Comment by EpsilonXX** [comment] 2016-08-08 08:03
Hi Liryna,

Well, I didn't repro with Win10 .
I checked again on Win7  with the latest master and from an other drive => same issue.

I noticed that between your logs and mine  : 
there is a createFile with the next folder after the getFileInfo that i don't explain and seems the start of the recursive check (###Create 0001 CreateFile : C:\TestFindFile\A\B\C\D\E\F\G ) /FlagsAndAttributes = 0x2000090 

the ###FindFiles 0000 appears only at the end when we back to the root.

--------------------------
mounted: Q -> \Volume{d6cc17c5-1733-4085-bce7-964f1e9f5de9}
Mounted
###Create 0000
CreateFile : C:\TestFindFile\A\B\C\D\E\F\G\H
	ShareMode = 0x7
	FILE_SHARE_READ
	FILE_SHARE_WRITE
	FILE_SHARE_DELETE
	AccessMode = 0x100001
	FILE_READ_DATA
	SYNCHRONIZE
	FlagsAndAttributes = 0x0
	OPEN_EXISTING

CreateFile status = 0 - lastError = 0
###GetFileInfo 0000
GetFileInfo : C:\TestFindFile\A\B\C\D\E\F\G\H
	GetFileInformationByHandle success, file size = 0

	result =  0
  unknown type:54
	DispatchQueryInformation result =  c000000d
###GetFileInfo 0000
GetFileInfo : C:\TestFindFile\A\B\C\D\E\F\G\H
	GetFileInformationByHandle success, file size = 0

	result =  0
	FileStandardInformation
	DispatchQueryInformation result =  0
###Create 0001
CreateFile : C:\TestFindFile\A\B\C\D\E\F\G
	ShareMode = 0x7
	FILE_SHARE_READ
	FILE_SHARE_WRITE
	FILE_SHARE_DELETE
	AccessMode = 0x100001
	FILE_READ_DATA
	SYNCHRONIZE
	FlagsAndAttributes = 0x2000090
	FILE_ATTRIBUTE_NORMAL
	FILE_FLAG_BACKUP_SEMANTICS
	OPEN_EXISTING

CreateFile status = 0 - lastError = 0
###FindFiles 0001
FindFiles :C:\TestFindFile\A\B\C\D\E\F\G
	FindFiles return 3 entries in C:\TestFindFile\A\B\C\D\E\F\G\*

index from 0
FileMatch? : . (H,0,0)
FileMatch? : .. (H,0,0)
FileMatch? : H (H,0,0)
  =>return single entry
index to 1
###Cleanup 0001
Cleanup: C:\TestFindFile\A\B\C\D\E\F\G

###Close 0001
Close: C:\TestFindFile\A\B\C\D\E\F\G

###Create 0002
CreateFile : C:\TestFindFile\A\B\C\D\E\F
	ShareMode = 0x7
	FILE_SHARE_READ
	FILE_SHARE_WRITE
	FILE_SHARE_DELETE
	AccessMode = 0x100001
	FILE_READ_DATA
	SYNCHRONIZE
	FlagsAndAttributes = 0x2000090
	FILE_ATTRIBUTE_NORMAL
	FILE_FLAG_BACKUP_SEMANTICS
	OPEN_EXISTING

CreateFile status = 0 - lastError = 0
###FindFiles 0002
FindFiles :C:\TestFindFile\A\B\C\D\E\F
	FindFiles return 3 entries in C:\TestFindFile\A\B\C\D\E\F\*

index from 0
FileMatch? : . (G,0,0)
FileMatch? : .. (G,0,0)
FileMatch? : G (G,0,0)
  =>return single entry
index to 1
###Cleanup 0002
Cleanup: C:\TestFindFile\A\B\C\D\E\F

###Close 0002
###Create 0003
Close: C:\TestFindFile\A\B\C\D\E\F

CreateFile : C:\TestFindFile\A\B\C\D\E
	ShareMode = 0x7
	FILE_SHARE_READ
	FILE_SHARE_WRITE
	FILE_SHARE_DELETE
	AccessMode = 0x100001
	FILE_READ_DATA
	SYNCHRONIZE
	FlagsAndAttributes = 0x2000090
	FILE_ATTRIBUTE_NORMAL
	FILE_FLAG_BACKUP_SEMANTICS
	OPEN_EXISTING

CreateFile status = 0 - lastError = 0
###FindFiles 0003
FindFiles :C:\TestFindFile\A\B\C\D\E
	FindFiles return 3 entries in C:\TestFindFile\A\B\C\D\E\*

index from 0
FileMatch? : . (F,0,0)
FileMatch? : .. (F,0,0)
FileMatch? : F (F,0,0)
  =>return single entry
index to 1
###Cleanup 0003
Cleanup: C:\TestFindFile\A\B\C\D\E

###Close 0003
Close: C:\TestFindFile\A\B\C\D\E

###Create 0004
CreateFile : C:\TestFindFile\A\B\C\D
	ShareMode = 0x7
	FILE_SHARE_READ
	FILE_SHARE_WRITE
	FILE_SHARE_DELETE
	AccessMode = 0x100001
	FILE_READ_DATA
	SYNCHRONIZE
	FlagsAndAttributes = 0x2000090
	FILE_ATTRIBUTE_NORMAL
	FILE_FLAG_BACKUP_SEMANTICS
	OPEN_EXISTING

CreateFile status = 0 - lastError = 0
###FindFiles 0004
FindFiles :C:\TestFindFile\A\B\C\D
	FindFiles return 3 entries in C:\TestFindFile\A\B\C\D\*

index from 0
FileMatch? : . (E,0,0)
FileMatch? : .. (E,0,0)
FileMatch? : E (E,0,0)
  =>return single entry
index to 1
###Cleanup 0004
Cleanup: C:\TestFindFile\A\B\C\D

###Close 0004
Close: C:\TestFindFile\A\B\C\D

###Create 0005
CreateFile : C:\TestFindFile\A\B\C
	ShareMode = 0x7
	FILE_SHARE_READ
	FILE_SHARE_WRITE
	FILE_SHARE_DELETE
	AccessMode = 0x100001
	FILE_READ_DATA
	SYNCHRONIZE
	FlagsAndAttributes = 0x2000090
	FILE_ATTRIBUTE_NORMAL
	FILE_FLAG_BACKUP_SEMANTICS
	OPEN_EXISTING

CreateFile status = 0 - lastError = 0
###FindFiles 0005
FindFiles :C:\TestFindFile\A\B\C
	FindFiles return 3 entries in C:\TestFindFile\A\B\C\*

index from 0
FileMatch? : . (D,0,0)
FileMatch? : .. (D,0,0)
FileMatch? : D (D,0,0)
  =>return single entry
index to 1
###Cleanup 0005
Cleanup: C:\TestFindFile\A\B\C

###Close 0005
Close: C:\TestFindFile\A\B\C

###Create 0006
CreateFile : C:\TestFindFile\A\B
	ShareMode = 0x7
	FILE_SHARE_READ
	FILE_SHARE_WRITE
	FILE_SHARE_DELETE
	AccessMode = 0x100001
	FILE_READ_DATA
	SYNCHRONIZE
	FlagsAndAttributes = 0x2000090
	FILE_ATTRIBUTE_NORMAL
	FILE_FLAG_BACKUP_SEMANTICS
	OPEN_EXISTING

CreateFile status = 0 - lastError = 0
###FindFiles 0006
FindFiles :C:\TestFindFile\A\B
	FindFiles return 3 entries in C:\TestFindFile\A\B\*

index from 0
FileMatch? : . (C,0,0)
FileMatch? : .. (C,0,0)
FileMatch? : C (C,0,0)
  =>return single entry
index to 1
###Cleanup 0006
Cleanup: C:\TestFindFile\A\B

###Close 0006
Close: C:\TestFindFile\A\B

###Create 0007
CreateFile : C:\TestFindFile\A
	ShareMode = 0x7
	FILE_SHARE_READ
	FILE_SHARE_WRITE
	FILE_SHARE_DELETE
	AccessMode = 0x100001
	FILE_READ_DATA
	SYNCHRONIZE
	FlagsAndAttributes = 0x2000090
	FILE_ATTRIBUTE_NORMAL
	FILE_FLAG_BACKUP_SEMANTICS
	OPEN_EXISTING

CreateFile status = 0 - lastError = 0
###FindFiles 0007
FindFiles :C:\TestFindFile\A
	FindFiles return 3 entries in C:\TestFindFile\A\*

index from 0
FileMatch? : . (B,0,0)
FileMatch? : .. (B,0,0)
FileMatch? : B (B,0,0)
  =>return single entry
index to 1
###Cleanup 0007
Cleanup: C:\TestFindFile\A

###Close 0007
Close: C:\TestFindFile\A

###Create 0008
CreateFile : C:\TestFindFile\
	ShareMode = 0x7
	FILE_SHARE_READ
	FILE_SHARE_WRITE
	FILE_SHARE_DELETE
	AccessMode = 0x100001
	FILE_READ_DATA
	SYNCHRONIZE
	FlagsAndAttributes = 0x2000090
	FILE_ATTRIBUTE_NORMAL
	FILE_FLAG_BACKUP_SEMANTICS
	OPEN_EXISTING

CreateFile status = 0 - lastError = 0
###FindFiles 0008
FindFiles :C:\TestFindFile\
	FindFiles return 3 entries in C:\TestFindFile\*

index from 0
FileMatch? : A (A,0,0)
  =>return single entry
index to 1
###Cleanup 0008
Cleanup: C:\TestFindFile\

###Close 0008
###FindFiles 0000
Close: C:\TestFindFile\

FindFiles :C:\TestFindFile\A\B\C\D\E\F\G\H
	FindFiles return 6 entries in C:\TestFindFile\A\B\C\D\E\F\G\H\*

index from 0
FileMatch? : . (b.txt,0,0)
FileMatch? : .. (b.txt,0,0)
FileMatch? : a.txt (b.txt,0,0)
FileMatch? : b.txt (b.txt,0,0)
  =>return single entry
index to 1
###Cleanup 0000
Cleanup: C:\TestFindFile\A\B\C\D\E\F\G\H

**Comment by Liryna** [comment] 2016-08-08 10:35
I don't have a working WIn7 for now.
Could you show output of filespy http://www.zezula.net/en/fstools/filespy.html when you use FindFirstFile on the Mirror device ?

**Comment by EpsilonXX** [comment] 2016-08-08 12:20
[FileSpy-FindFile.txt](https://github.com/dokan-dev/dokany/files/406745/FileSpy-FindFile.txt)

**Comment by Liryna** [comment] 2016-08-09 12:59
Sorry, it seems that FileSpy is not giving more informations :cry: 
Could you try with https://technet.microsoft.com/en-us/sysinternals/bb896645.aspx in advanced mode (Filter menu, adtionnal output enabled)
on the mirror and on local NTFS ?

**Comment by EpsilonXX** [comment] 2016-08-10 14:55
Hi Liryna,

According my regression test and if i'm correct ,the issue seems to appear with
https://github.com/dokan-dev/dokany/commit/a815463467b8b08405b8a55b69704e544b61c9cf

This one works
https://github.com/dokan-dev/dokany/commit/3083fdda2e04d8fc798a7d6cb9eafceafa8bdbaa

Here is the log from Process Monitor 3.3 ,Please rename the pdf to zip ,
[Logfile.pdf](https://github.com/dokan-dev/dokany/files/411375/Logfile.pdf)

Thx for your help.

**Comment by Liryna** [comment] 2016-08-10 18:10
Compare of the two commit linked: https://github.com/dokan-dev/dokany/compare/a815463467b8b08405b8a55b69704e544b61c9cf...3083fdda2e04d8fc798a7d6cb9eafceafa8bdbaa

Can you try to set FileSystemNameBuffer to "Dokan" as before ?
https://github.com/dokan-dev/dokany/compare/a815463467b8b08405b8a55b69704e544b61c9cf...3083fdda2e04d8fc798a7d6cb9eafceafa8bdbaa#diff-3e4a0e9bc5f5ce9956bf1c87bff87b48L51

**Comment by Liryna** [comment] 2016-08-11 10:10
And here also https://github.com/dokan-dev/dokany/compare/a815463467b8b08405b8a55b69704e544b61c9cf...3083fdda2e04d8fc798a7d6cb9eafceafa8bdbaa#diff-210b81c018cd0036b1a9abb162fb97b9L1123
Change NTFS as Dokan like before.

It is the only changes that has been made between this two commit that can change the behavior of the FS.
Dokan to NTFS has been made to make work the socket as you know. This can also behave on Win7 FindFiles. If thats the case, we can do nothing about it and thats the behavior of Win7 :( (that seems to be fix in Win10)

**Comment by EpsilonXX** [comment] 2016-08-11 15:19
I've already done some changes (like the "ntfs" change ) between the two versions without a chance.
You should be nice at least to know if someone got the same issue on seven.

I joined 2 logs from the DokanFS output
the RC3 applies a DokanQueryInformation on the \A\B\C\D\E\F\G\H 
and the original version ,it's DokanDirectoryControl


[dokanFindFirstFileOk.txt](https://github.com/dokan-dev/dokany/files/413535/dokanFindFirstFileOk.txt)
[dokanFindFirstFileOk-RC3.txt](https://github.com/dokan-dev/dokany/files/413536/dokanFindFirstFileOk-RC3.txt)

**Comment by Liryna** [comment] 2016-08-11 16:21
@EpsilonXX Thank you for the kernel logs and Process Monitor.
It show well that this only seems to happen with Dokan device and not local NTFS.

Are you sure that it is between this two commit https://github.com/dokan-dev/dokany/compare/a815463467b8b08405b8a55b69704e544b61c9cf...3083fdda2e04d8fc798a7d6cb9eafceafa8bdbaa
that the behaviour changed ?

Do you think you can find the exact commit that create it ? Sorry I have still not been able to have a working Win7....

**Comment by Liryna** [comment] 2016-09-06 20:05
@EpsilonXX any news from this ?

**Comment by magol** [comment] 2016-09-07 09:16
> You should be nice at least to know if someone got the same issue on seven.
@EpsilonXX I also see this problem in Windows 7. Very annoying :-(

**Comment by Liryna** [comment] 2016-09-07 09:25
@magol are you able to build dokan and test it on windows 7 ?
would be nice if it is between this two commit https://github.com/dokan-dev/dokany/compare/a815463467b8b08405b8a55b69704e544b61c9cf...3083fdda2e04d8fc798a7d6cb9eafceafa8bdbaa

**Comment by EpsilonXX** [comment] 2016-09-07 10:11
Hi guys,

Sorry for not answering quickly.
Thanks @magol ,I'm not feeling alone :)
I'm confident about the versions I tested but to be honest making mistake is easy when you have to switch drivers etc.
I already spent few days trying to fix it without a chance and like It's fine with Win 10 ,I didn't continue.
In future,if there is some plan to have a metadata cache inside the drivers ,that could help to reduce these effects

**Comment by Liryna** [comment] 2016-09-07 14:33
After looong testing, the issue come from the commit a815463467b8b08405b8a55b69704e544b61c9cf

**Comment by marinkobabic** [comment] 2016-09-07 23:03
Just a question. In your case the first file will be returned. Should in this case the status not be  STATUS_NO_MORE_FILES?

From my point of view STATUS_SUCCESS means,  I have filled the buffer using the found files, but there are more files so please come back to me.

**Comment by Liryna** [comment] 2016-09-08 12:08
@marinkobabic this could be the reason if the driver continue to ask the content of the same folder.
But here the driver ask the content of parent folders until `\`.

**Comment by marinkobabic** [comment] 2016-09-08 13:12
@Liryna 
Normally the output should look like this

1.  STATUS_SUCCESS for the filter a.txt and FileFullDirectoryInformation **SL_RETURN_SINGLE_ENTRY**
2. STATUS_NO_MORE_FILES for path h:\TestFindFile\A\B\C\D\E\F\G\H and FileFullDirectoryInformation 

This happens when testing using cmd.exe dir command. Can you reproduce the issue using the dir command as well? When you set the process filter inside of the filespy to cmd.exe you should get the same output like me on Windows 7 x64. Is this the case?

**Comment by Liryna** [comment] 2016-09-09 11:31
@marinkobabic dir command in C:\Users\A\B\C\D\E\F\G\H:
```
1:18:06.0268124 PM	cmd.exe	2696	CreateFile	C:\Users\A\B\C\D\E\F\G\H	SUCCESS	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a, OpenResult: Opened
1:18:06.0268265 PM	cmd.exe	2696	QueryBasicInformationFile	C:\Users\A\B\C\D\E\F\G\H	SUCCESS	CreationTime: 9/7/2016 2:34:40 PM, LastAccessTime: 9/7/2016 2:34:40 PM, LastWriteTime: 9/7/2016 2:34:40 PM, ChangeTime: 9/7/2016 2:34:40 PM, FileAttributes: D
1:18:06.0268348 PM	cmd.exe	2696	CloseFile	C:\Users\A\B\C\D\E\F\G\H	SUCCESS	
1:18:06.0269116 PM	cmd.exe	2696	CreateFile	C:\Users\A\B\C\D\E\F\G\H	SUCCESS	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a, OpenResult: Opened
1:18:06.0269214 PM	cmd.exe	2696	QueryBasicInformationFile	C:\Users\A\B\C\D\E\F\G\H	SUCCESS	CreationTime: 9/7/2016 2:34:40 PM, LastAccessTime: 9/7/2016 2:34:40 PM, LastWriteTime: 9/7/2016 2:34:40 PM, ChangeTime: 9/7/2016 2:34:40 PM, FileAttributes: D
1:18:06.0269282 PM	cmd.exe	2696	CloseFile	C:\Users\A\B\C\D\E\F\G\H	SUCCESS	
1:18:06.0269968 PM	cmd.exe	2696	CreateFile	C:\Users\A\B\C\D\E\F\G\H\.	NAME INVALID	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
1:18:06.0272646 PM	cmd.exe	2696	CreateFile	C:\Users\A\B\C\D\E\F\G\H	SUCCESS	Desired Access: Read Data/List Directory, Synchronize, Disposition: Open, Options: Directory, Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a, OpenResult: Opened
1:18:06.0272777 PM	cmd.exe	2696	QueryDirectory	C:\Users\A\B\C\D\E\F\G\H\*	SUCCESS	Filter: *, 1: .
1:18:06.0273925 PM	cmd.exe	2696	QueryDirectory	C:\Users\A\B\C\D\E\F\G\H	SUCCESS	0: .., 1: b.txt
1:18:06.0275849 PM	cmd.exe	2696	QueryDirectory	C:\Users\A\B\C\D\E\F\G\H	NO MORE FILES	
1:18:06.0275963 PM	cmd.exe	2696	CloseFile	C:\Users\A\B\C\D\E\F\G\H	SUCCESS	
1:18:06.0276934 PM	cmd.exe	2696	CreateFile	C:\Users\A\B\C\D\E\F\G\H	SUCCESS	Desired Access: Synchronize, Disposition: Open, Options: Directory, Synchronous IO Non-Alert, Open For Free Space Query, Attributes: n/a, ShareMode: None, AllocationSize: n/a, OpenResult: Opened
1:18:06.0277068 PM	cmd.exe	2696	QueryFullSizeInformationVolume	C:\Users\A\B\C\D\E\F\G\H	SUCCESS	TotalAllocationUnits: 15,439,359, CallerAvailableAllocationUnits: 6,256,041, ActualAvailableAllocationUnits: 6,256,041, SectorsPerAllocationUnit: 8, BytesPerSector: 512
1:18:06.0277151 PM	cmd.exe	2696	CloseFile	C:\Users\A\B\C\D\E\F\G\H	SUCCESS	

```

dir command on M:\A\B\C\D\E\F\G\H
http://pastebin.com/pcLPUzib

Only NO MORE FILES is used in both case.
The probleme here, is that windows request all parent folders before requesting the correct folder content.

**Comment by marinkobabic** [comment] 2016-09-09 11:40
@Liryna
Why I can't find cmd.exe in pastebin example?

**Comment by Liryna** [comment] 2016-09-09 11:43
Oups sorry here it is:

```
1:42:06.6483919 PM	cmd.exe	1316	CreateFile	\Device\Volume{d6cc17c5-1737-4085-bce7-964f1e9f5de9}\	SUCCESS	Desired Access: Synchronize, Disposition: Open, Options: Directory, Synchronous IO Non-Alert, Attributes: n/a, ShareMode: None, AllocationSize: n/a, OpenResult: Opened
1:42:06.7731972 PM	cmd.exe	1316	QueryNameInformationFile	\Device\Volume{d6cc17c5-1737-4085-bce7-964f1e9f5de9}\	SUCCESS	Name: \
1:42:06.7732097 PM	cmd.exe	1316	QueryAttributeInformationVolume	\Device\Volume{d6cc17c5-1737-4085-bce7-964f1e9f5de9}\	SUCCESS	FileSystemAttributes: Case Preserved, Case Sensitive, Unicode, ACLs, 0x100, MaximumComponentNameLength: 256, FileSystemName: NTFS
1:42:06.7732843 PM	cmd.exe	1316	CloseFile	\Device\Volume{d6cc17c5-1737-4085-bce7-964f1e9f5de9}\	SUCCESS	
1:42:06.7746770 PM	cmd.exe	1316	CreateFile	\Device\Volume{d6cc17c5-1737-4085-bce7-964f1e9f5de9}\A\B\C\D\E\F\G\H	SUCCESS	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a, OpenResult: Opened
1:42:06.7751102 PM	cmd.exe	1316	QueryBasicInformationFile	\Device\Volume{d6cc17c5-1737-4085-bce7-964f1e9f5de9}\A\B\C\D\E\F\G\H	SUCCESS	CreationTime: 9/7/2016 2:34:40 PM, LastAccessTime: 9/7/2016 2:34:40 PM, LastWriteTime: 9/7/2016 2:34:40 PM, ChangeTime: 9/7/2016 2:34:40 PM, FileAttributes: D
1:42:06.7752108 PM	cmd.exe	1316	CloseFile	\Device\Volume{d6cc17c5-1737-4085-bce7-964f1e9f5de9}\A\B\C\D\E\F\G\H	SUCCESS	
1:42:06.7772642 PM	cmd.exe	1316	CreateFile	\Device\Volume{d6cc17c5-1737-4085-bce7-964f1e9f5de9}\A\B\C\D\E\F\G\H	SUCCESS	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a, OpenResult: Opened
1:42:06.7776784 PM	cmd.exe	1316	QueryBasicInformationFile	\Device\Volume{d6cc17c5-1737-4085-bce7-964f1e9f5de9}\A\B\C\D\E\F\G\H	SUCCESS	CreationTime: 9/7/2016 2:34:40 PM, LastAccessTime: 9/7/2016 2:34:40 PM, LastWriteTime: 9/7/2016 2:34:40 PM, ChangeTime: 9/7/2016 2:34:40 PM, FileAttributes: D
1:42:06.7777597 PM	cmd.exe	1316	CloseFile	\Device\Volume{d6cc17c5-1737-4085-bce7-964f1e9f5de9}\A\B\C\D\E\F\G\H	SUCCESS	
1:42:06.7790931 PM	cmd.exe	1316	CreateFile	\Device\Volume{d6cc17c5-1737-4085-bce7-964f1e9f5de9}\A\B\C\D\E\F\G\H\.	NAME INVALID	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
1:42:06.7795053 PM	cmd.exe	1316	CreateFile	\Device\Volume{d6cc17c5-1737-4085-bce7-964f1e9f5de9}\	SUCCESS	Desired Access: Synchronize, Disposition: Open, Options: Directory, Synchronous IO Non-Alert, Attributes: n/a, ShareMode: None, AllocationSize: n/a, OpenResult: Opened
1:42:06.7799641 PM	cmd.exe	1316	QueryNameInformationFile	\Device\Volume{d6cc17c5-1737-4085-bce7-964f1e9f5de9}\	SUCCESS	Name: \
1:42:06.7799736 PM	cmd.exe	1316	QueryInformationVolume	\Device\Volume{d6cc17c5-1737-4085-bce7-964f1e9f5de9}\	SUCCESS	VolumeCreationTime: 1/1/1601 2:00:00 AM, VolumeSerialNumber: 1983-1116, SupportsObjects: False, VolumeLabel: DOKAN
1:42:06.7800390 PM	cmd.exe	1316	CloseFile	\Device\Volume{d6cc17c5-1737-4085-bce7-964f1e9f5de9}\	SUCCESS	
1:42:06.7809638 PM	cmd.exe	1316	CreateFile	\Device\Volume{d6cc17c5-1737-4085-bce7-964f1e9f5de9}\A\B\C\D\E\F\G\H	SUCCESS	Desired Access: Read Data/List Directory, Synchronize, Disposition: Open, Options: Directory, Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a, OpenResult: Opened
1:42:06.7813466 PM	cmd.exe	1316	QueryDirectory	\Device\Volume{d6cc17c5-1737-4085-bce7-964f1e9f5de9}\A\B\C\D\E\F\G\H\*	SUCCESS	Filter: *, 1: .
1:42:06.7815936 PM	cmd.exe	1316	QueryDirectory	\Device\Volume{d6cc17c5-1737-4085-bce7-964f1e9f5de9}\A\B\C\D\E\F\G\H	SUCCESS	0: .., 1: b.txt
1:42:06.7818590 PM	cmd.exe	1316	QueryDirectory	\Device\Volume{d6cc17c5-1737-4085-bce7-964f1e9f5de9}\A\B\C\D\E\F\G\H	NO MORE FILES	
1:42:06.7819766 PM	cmd.exe	1316	CloseFile	\Device\Volume{d6cc17c5-1737-4085-bce7-964f1e9f5de9}\A\B\C\D\E\F\G\H	SUCCESS	
1:42:06.7835877 PM	cmd.exe	1316	CreateFile	\Device\Volume{d6cc17c5-1737-4085-bce7-964f1e9f5de9}\A\B\C\D\E\F\G\H	SUCCESS	Desired Access: Synchronize, Disposition: Open, Options: Directory, Synchronous IO Non-Alert, Open For Free Space Query, Attributes: n/a, ShareMode: None, AllocationSize: n/a, OpenResult: Opened
1:42:06.7840137 PM	cmd.exe	1316	QueryFullSizeInformationVolume	\Device\Volume{d6cc17c5-1737-4085-bce7-964f1e9f5de9}\A\B\C\D\E\F\G\H	SUCCESS	TotalAllocationUnits: 2,097,152, CallerAvailableAllocationUnits: 1,048,576, ActualAvailableAllocationUnits: 1,048,576, SectorsPerAllocationUnit: 1, BytesPerSector: 512
1:42:06.7840791 PM	cmd.exe	1316	CloseFile	\Device\Volume{d6cc17c5-1737-4085-bce7-964f1e9f5de9}\A\B\C\D\E\F\G\H	SUCCESS	

```

**Comment by marinkobabic** [comment] 2016-09-09 12:00
This is the reason I asked for just cmd.exe

Did you try to disable Windows Defender and antivirus software?

**Comment by Liryna** [comment] 2016-09-09 12:06
Yes, I did. It changed nothing.
It is on the same Windows 7 where it work before the commit https://github.com/dokan-dev/dokany/commit/a815463467b8b08405b8a55b69704e544b61c9cf

**Comment by Liryna** [comment] 2016-09-10 06:01
@marinkobabic I begin to think that the behaviour that we have on dokan is probably the "normal" behaviour since `dir` command behave the same.
How can we be sure of this ?

**Comment by Liryna** [comment] 2016-11-02 13:52
I close this issue as wont fix because we have no idea if it is Windows 7 normal behavior or not.
If anyone has an idea why this is happening, I am willing to reopen it 👍

**Closed by Liryna** 2016-11-02 13:52 UTC
Labels: bug

**Comment by Liryna** [comment] 2019-05-10 14:29
https://github.com/dokan-dev/dokany/commit/ad0820e8dcac175f273279b61db71bb2be7d4cad
DOKAN_OPTION_OPTIMIZE_SINGLE_NAME_SEARCH option has been added to speedup the situation.
