### ISSUE TITLE
LibDokan RC3 fails to open some files

### ISSUE THREAD

**Issue by psaghelyi** [dokan-dev/dokany#236] opened 2016-05-12 12:18 UTC
# Environment
 * Windows version: Windows 8.1
 * Processor architecture: x86 (core i7)
 * Dokany version: 1.0.0 RC2
 * Library type (Dokany/FUSE): dokany
 
# Check List
  - [X] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [X] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [X] I can always reproduce the issue with the provided description below.
  - [X] I have updated Dokany to the latest version (https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.

# Description
In Dokan RC2 I could open-edit-save MSWord documents. In Dokan RC3 I cannot.
sample: [01-HttpCient-Es-A-Logolas.docx](https://github.com/dokan-dev/dokany/files/261250/01-HttpCient-Es-A-Logolas.docx)

Symptom: Open MSWord doc using WindowsExplorer and TotalCommander. They freeze then crash after certain seconds.

# Logs
[kernel.zip](https://github.com/dokan-dev/dokany/files/263341/kernel.zip)
[mirror.zip](https://github.com/dokan-dev/dokany/files/263342/mirror.zip)

**Comment by Liryna** [comment] 2016-05-12 12:35
Hi @psaghelyi ,

It is not easy and quick to reproduce like you say since every MSWord behave differently.
We will need mirror and kernel logs here.

**Comment by psaghelyi** [comment] 2016-05-13 13:19
Some refinement:
- It has the same problem on Windows10 and Windows8.1.
- You can open/edit/save the Word document if you open them from MSWord2016
- Only Explorer and TotalCommander crashes on open attempt.
- Tested on different machines, clean install
- please find the logs in the attachment
[kernel.zip](https://github.com/dokan-dev/dokany/files/263315/kernel.zip)
[mirror.zip](https://github.com/dokan-dev/dokany/files/263316/mirror.zip)

**Comment by Liryna** [comment] 2016-05-16 13:27
Hi @psaghelyi ,

I have made the test windows 10 x64 and Word 2016.
I had no issue by using your file with Explorer / Total Commander or directly from Word.

`The CreateFile was not even called so probably the root of the problem is deeper in Dokany.sys.`
I see a couple of CreateFile in your logs but there is no ReadFile request.

Can you remake the test without having other files in the same folders ?

**Comment by Maxhy** [comment] 2016-05-17 11:15
Indeed, I can reproduce your issue but this is related to network option. If you don't mount as a network drive (eg. remove /n on mirror sample) it will work fine. I believe there is a bug on latest Network Provider changes, I'm gonna check.

**Comment by Maxhy** [comment] 2016-05-17 20:04
Fixed with d3ecfb0e5d327092113430bfd7b27ee605860081, thanks for the report.

**Closed by Maxhy** 2016-05-17 20:04 UTC
Labels: Informations required
