### ISSUE TITLE
event context leak on every file lock operation when FileLockInUserMode is false

### ISSUE THREAD

**Issue by bailey27** [dokan-dev/dokany#287] opened 2016-07-09 12:31 UTC
# Environment
 * Windows version: Windows 10
 * Processor architecture: x64
 * Dokany version: current source
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x ] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x ] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x ] I can always reproduce the issue with the provided description below.
  - x[ ] I have updated Dokany to the latest version (https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.

# Description

It looks to me that DokanDispatchLock() normally leaks an event context every time it is called when FileLockInUserMode is false (which is the default setting).

This happens because it always allocates an eventContext, but when FileLockInUserMode is false, the operation shouldn't be and is not normally sent to user mode, and the irp is completed by FsRtlProcessFileLock() and not the dokany driver.  So the event context is never freed.

The only time it doesn't leak when FileLockInUserMode is false is if FsRtlCheckOplock() returns pending. But if FsRtlCheckOplock() does return pending, then the lock request will be sent to user mode, which isn't supposed to happen when FileLockInUserMode is false.

I think what it should do is, if FileLockInUserMode is false, then not allocate an event context.  And it should pass a different (new) callback to FsRtlCheckOplock() that places the operation on work queue instead of using DokanOplockComplete which will send the operation to user mode.  That is what the oplock complete in fastfat does.

I am not sure how to cause an oplock break on a lock operation to happen though.  So I don't know how to test that.

In general, I'm not having much luck at writing a working program that opens a file and breaks the oplock held by another process on some other operation besides create (e.g. a write).  But I'm working on that.

But I think the leak could be serious if somebody ran an app that did lots of file locking.

To see the leaks happening, I complied the second example on this page

https://msdn.microsoft.com/en-us/library/windows/desktop/aa365204(v=vs.85).aspx

into locktest.exe

I added this code to the driver for tracking allocates and frees of event contexts.

http://pastebin.com/VFmiv8x0

I did some normal things like dir, and cat and dd'd 1MB to the mirror drive to make sure my allloc counting was working.

Then I ran locktest.exe foo.dat

I can see towards the end of my log file that the event contexts are being leaked on every lock operation.

# Logs

Here is the log.  I set the filter to "\*contexts\*"

[locktest.zip](https://github.com/dokan-dev/dokany/files/355520/locktest.zip)

**Comment by Corillian** [comment] 2016-07-17 13:50
For the record I'm rewriting all of the event context handling for #210

**Comment by Liryna** [comment] 2016-07-17 17:59
That's great ! @Corillian , in case of you are touching at the Irp pending in the kernel and you have the time, can you check if we correctly wait that the pending Irp finish before unmount ?

**Comment by bailey27** [comment] 2016-07-18 07:37
@Liryna ,

I still cannot make a test case in which a LockFileEx() causes an oplock break.  So I cannot test the case where FsRtlCheckOplock() in DokanCommonLockControl would return STATUS_PENDING now.

But I think this bug could be fixed by 

1. not allocating an eventContext in DokanDispatchLock() if FileLockInUserMode is false.
2. removing the eventContext parameter to DokanCommonLockControl() because  DokanCommonLockControl is used only if FileLockInUserMode is false.
3. having DokanCommonLockControl() pass NULL for the callback parameter to FsRtlCheckOplock() instead of DokanOplockComplete so it will block if an oplock needs to be broken before the lock is granted.

Do you think this would be good enough?  If so,  I wouldn't mind doing the changes myself.

**Comment by Liryna** [comment] 2016-07-18 11:15
Hi @bailey27 ,

After review of the code and your proposition, this seems to be the way to fix it ! :+1: 
I just hope that FsRtlCheckOplock blocking will not create freeze...but since you have not been able to create `STATUS_PENDING` :cry: it gonna be hard to check it

**Comment by Corillian** [comment] 2016-07-18 14:55
@Liryna the changes outlined in #210 concern the user-mode driver but once I submit a PR I can certainly take a look at that for you.

@bailey27 I don't see the purpose in making changes to event context code when all of that is about to change?

**Comment by Liryna** [comment] 2016-07-18 15:00
@Corillian Seems like @marinkobabic is already taking a look at the shutdown of the device, my request can be ignored for now :smiley:  :heart: 

If your changes remove/fix this behavior, this issue can be ignored because since even @bailey27 is not able to reproduce it !

**Comment by Corillian** [comment] 2016-07-18 15:05
ok cool =)

**Comment by bailey27** [comment] 2016-07-18 15:06
I can reproduce the leak at will.  By running the Microsoft lock example program (the 2nd example from here https://msdn.microsoft.com/en-us/library/windows/desktop/aa365204(v=vs.85).aspx) I was able to leak about 12,000 event contexts.

What I can't make happen is having a file lock request cause an oplock break.

Here is my branch with the changes pushed.

https://github.com/bailey27/dokany/commit/7019544f8811ee3a844d12c005f03162bac1d2ba

**Comment by Liryna** [comment] 2016-07-18 15:11
Oh my bad >< I made a mistake, sorry @bailey27 .
Your changes are not big so I let @Corillian decide if this can be merged or we should wait #210.

**Comment by bailey27** [comment] 2016-07-18 15:25
@Liryna ,

It's okay.   I am more concerned about the leak than the oplock issue there.

I think @Corillian  wants to use  a pool of eventContexts, so I think a leak would still be a problem.

**Comment by Corillian** [comment] 2016-07-18 17:31
Is the leak in the kernel? Otherwise I don't see how the leak automatically remains when I'm completely rewriting the user-mode event handling.

**Comment by Liryna** [comment] 2016-07-18 17:56
So it gonna disappear :sunglasses:

**Comment by bailey27** [comment] 2016-07-18 18:19
@Corillian ,  yes, the leak is in the kernel-mode driver.  It's leaking non-paged kernel memory.

**Comment by Corillian** [comment] 2016-07-18 18:47
Ah ok, my changes for #210 currently have nothing to do with the kernel driver though I wouldn't be surprised if it needs to get cleaned up for proper async IO as well. I'm going to submit a PR for user-mode before I take a look at kernel-mode.

**Comment by bailey27** [comment] 2016-07-18 19:48
@Liryna,

 I went ahead and made a pull request.

**Comment by Liryna** [comment] 2016-07-18 20:44
Fixed with @bailey27 contribution https://github.com/dokan-dev/dokany/pull/290
Thanks all of you !

**Closed by Liryna** 2016-07-18 20:44 UTC
Labels: bug
