### ISSUE TITLE
Windows 11 - Saving file by notepad is not working

### ISSUE THREAD

**Issue by cji80** [dokan-dev/dokany#1240] opened 2024-08-14 07:44 UTC
# Environment
 * Windows version:  Windows 11 (23H2 OS build 22631.4037)
 * Processor architecture: Intel x64
 * Dokany version:  1.4.1.1000 and latest version 2.1.0.1000
 * Library type (Dokany/FUSE):  Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
Hi. 
I found a bug that file saving by Windows 11's notepad is not working on mounted drive.
Notepad version is 11.2406.9.0.
I checked that Windows 11's Notepad does not request write permission just before saving a file.
Windows 10' s notepad requests write permission like GENERIC_WRITE before saving a file, so it works normally.
Could I know is it bug?

Thank you.

**Comment by Liryna** [comment] 2024-08-14 11:24
Hi @cji80 ,

Could you explain how you did the test and share the logs of the sample that failed ?

**Comment by Liryna** [comment] 2024-08-14 15:26
I was able to reproduce the issue and looks like now it requires to use the mount manager option. It worked after using `/o` option with the mirror.
https://github.com/dokan-dev/dokany/blob/7f25947970c1dc23cd3be9a0dbdb41f96e54f513/dokan/dokan.h#L97-L104

**Comment by cji80** [comment] 2024-08-17 13:29
@Liryna Thanks for your reply.
I will test it as soon as possible.

**Comment by cji80** [comment] 2024-08-19 00:39
@Liryna Hi.
After adding the DOKAN_OPTION_MOUNT_MANAGER option, file saving in Windows 11 Notepad proceeded normally.
Thank you very much!!

**Comment by koimatcha** [comment] 2024-09-08 15:02
Hi.
This issue seems to be resolved by Notepad version 11.2407.8.0.

**Comment by Liryna** [comment] 2024-09-13 20:01
Glad that was fixed by Microsoft 🥳 Thanks @koimatcha for letting us know

**Closed by Liryna** 2024-09-13 20:01 UTC
