### ISSUE TITLE
PDF does not open in Microsoft Edge

### ISSUE THREAD

**Issue by g-fusion** [dokan-dev/dokany#340] opened 2016-09-15 13:45 UTC
# Environment
 * Windows version:  Win 10 
 * Processor architecture: x64
 * Dokany version: 1.0.0 RC4
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [ x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [ x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [ x] I can always reproduce the issue with the provided description below.
  - [ x] I have updated Dokany to the latest version (https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.

# Description
Try to open pdf file with Microsoft Edge using either C or C# Implementation.
The Microsoft Edge trying to open it, but never does. 

# Logs
Please attach in separate files: mirror output, library logs and kernel [logs](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan).
In case of BSOD, please attach minidu
[Dokany_CImpl_PDF_TestLog.txt](https://github.com/dokan-dev/dokany/files/474774/Dokany_CImpl_PDF_TestLog.txt)
mp or dump analyze output.

**Comment by melak47** [comment] 2016-09-15 20:21
I can reproduce this with 0.74 as well.
It doesn't matter whether I try to open the file in Edge from explorer, or by navigating to `file://Q:/file.ext`, and it doesn't just affect PDF files.
This doesn't appear to be a problem with UWP apps in general, for example the "Photos" app has no trouble opening pictures on a dokan(y) filesystem.

**Comment by Maxhy** [comment] 2016-09-15 20:48
This was a known issue but should be fixed today thanks to mount manager support (`/o` on mirror sample).

**Comment by g-fusion** [comment] 2016-09-16 07:03
I can confirm that using manager option /o, C and  C# Implementation is working.
Thank you!

**Closed** 2016-09-16 07:32 UTC
Labels: bug

**Comment by g-fusion** [comment] 2016-09-21 13:34
Hi,

I noticed a small side effect using Mount Manager as solution for the above bug i.e.
when using Mount Manager and check Properties of a Folder you do NOT have Size, Size on disk, Contains props.
![mountmanager](https://cloud.githubusercontent.com/assets/20126958/18712882/115c0ac0-8019-11e6-8a93-caf4027ce4f4.png)

Regards,
g-fusion

**Comment by Rondom** [comment] 2016-09-21 13:35
Looks like a bug to me. Maybe you could file a separate issue for that.

**Comment by g-fusion** [comment] 2016-09-21 13:37
I could, but it looks somehow related to the initial one i posted.

**Comment by g-fusion** [comment] 2016-09-26 08:00
Hello,

Do you want me to open new issue for this one or we can continue in this one?

BR,
g-fusion

**Comment by Liryna** [comment] 2016-09-26 11:40
Hi @g-fusion ,

Yes you should open new issue for this since it is not related.

**Comment by AndirNotes** [comment] 2018-03-12 16:02
The same issue could be reproduced for mounted folder even with mirror.exe. Please, reopen.

**Comment by Liryna** [comment] 2018-03-12 16:19
Hi @AndirNotes ,

Mounted folder cannot use the mount manager option. Please try directly with `/o` and with a driver letter.

**Comment by AndirNotes** [comment] 2018-03-12 23:04
Hi, Liryna,

Yes, you right, it certainly does work with mount manager option and drive letter. But still it doesn't work for a mounted folder, so it looks like a bug for me. 
User just can't open any PDF's in Windows 10 (with default Edge browser) if they are located inside a mounted folder handled by Dokan driver. Using a drive letter instead of a mounted folder could be a workaround, but it's not an option for some cases.

**Comment by Liryna** [comment] 2018-03-13 22:34
@Rondom The combination is not allowed if i remember. If not, we should return an error i agree. 

It is a windows limitation as far as i know and seen. If someone find a reason or a way to make it work, i have no problem to reopen it.

**Comment by AndirNotes** [comment] 2018-03-15 08:49
Hi, @Liryna  and @Rondom 

The problem is not with flags combination, but with opening any PDF in Windows 10 from Dokan mounted folder. 
This doesn't look like a Windows limitation, I've checked Box.Net Drive solution (which uses CBFS Connect driver underhood) and it works perfectly in the same conditions.
