### ISSUE TITLE
FUSE stat attributes wrong

### ISSUE THREAD

**Issue by gang929** [dokan-dev/dokany#234] opened 2016-05-11 08:22 UTC
In dokan fuse, when readdir is called, dokanfuse use the stat for fill file&dir attr, but stat define is depends platform. 
For example,  the mingw stat define is different to linux,  so, when compile app with dokanfuse, must use the dokanfuse compile platform!
In my wdfs port project, I use mingw compile, so the dir, file length, file create date, file modify date is not correctly convert and display.
Have any way to solve this problem?

**Comment by Liryna** [comment] 2016-05-11 08:36
`the mingw stat define is different to linux` could you link this part of code in the dokan fuse ?
`In my wdfs port project, I use mingw compile` So wdfs is using mingw stat at this moment ? and dokan fuse build with mingw does not ?

**Comment by gang929** [comment] 2016-05-11 10:03
in wdfs' readdir interface， as below, the filler will use  file stat  to fill
```
wdfs_readdir(const char *localpath, void *buf, fuse_fill_dir_t filler, off_t offset, struct fuse_file_info *fi)
```
in mingw, the stat define as below 
```
 struct stat {
    _dev_t st_dev;
    _ino_t st_ino;
    unsigned short st_mode;
    short st_nlink;
    short st_uid;
    short st_gid;
    _dev_t st_rdev;
    _off_t st_size;
    time_t st_atime;
    time_t st_mtime;
    time_t st_ctime;
  };
```
but in dokanfuse, then function  convertStatlikeBuf in utils.h use stat maybe as below (depends on dokanfuse compile env)
```
struct stat {
.......
    struct timespec st_atim;            /* Time of last access.  */
    struct timespec st_mtim;            /* Time of last modification.  */
    struct timespec st_ctim;            /* Time of last status change.  */
.......
}
```
It seems that is not binary compatible.

**Comment by Liryna** [comment] 2016-05-11 11:48
Ok I see, so it would mean that:
https://github.com/dokan-dev/dokany/blame/f5afbea312cf69fcd217cb14fb2af51067d89b83/dokan_fuse/include/fuse_win.h#L74

should be changed to: `typedef struct timespec time_t;` ?

**Comment by gang929** [comment] 2016-05-11 13:15
NO, this is a  binary compatible problem, only changing the st_xxxx define  can not solve it.
In order to solve this problem，It should Export all struct used by Dokanfuse and App developed with Dokanfuse.
For example, the stat struct can be export as FUSE_STAT, When other App developing  with dokanfuse, it should convert it's stat to FUSE_STAT,  to ensure the binary compatibility of stat struct.

**Comment by gang929** [comment] 2016-05-11 13:38
OH....dokanfuse has exported stat as bleow
`#define FUSE_STAT stat64_cygwin`
I didn't see，  I always thought that dokanfuse used the system define stat.
let me try to convert the stat stuct  in wdfs project.

**Comment by Liryna** [comment] 2016-05-11 18:25
@gang929 have you been able to fix your issue by using directly FUSE_STAT ?

**Comment by gang929** [comment] 2016-05-12 02:47
before filler stat, i convert stat to fuse_stat
```
static void stat2fuse_stat(struct stat *stat, struct FUSE_STAT *fuse_stat)
{
	fuse_stat->st_dev = stat->st_dev;
	fuse_stat->st_ino = stat->st_ino;
	fuse_stat->st_mode = stat->st_mode;
	fuse_stat->st_nlink = stat->st_nlink;
	fuse_stat->st_uid = stat->st_uid;
	fuse_stat->st_gid = stat->st_gid;
	fuse_stat->st_rdev = stat->st_rdev;
	fuse_stat->st_size = stat->st_size;
	fuse_stat->st_atim.tv_sec = stat->st_atime;
	fuse_stat->st_mtim.tv_sec = stat->st_mtime;
	fuse_stat->st_ctim.tv_sec = stat->st_ctime;
	fuse_stat->st_blksize = 0;
	fuse_stat->st_blocks = 0;
	fuse_stat->st_birthtim.tv_sec = 0;
}
....................
	struct FUSE_STAT fuse_stat;
	memset(&fuse_stat, 0, sizeof(fuse_stat));
	stat2fuse_stat(&stat, &fuse_stat);
	filler(buf, filename, &fuse_stat, 0))
```
the dir can be display correctly, but the file size is error, no matter set  fuse_stat->st_size to XXXX, in windows explore all file size is a same value(1463019399, 1463020793, ...Not fixed, each refresh will change) 
and the file modify/create time also has error, can not be display

**Comment by Liryna** [comment] 2016-05-12 06:30
There is probably an issue in dokan fuse wrapper in the conversion stats <-> windows

**Comment by gang929** [comment] 2016-05-12 06:49
yes, the fuse sample mirror.exe has same issue.
run mirror.exe v
the new disk V: can not display file size and date correctly.

**Comment by gang929** [comment] 2016-05-16 14:10
I try to fix the issue

**Comment by Liryna** [comment] 2016-05-16 18:44
Hi @gang929 ,

I have taken a look and it seems like there is not real issue with the dokan fuse implementation as I found now.

The probleme of wrong size/time and such come from the fuse mirror that only list files and does not do much else...https://github.com/dokan-dev/dokany/blob/master/samples/fuse_mirror/fusexmp.c#L96
Normally it should fill the stat struct before calling `filler`.

**Comment by gang929** [comment] 2016-05-17 13:39
has fixed with https://github.com/dokan-dev/dokany/pull/242

**Comment by jetwhiz** [comment] 2016-05-19 20:47
I can confirm this issue ... all of my file sizes are being reported as 100+ PB in size, and randomly changes upon refresh.

**Comment by Liryna** [comment] 2016-05-19 20:51
@jetwhiz how are you building the dokan fuse and your filesystem ? (VC, Cygwin, msys)
Here is where the size is converted from fuse to dokan: https://github.com/dokan-dev/dokany/blob/master/dokan_fuse/include/utils.h#L40
Can you try to print and see if the conversion is good in your case ?

**Comment by jetwhiz** [comment] 2016-05-19 21:49
I am building with Visual Studio 2015.  For the target machine I am using your installer (provided in your releases), though.  My target machine is a 32-bit Windows 7 installation.  Also, the "Size on Disk" is being reported correctly, but the "Size" field is incorrect. 
 
Is there a way I can print this value out from within our readdir() function?

**Comment by Liryna** [comment] 2016-05-20 05:46
In your readdir; the callback is `walk_directory`:
https://github.com/dokan-dev/dokany/blob/468e08ebfd74ce4d282896c7c3eeecf85e94a882/dokan_fuse/src/fusemain.cpp#L265

In this fonction there is `convertStatlikeBuf` that handle the conversion of your stat to dokan windows informations:
https://github.com/dokan-dev/dokany/blob/468e08ebfd74ce4d282896c7c3eeecf85e94a882/dokan_fuse/src/fusemain.cpp#L302
https://github.com/dokan-dev/dokany/blob/master/dokan_fuse/include/utils.h#L40

You can print there all the informations.
For simple test and not get floor, you can simple use `cmd.exe`, go in a folder and use `dir` command. Only `readdir` is going to be called.

**Comment by gang929** [comment] 2016-05-20 05:56
print:  wdfs.exe with dokanfuse1.dll  build by mingw.
 the sizeof(fuse_stat) in dokanfuse1.dll not equal sizeof(fuse_stat) in wdfs, because In VS2015(build with x86), the mode_t and nlink_t is 4bytes, but In mingw32, they are 2bytes, otherwise, the timespec is 16bytes in VS2015, but 8bytes in mingw.

**Comment by Liryna** [comment] 2016-05-20 06:14
@gang929 that’s why `dokan_fuse` has to be built with Cygwin (same as wdfs). You will have `cygdokanfuse1.dll`. Therefore the `FUSE_STAT` that has the same in both (fuse and wdfs) since the same compiler has been used.

It is normal that you have a difference between VS and Cygwin. And you will have another difference from VS and Msys probably.
We cannot **force** size type as you do because it will probably not work in another Linux like environment.

Or there is something here that I don't understand.

**Comment by gang929** [comment] 2016-05-20 06:25
so, if I use mingw, this can not be correctly!  
it seems that I must build my app using the same environment with building dokanfus also can solve the problem.

**Comment by jetwhiz** [comment] 2016-05-21 09:59
@Liryna 

Here is the code I am using to print the values: 

````C++
  fprintf(stderr, "fuse: name: %s\n", name.c_str());
  fprintf(stderr, "fuse: st_size: %I64d\n", stbuf->st_size);
  fprintf(stderr, "fuse: nFileSizeLow: %lu\n", find_data->nFileSizeLow);
  fprintf(stderr, "fuse: nFileSizeHigh: %lu\n\n", find_data->nFileSizeHigh);
````

Here is the output I am getting: 

![virtualbox_win7_21_05_2016_11_54_43](https://cloud.githubusercontent.com/assets/533569/15447713/5171f2f2-1f4b-11e6-953c-ffbc270cdc41.png)

**Comment by Liryna** [comment] 2016-05-21 11:22
Oh great @jetwhiz ! Thank you !

So as we has seen, there is sometimes good informations about `libeay32.dll` (when st_size = 1209856 i guess).
`convertStatlikeBuf ` is called in two different places:
`walk_directory` https://github.com/dokan-dev/dokany/blob/468e08ebfd74ce4d282896c7c3eeecf85e94a882/dokan_fuse/src/fusemain.cpp#L302
`get_file_information` https://github.com/dokan-dev/dokany/blob/468e08ebfd74ce4d282896c7c3eeecf85e94a882/dokan_fuse/src/fusemain.cpp#L626

Can you add some print in this two fonctions to see whish is giving "wrong" information to the system  (st_size= 1432608.....) ?

**Comment by jetwhiz** [comment] 2016-05-21 11:56
It looks like the problem is when walk_directory is called: 

````cmd
fuse: walk_directory name: libeay32.dll
fuse: name: libeay32.dll
fuse: st_size: 152832908540914282
fuse: nFileSizeLow: 2006067818
fuse: nFileSizeHigh: 35584184

fuse: get_file_information fname: /libeay32.dll
fuse: name: /libeay32.dll
fuse: st_size: 1209856
fuse: nFileSizeLow: 1209856
fuse: nFileSizeHigh: 0
````

The code is setting ``stat = *stbuf;`` and is not filling in the rest of the stat parameters (with getattr, I assume).  

````C
  struct FUSE_STAT stat = {0};

  if (stbuf != NULL)
    stat = *stbuf;
````

We are running: 

````C++
struct stat_st st;
st.st_ino = inode;
st.st_mode = fileType << 12;

if (walk_directory(buf, name.c_str(), &st, 0)) break;
````

From what I understand, FUSE should only be looking at st_ino and st_mode in the provided struct, and should provide the rest on its own: 

>  Optionally, create a struct stat that describes the file as for getattr (but FUSE only looks at st_ino and the file-type bits of st_mode). 

https://www.cs.hmc.edu/~geoff/classes/hmc.cs135.201001/homework/fuse/fuse_doc.html#readdir-details

**Comment by Liryna** [comment] 2016-05-21 12:05
Ok so dokan_fuse 'should' force getattr since Windows use readdir informations compared to libfuse.

Can you test: `if (walk_directory(buf, name.c_str(), NULL, 0)) break;`
It should force the getattr as you seen.

If it work, we are going to force the getattr everytime.

**Comment by jetwhiz** [comment] 2016-05-21 12:14
Yes, it works correctly if I pass a NULL struct stat in (both the sizes and the dates are fixed).

**Comment by Liryna** [comment] 2016-05-23 11:49
Fixed with https://github.com/dokan-dev/dokany/commit/0b350fddd76f4da811e7a037e2fcfa57f87070f8

Thank you @jetwhiz, @gang929 for your report, time and help !

**Closed by Liryna** 2016-05-23 11:49 UTC
Labels: bug, help wanted
