### ISSUE TITLE
oplocks not working properly

### ISSUE THREAD

**Issue by bailey27** [dokan-dev/dokany#285] opened 2016-07-07 15:46 UTC
# Environment
 * Windows version: Windows 10
 * Processor architecture: x64
 * Dokany version: 1.0.0-RC3, current source, my fork with oplock fixes
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x ] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x ] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x ] I can always reproduce the issue with the provided description below.
  - [ x] I have updated Dokany to the latest version (https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.

# Description

I built this program that does an oplock on a file

https://blogs.msdn.microsoft.com/oldnewthing/20130415-00/?p=4663

I compiled it to oplocktest.exe

if I do this on a non-mirror drive, then it works as they say it should

```
[cmd window 1]
C:\tmp> echo blah > foo.txt
C:\tmp> c:\tmp\oplocktest.exe foo.txt

[in cmd window 2]
C:\tmp> echo blah > foo.txt
[pause]
C:\tmp> [cmd prompt returned with no error message]

[in cmd window 1]
Cleaning up because somebody wants the file...
Closing file handle
```

But on a mirror drive, even though oplocktest also prints "Cleaning up because somebody wants the file...Closing file handle", in cmd window 2, where echo is trying to write to the file, it prints
```
The process cannot access the file because it is being used by another process
```

It looks like even though the process with the oplock releases it, the createfile fails anyway due to a sharing violation.

# Logs
Here are the logs (driver and mirror)

[oplock_logs.zip](https://github.com/dokan-dev/dokany/files/352522/oplock_logs.zip)

**Comment by bailey27** [comment] 2016-07-07 15:53
The logs are from a driver built from a fresh clone of https://github.com/dokan-dev/dokany.git done about a half hour ago.

**Comment by bailey27** [comment] 2016-07-07 16:15
Also, with mirror, in cmd window 2, it immediately prints the "The process cannot access the file because it is being used by another process" before oplocktest has a chance to release the oplock.

On the C: drive the echo blah > foo.txt in cmd widow 2 pauses until oplocktest says it's cleaned up and closed the handle.

**Comment by bailey27** [comment] 2016-07-07 16:47
I stepped through it in the debugger when cmd window 2 tries to open the file.

The thing I noticed that was strange was FsRtlCheckOplock() returned STATUS_SUCCES and not STATUS_PENDING.  

I would think that in this case, it should return pending, and the create would proceed after the oplock was released.

**Comment by bailey27** [comment] 2016-07-07 18:46
This is sort of interesting.

When I use the echo command to write to the file, oplocktest does get the oplock break on the mirror drive.

But when I run this test program (writetest) to write to the file.

http://pastebin.com/6XtQeyt5

Then on the mirror drive, oplocktest never gets the break.

On my C: drive, writetest's createfile blocks until oplocktest closes the handle.  

On M: writetest's createfile returns immediately with lasterr 32 (sharing violation) and oplocktest never gets the oplock break.

**Comment by Liryna** [comment] 2016-07-07 20:21
:open_mouth: that's interesting and a good test !
Unfortunatly I do not really have a reason to give for this behaviour.

But it seems to look the same as https://github.com/dokan-dev/dokany/issues/283

**Comment by marinkobabic** [comment] 2016-07-07 20:59
What happens when you set the CompletionRoutine to NULL. It should block as well.

**Comment by bailey27** [comment] 2016-07-07 21:26
If I change the oplock flags in oplocktest to include OPLOCK_LEVEL_CACHE_WRITE, then it works.

```
<   OPLOCK_LEVEL_CACHE_READ | OPLOCK_LEVEL_CACHE_HANDLE,
---
>   OPLOCK_LEVEL_CACHE_WRITE | OPLOCK_LEVEL_CACHE_READ | OPLOCK_LEVEL_CACHE_HANDLE,
```

I sounds to me like (from https://msdn.microsoft.com/en-us/library/windows/desktop/ee681828(v=vs.85).aspx)

`Using the FSCTL_REQUEST_OPLOCK control code with the RequestedOplockLevel member set to OPLOCK_LEVEL_CACHE_READ | OPLOCK_LEVEL_CACHE_HANDLE grants an oplock of type RH. An RH oplock is similar to the filter oplock granted by the FSCTL_REQUEST_FILTER_OPLOCK control code. However, note that the filter oplock allows only one client to hold an oplock on a file at a time; FSCTL_REQUEST_OPLOCK allows multiple clients at a time to have the RH lock on a file. Another difference is that FSCTL_REQUEST_FILTER_OPLOCK requires an oplock break acknowledgment before writes can occur, where FSCTL_REQUEST_OPLOCK does not because the oplock break notification is advisory-only and writes are allowed to go ahead without acknowledgment. For more information, see Breaking Oplocks.`

It sounds like maybe dokany is behaving correctly in not breaking the oplock if only OPLOCK_LEVEL_CACHE_READ | OPLOCK_LEVEL_CACHE_HANDLE were specified when it was created.  But not breaking it causes the create to proceed, which fails because of a sharing violation because the underlying (root) fs has no idea about the oplock.

I don't see anything different about how DokanOplockRequest() and FatOplockRequest() are handling this.  

I did try it with a fat32 formatted usb drive and with only OPLOCK_LEVEL_CACHE_READ | OPLOCK_LEVEL_CACHE_HANDLE it works as on my ntfs C: drive.

**Comment by bailey27** [comment] 2016-07-07 21:28
@marinkobabic ,
I tried setting in the create in the driver the completion routine to null.  But with this test (with the original flags) FsRtlCheckOplock() always returns STATUS_SUCCESS regardless.

**Comment by bailey27** [comment] 2016-07-09 17:25
I think this issue has something to do with this code being commented out

https://github.com/dokan-dev/dokany/blob/c226ba58470638d45134498c178bcdf4b1b346e3/sys/create.c#L917-1024

**Comment by bailey27** [comment] 2016-07-09 18:13
If I enable the commented-out code (and the other two related bits of code), then the oplock test behaves the same on the mirror drive as on c:

But there are now some intermittent failures with winfstest http://pastebin.com/R6ebjjFi

I guess maybe before the oplocks were put in, that the driver relied on user mode to deal with  sharing?  I think now with the oplocks the driver it needs to do some of that itself.

**Comment by bailey27** [comment] 2016-07-09 19:12
I can't reproduce those winfstest failures anymore.

**Comment by bailey27** [comment] 2016-07-09 20:31
This code that was commented out leaks eventContext/ccb/fcb whenever a sharing violation occurs and there is no oplock to break.  I can see the number of allocated eventContexts go up by one every time winfstest generates a sharing violation (on purpose). 

I put in frees of the eventContext, ccb, and fcb if that happens, and also where there is an unexpected error status.

I haven't been able to reproduce the winfstest errors again.  They happened only that one time and not since.  I think the leaks didn't cause them.

I think the reason the code had the warning comment  was maybe because it was leaking fcbs and the leaked fcbs were causing the sharing violations.

I don't see anything else wrong with this code, and I think it is maybe needed for handling oplocks correctly.

**Comment by Liryna** [comment] 2016-07-09 20:42
@bailey27 Hi,

yes the comment was part of the oplock implementation but had an huge issue of sharing violation. You was absolutely not able to copy past files from Explorer. 

Does that mean that by freeing context when an error happen, Sharing violation issue dissappear? If yes, this code can be uncomment :D

By the way, I really wanted to thank you for the help and the time you take to make all the test. I currently do not have the time to investigate on it so it is very a pleasure to see such people as you!

**Comment by bailey27** [comment] 2016-07-09 21:14
I can copy and paste files in explorer.  

I am pretty sure this leak was causing the sharing violations.  I think it was because of fcb->ShareAccess in the leaked fcb. 

You're welcome.  I haven't worked on something like this in a long time, and I enjoy it.

I will test it some more and then put then push my branch so you can see it.

**Comment by bailey27** [comment] 2016-07-12 11:19
@Liryna ,

I have a working solution.  Here is my branch.

https://github.com/bailey27/dokany/commit/113097cf092db6323e21d9e3c9a491cb32151464

 But I want to point out some issues.

First, DokanOplockComplete() is what the driver uses for when it wants to to be called back after an oplock is broken.

DokanOplockComplete simply sends the request to user mode.

I think in most cases that is ok. I most cases, the driver calls FsRtlCheckOplock() with DokanOplockComplete as the callback right before it would have called DokanRegisterPendingIrp() anyway.  So there is nothing else to be done besides send the request to user mode.

The problem I see with using DokanOplockComplete as the callback in create is that in both cases where it is used, but especially in this code that was commented out before, it is being used when the driver still has stuff that needs to be done for this create that won't happen if it gets pended to user mode at that point.

The the function used by fastfat for these pending oplock  things  posts the operations to a work queue. The work queue function dispatches the operation over again, from the beginning.

I don't think that is necessary for the dokan driver, but I do think that dokan's create needs to block instead of using the callback.  It definitely needs to do this in the code that was commented out, and I think it should do it (pass NULL and block) in the 2nd case that was already there.

Another thing I found out is that when FsRtlOplockBreakH() (and I assume FsRtlCheckOplock()) either returns from a blocking call or calls the callback, that all that means is that the oplock break has been sent to the owner.  It doesn't mean that the owner has necessarily released the resource it had the oplock on (closed the file).

When I have my oplocktest sleep after getting the oplock break and before closing the file, I can see that my writetest program, even though calls CreateFile() only one time and succeeds, that the writetest process sends two creates to the driver.  The first one fails with sharing violation because oplock test is still sleeping.  The second one succeeds.  I think win32 is doing this.

That's just information.  I was confused by this for a while.

Another thing I noticed is that the Io*ShareAccess() functions are supposed to be protected by a lock (the fcb->Resource), but they weren't being locked.  I fixed that in create and also the one in cleanup.

It looks to me that before this code was un-commented-out, that the driver was removing share access in cleanup and in DokanCompleteCreate() (in the case of failure), but it was never setting the share access before.

Finally, I think in create it was too easy to leak an fcb, ccb and eventContext.  

I changed it so the finally automatically frees what should be freed based on NT_SUCCESS(status).

**Comment by Liryna** [comment] 2016-07-13 11:26
@bailey27 Thank you for your full explanation ! 

The code seems to be good for me. 
Is there a reason for removing https://github.com/bailey27/dokany/commit/113097cf092db6323e21d9e3c9a491cb32151464#diff-86caa6b16e4044982075fe5d5bc59915R101 ?

After all your test, would you say that oplock are now correctly implemented and pass  oplocktest.exe and other test without issue with your patch ?

**Comment by bailey27** [comment] 2016-07-14 09:32
@Liryna ,

That dbg print was suggested by @marinkobabic  when we were debugging the Word issue.

I commented it out because it was coming through my filter in dbgview and I wanted to make the output less verbose.   I guess I should have used an exclude filter instead.

I will put it back in. 

My patch does solve the issue of RH (read-handle) oplocks not getting broken when somebody opens the file for Write.  It doesn't break anything else as far as I can tell.

There is still an issue with FILE_OPEN_REQUIRING_OPLOCK.

https://github.com/dokan-dev/dokany/blob/c226ba58470638d45134498c178bcdf4b1b346e3/sys/create.c#L1069-1071


```
[DokanFS]    FsRtlOplockFsctrl failed with 0xc000000d, fileName = \foo.txt, fileCount = 1

```

This is the place where the failure was occurring which caused the fcb leak which caused the Word problem  https://github.com/dokan-dev/dokany/issues/249

I checked out the current dokany source without my patch, and it happens there as well.

I noticed it now because I wrote a program to test FILE_OPEN_REQUIRING_OPLOCK

According to MSDN: 

> If the IRP is an IRP_MJ_CREATE request, FsRtlOplockFsctrl can be used to request a pending filter opportunistic lock if all of the following conditions are true:
The value of the OpenCount parameter must be 1.
The value of the DesiredAccess parameter for the IRP_MJ_CREATE request must be FILE_READ_ATTRIBUTES.
The value of the ShareAccess parameter for the IRP_MJ_CREATE request must be FILE_SHARE_READ | FILE_SHARE_WRITE | FILE_SHARE_DELETE.


And according to filespy 
```
1	11:01:59.522		createwithoplock.exe	IRP_MJ_CREATE	00000884	0000000000000000	M:\foo.txt	STATUS_INVALID_PARAMETER	FILE_OPEN CreOpts: 00010000 Access: 00000080 Share:  00000007 Attrib: 00000080

```

And according to dbgview, the OpenCount (which is the fileCount in the fcb) is 1

So I have no idea why it fails on my mirror drive.  It works on C:

I also tried to test FILE_COMPLETE_IF_OPLOCKED.  The code looks like it will return a sharing violation and not STATUS_OPLOCK_BREAK_IN_PROGRESS  if the file is oplocked. I was unable to make a test of this flag that returned STATUS_OPLOCK_BREAK_IN_PROGRESS on my C: drive.  I always get a sharing violation on C:, which is what happens on M:.  So I don't know if there is really any problem there.

**Comment by Liryna** [comment] 2016-07-14 13:34
@bailey27 , I tested you branch https://github.com/bailey27/dokany/tree/oplock_share_access

and I am unable to copy past files in the same folder :cry: on windows 10.
Copy into another directory work but copy in the same location: no new file created, nothing happen.
This can reproduce by simply select a file and `ctrl +c / ctrl +v`

**Comment by bailey27** [comment] 2016-07-14 19:09
@Liryna ,

I'm sorry, I didn't test that.

It looks like what happens is explorer has the file open.  Then it tries to open it again with incompatible sharing but also with FILE_CREATE.   The driver returns sharing violation instead of STATUS_OBJECT_NAME_COLLISION.  And that's why explorer doesn't work.

I changed it to check and see if the refcount is > 1 on the fcb and the disposition is FILE_CREATE early, and in that case return STATUS_OBJECT_NAME_COLLISION.

Now ctrl+c/ctr_v on a file works.

Also, the driver was setting disposition only if the volume was read only.

I needed it more early, and I didn't see any reason not to always set it near the begging.

Here is my commit about this

https://github.com/bailey27/dokany/commit/2bc3bdad93524953ee5023c75a4b8532aa4f184a


I think there could be other cases like this, where the driver might return a sharing violation instead of some other error that the ntfs driver checks for before checking sharing.

**Comment by Liryna** [comment] 2016-07-14 20:03
Thank you @bailey27 for your contribution and the quick fix ! :heart: 
I am able to copy files without issues !
Your patch has been merged to the master :smiley: !

**Closed by Liryna** 2016-07-14 20:03 UTC
