### ISSUE TITLE
After 1 hour of sleep mirror.exe stops unexpectedly

### ISSUE THREAD

**Issue by Rambalac** [dokan-dev/dokany#413] opened 2016-12-22 15:01 UTC
# Environment
 * Windows version: Windows 10 Pro x64 v1607 14393.576
 * Processor architecture: x64 Core i7-4650U 
 * Dokany version: 1.0.1.1000 (tested both normal and dbg)
 * Library type (Dokany/FUSE): Dokany/mirror
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [x] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI.

# Description
On Surface Pro 3 after about 1 hour device sleep Mirror.exe stops unexpectedly and drive get unmounted.

mirror.exe runned as ```/r c:\ /l m /d```

Actually first time noticed by one of users of my dokan.net based app also with some Surface device.

Have no other laptop to try.

Tried latest snapshot 1.0.1-50 3e2320ea but it does not work at all. 
```dokanctl /v``` returns 
```
Dokan version : 100
Dokan Error: Failed to open \\.\Dokan_1 with code 2
Dokan driver version : 0x0
```
Rebooted after uninstalling other dokany and rebooted after installing this one.

# Logs
[mirror.zip](https://github.com/dokan-dev/dokany/files/668994/mirror.zip)

# Support
 - Usage: personal - production
 - Support ability:

**Comment by Liryna** [comment] 2016-12-22 15:10
Hi @Rambalac ,

Regarding the snapshot, it seems like the driver is not installed.
Did you import the certificate before installing it ?
https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot

Do you mean the computer was in sleeping mode and you turn it on and the device is dismounted ?
Does the behavior also happen with you put it in sleeping mode, wait 5min and come back ?

(I don't have a laptop at all but I probably see what is happening.)

**Comment by Rambalac** [comment] 2016-12-23 07:24
Regarding the snapshot, I did download cert folder and run ```Powershell.exe -executionpolicy remotesigned -File .\cert\dokan-import.ps1``` from its parent folder under elevated cmd.

Yes, when I turn it back device is already dismounted.

If I put laptop to sleep for short time like few minutes there is no problem.

**Comment by marinkobabic** [comment] 2016-12-23 09:44
Kernel log is needed because it's the kernel which did the unmount.

Am 23.12.2016 08:24 schrieb "Rambalac" <notifications@github.com>:

**Comment by plttn** [comment] 2017-01-15 23:47
While I'm repro-ing this on Keybase FS, not `mirror.exe`, I'm also seeing similar behavior on a Surface Book. KBFS will unmount after the book being asleep for 15 minutes or longer or so, and even after resuming from hibernate KBFS will not successfully remount. A reboot is required for the FS to come back up.

**Comment by Rondom** [comment] 2017-05-01 08:24
This needs kernel logs to analyse the cause of the unmount.

**Comment by plttn** [comment] 2017-05-26 21:13
@Rondom I've just repro'd `mirror.exe` stopping after the Surface Book being closed for long enough to enter the InstantGo state. Where should I send kernel log to, as I'm not sure it's 100% safe to post in a public forum?

**Comment by marinkobabic** [comment] 2017-05-26 22:17
Hi Jack

Just remove the pc information at the beginning of the log and upload the
log here. There are no confidential information inside.

Thx Marinko

Am 26.05.2017 23:13 schrieb "Jack Platten" <notifications@github.com>:

**Comment by plttn** [comment] 2017-05-26 22:30
This isn't a log from boot, but contains me closing the book and when I woke it back up, mirror.exe had ended. 

https://gist.githubusercontent.com/plttn/61d7940180bd1efe8114d7d96ece91c2/raw/d8b6737e8e63edce415e4d1c8b5fb05633a14c64/dokan.log

**Comment by marinkobabic** [comment] 2017-05-26 22:58
As you can see here 

00010823	72.81896973	[DokanFS]   IOCTL_EVENT_RELEASE	

Driver got the instruction from usermode to unmount your drive M:

So the question is now why did the usermode application sent this event to the driver? What happened inside the mirror so that the event has been sent to the driver. 

Now more details are needed from the usermode application respective from the mirror.exe

**Comment by plttn** [comment] 2017-05-26 23:19
https://gist.github.com/plttn/ad60cc98523abacde49313ce4af181a8

Usermode mirror log.

**Comment by marinkobabic** [comment] 2017-05-26 23:48
There is a "send global release for" which tells us that the unmount caned
from user mode application. So please do the following:

Add some log to the DokanRemoveMountPointEx
Run mirror with just one thread may simplify the log



Am 27.05.2017 01:19 schrieb "Jack Platten" <notifications@github.com>:

https://gist.github.com/plttn/ad60cc98523abacde49313ce4af181a8

Usermode mirror log.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/dokan-dev/dokany/issues/413#issuecomment-304407198>,
or mute
the thread

**Comment by plttn** [comment] 2017-05-26 23:50
Where specifically is the DokanRemoveMountPointEx? usermode or kernel?

**Comment by marinkobabic** [comment] 2017-05-26 23:56
https://github.com/dokan-dev/dokany/blob/b4dc99ad9efa0b60b05a1e37653e1fc1ba793f43/dokan/mount.c#L571


Am 27.05.2017 01:50 schrieb "Jack Platten" <notifications@github.com>:

**Comment by plttn** [comment] 2017-05-26 23:57
As in should I be logging `mirror.exe` or the kernel again?

**Comment by marinkobabic** [comment] 2017-05-27 00:13
Just the mirror please. We need to figure out where the call of the
SendGlobaleReleaseIRP caned from.

Am 27.05.2017 01:57 schrieb "Jack Platten" <notifications@github.com>:

**Comment by plttn** [comment] 2017-05-27 00:24
https://gist.github.com/plttn/97f9bdcac0afe52d6f716c54bab62db6

new execution, letting it idle to instantgo rather than closing the lid. that's an entire execution of `mirror.exe` minus the first few lines because powershell buffer.

**Comment by marinkobabic** [comment] 2017-05-27 00:28
There is no "send global release" in the log anymore. Please can you
provide the kernel log?

Am 27.05.2017 02:24 schrieb "Jack Platten" <notifications@github.com>:

**Comment by plttn** [comment] 2017-05-27 00:29
Did the kernel log above not provide what needed?

**Comment by marinkobabic** [comment] 2017-05-27 00:34
The kernel log above said that usermode requested the unmount. Your last
usermode log does not contain such an request. So the question is who
caused the unmount now.

You can check the user Mode your self and you will see that in the first
user Mode log is "send global release" but in the second one there is no
such an entry. So why is there still an unmount.

Am 27.05.2017 02:30 schrieb "Jack Platten" <notifications@github.com>:

> Did the kernel log above not provide what needed?
>

**Comment by plttn** [comment] 2017-05-27 00:37
The kernel logs and usermode logs were collected from different runs, but I can't see how this is a mirror.exe problem, as this occurs with keybase's filesystem as well.

**Comment by marinkobabic** [comment] 2017-05-27 00:43
In the passed the error was always in the driver. Use 1 thread and create 3
different kernel logs. Maybe one of them will provide enough information to
solve the problem. Normally is always the timeout thread.
https://github.com/dokan-dev/dokany/blob/de4e1408c498b069ada734d0ca9b5c2de501d14d/sys/timeout.c#L101


Am 27.05.2017 02:37 schrieb "Jack Platten" <notifications@github.com>:

**Comment by Liryna** [comment] 2018-12-09 10:07
Does anyone still face / reproduce this issue ? If Yes, can someone try with this changes:
https://github.com/dokan-dev/dokany/commit/1fdf9fb23e20d75659bf8344ce8d19f1bbcda7c8

**Comment by plttn** [comment] 2018-12-09 17:40
@Liryna is there a build artifact for it or do I need to build myself?

**Comment by Liryna** [comment] 2018-12-09 19:03
Hi @plttn ,

Appveyor succeed to create an artifact here https://ci.appveyor.com/project/Maxhy/dokany/builds/20877839/job/91tueoo2kvd5fa8y/artifacts
Be sure to import the dokan cert for being able to install and use it. Also to use the dokan1.dll from the installer that enables the new keepalive.

**Closed** 2019-05-11 20:39 UTC
Labels: Informations required
