### ISSUE TITLE
Visual Studio cannot create browsing database file when opening project on mirrored drive

### ISSUE THREAD

**Issue by bailey27** [dokan-dev/dokany#264] opened 2016-06-16 09:20 UTC
# Environment
- Windows version: Windows 10 64-bit
- Processor architecture:  Intel Haswell (i5-4200U)
- Dokany version: 1.0.0-RC3
- Library type (Dokany/FUSE): Dokany
# Check List
- [x ] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x ] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
- [x ] I can always reproduce the issue with the provided description below.
- [ x] I have updated Dokany to the latest version (https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
# Description

It seems that Visual Studio cannot create the browsing database on a mirrored drive.

Steps to reproduce

c:
cd \
mkdir c:\tmp\mirror 
cd tmp\mirror
git clone https://github.com/bailey27/cppcryptfs.git

[set up for Dokany debugging and reboot]

[ cd to C:\Program Files\Dokan\Dokan Library-1.0.0\sample\mirror]

[run as administrator]

.\mirror.exe /t 1 /d /s /r c:\tmp\mirror /l m 2> c:\tmp\mirror_vs.log

Open M:\cppcryptfs\cppcryptfs.sln in Visual Studio 2015 Community Edition

Visual Studio displays a dialog that says 

"An error occurred while creating or opening the C++ browsing database file M:\cppcryptfs\cppcryptfs.sdf. IntelliSense and browsing information will not be available for C++ projects.

Ensure that Microsoft SQL Server Compact 4.0 is installed and that no other applications are accessing the file.  If this problem persists, delete this file and reopen the solution."

I looked in the mirror log, and I couldn't figure out what VS tried to do that failed that caused this to happen. 

If I try to create a new project on the mirrored drive, the same error happens.
# Logs

Here are the logs.  I'm not sure what the "library logs" are.  If it's logging from the dll, I think there weren't any instructions for obtaining them.  I seem to have had only kernel driver output in dbgview.  I logged it to a file. I logged mirror to stderr and redirected to a file.

Here are the logs in this zip file.

[dokan_vs_logs.zip](https://github.com/dokan-dev/dokany/files/318023/dokan_vs_logs.zip)

**Comment by Liryna** [comment] 2016-06-16 10:55
Hi @bailey27 ,

This seems to be the same behaviour that https://github.com/dokan-dev/dokany/issues/249
The cppcryptfs.sdf is returned as not found for a reason.

This need to be investigated. If you have time to look into it, it would be very appreciate :+1: 
I have currently not a lots of time for it.

**Comment by bailey27** [comment] 2016-06-17 09:16
I didn't get very far, but I did notice this.

Right after Visual Studio actually creates the .sdf file, and before it deletes it, there two GetFileInfo that fail 

e.g.
###GetFileInfo 0093
	result =  0
	FileAllInformation
	DispatchQueryInformation result =  2147483653

2147483653 is 0x80000005 STATUS_BUFFER_OVERFLOW

Maybe that's not supposed to happen, and maybe that's why Visual Studio gives up and deletes the file?

I was thinking that maybe the problem is that the buffer is too small because there's only enough space in it to hold M:\cppcryptfs\cppcryptfs.sdf and not C:\tmp\mirror\cppcryptfs\cppcryptfs.sdf

I tried it with  mirror /r d:\ (so the path length wouldn't be different) and it still failed.

**Comment by Liryna** [comment] 2016-06-21 05:54
It seems like FileAllInformation should never return STATUS_BUFFER_OVERFLOW
https://msdn.microsoft.com/en-us/library/cc232117.aspx

I will take a look :)

**Comment by Liryna** [comment] 2016-06-21 15:10
Hi @bailey27 ,

Can you try to force STATUS_SUCCESS for DokanFillFileAllInfo and see if it improve the situation ?
Add `status = STATUS_SUCCESS` here https://github.com/dokan-dev/dokany/blob/054300d20c341413daccf35dbdc91f0b5001fedc/dokan/fileinfo.c#L481

**Comment by Liryna** [comment] 2016-06-25 10:40
@bailey27 , I have not been able to make visual studio create an sdf also :cry: 
Everything worked without it :smile: 

I dont know what VS need to create it

**Comment by Corillian** [comment] 2016-06-28 15:33
The SDF is the intellisense/code browser database, it's important.

**Comment by Liryna** [comment] 2016-06-28 15:36
Yes it is !
If I understood well, VS 2015 dropped SDF, I will make a test with VS 2013 this weekend.

**Comment by Liryna** [comment] 2016-07-02 13:02
Can be easily been reproduce with VS 2013 -> open a solution, close VS: Error as describe by @bailey27 

Quick review: VS try to open an existing .sdf and .opensdf. He create opensdf at first, delete it, create a .sdf, delete it, and try to open it.

Full log: http://pastebin.com/QULkenQz
```
###Create 0150
CreateFile : C:\Users\liryna\Desktop\vs\ConsoleApplication1\ConsoleApplication1.sdf
  AccountName: liryna, DomainName: DESKTOP-T9B1IFA
	ShareMode = 0x0
	AccessMode = 0x100080
	FILE_READ_ATTRIBUTES
	SYNCHRONIZE
	FlagsAndAttributes = 0x0
	OPEN_EXISTING
	error code = 2


CreateFile status = c0000034 - lastError = 2
###Create 0151
CreateFile : C:\Users\liryna\Desktop\vs\ConsoleApplication1\ConsoleApplication1.sdf
  AccountName: liryna, DomainName: DESKTOP-T9B1IFA
	ShareMode = 0x3
	FILE_SHARE_READ
	FILE_SHARE_WRITE
	AccessMode = 0x12019f
	FILE_READ_DATA
	FILE_READ_ATTRIBUTES
	FILE_READ_EA
	READ_CONTROL
	FILE_WRITE_DATA
	FILE_WRITE_ATTRIBUTES
	FILE_WRITE_EA
	FILE_APPEND_DATA
	SYNCHRONIZE
	STANDARD_RIGHTS_READ
	STANDARD_RIGHTS_WRITE
	STANDARD_RIGHTS_EXECUTE
	FlagsAndAttributes = 0x10000080
	FILE_ATTRIBUTE_NORMAL
	FILE_FLAG_RANDOM_ACCESS
	CREATE_NEW

CreateFile status = 0 - lastError = 0
###Cleanup 0144
Cleanup: C:\Users\liryna\Desktop\vs\ConsoleApplication1\ConsoleApplication1.opensdf

###GetFileInfo 0151
GetFileInfo : C:\Users\liryna\Desktop\vs\ConsoleApplication1\ConsoleApplication1.sdf
	GetFileInformationByHandle success, file size = 0

	result =  0
	FileStandardInformation
	DispatchQueryInformation result =  0
###Close 0144
Close: C:\Users\liryna\Desktop\vs\ConsoleApplication1\ConsoleApplication1.opensdf

###WriteFile 0136
WriteFile : C:\Users\liryna\Desktop\vs\ConsoleApplication1\ConsoleApplication1.opensdf, offset 0, length 14
	write 14, offset 0

###GetFileInfo 0151
GetFileInfo : C:\Users\liryna\Desktop\vs\ConsoleApplication1\ConsoleApplication1.sdf
	GetFileInformationByHandle success, file size = 0

	result =  0
	FileBasicInformation
	DispatchQueryInformation result =  0
###WriteFile 0136
WriteFile : C:\Users\liryna\Desktop\vs\ConsoleApplication1\ConsoleApplication1.opensdf, offset 14, length 30
	write 30, offset 14

###GetFileInfo 0151
GetFileInfo : C:\Users\liryna\Desktop\vs\ConsoleApplication1\ConsoleApplication1.sdf
	GetFileInformationByHandle success, file size = 0

	result =  0
	FileStandardInformation
	DispatchQueryInformation result =  0
###GetFileInfo 0151
GetFileInfo : C:\Users\liryna\Desktop\vs\ConsoleApplication1\ConsoleApplication1.sdf
	GetFileInformationByHandle success, file size = 0

	result =  0
	FileInternalInformation
	DispatchQueryInformation result =  0
###Cleanup 0151
Cleanup: C:\Users\liryna\Desktop\vs\ConsoleApplication1\ConsoleApplication1.sdf

###Close 0151
Close: C:\Users\liryna\Desktop\vs\ConsoleApplication1\ConsoleApplication1.sdf

###Create 0152
CreateFile : C:\Users\liryna\Desktop\vs\ConsoleApplication1\ConsoleApplication1.sdf
  AccountName: liryna, DomainName: DESKTOP-T9B1IFA
	ShareMode = 0x7
	FILE_SHARE_READ
	FILE_SHARE_WRITE
	FILE_SHARE_DELETE
	AccessMode = 0x10080
	DELETE
	FILE_READ_ATTRIBUTES
	FlagsAndAttributes = 0x200000
	FILE_FLAG_OPEN_REPARSE_POINT
	OPEN_EXISTING

CreateFile status = 0 - lastError = 0
###GetFileInfo 0152
GetFileInfo : C:\Users\liryna\Desktop\vs\ConsoleApplication1\ConsoleApplication1.sdf
	GetFileInformationByHandle success, file size = 0

	result =  0
	FileStandardInformation
	DispatchQueryInformation result =  0
###GetFileInfo 0152
GetFileInfo : C:\Users\liryna\Desktop\vs\ConsoleApplication1\ConsoleApplication1.sdf
	GetFileInformationByHandle success, file size = 0

	result =  0
	FileBasicInformation
	DispatchQueryInformation result =  0
###GetFileInfo 0152
GetFileInfo : C:\Users\liryna\Desktop\vs\ConsoleApplication1\ConsoleApplication1.sdf
	GetFileInformationByHandle success, file size = 0

	result =  0
	FileStandardInformation
	DispatchQueryInformation result =  0
###GetFileInfo 0152
GetFileInfo : C:\Users\liryna\Desktop\vs\ConsoleApplication1\ConsoleApplication1.sdf
	GetFileInformationByHandle success, file size = 0

	result =  0
	FileInternalInformation
	DispatchQueryInformation result =  0
###GetFileInfo 0152
GetFileInfo : C:\Users\liryna\Desktop\vs\ConsoleApplication1\ConsoleApplication1.sdf
	GetFileInformationByHandle success, file size = 0

	result =  0
	FileAttributeTagInformation
	DispatchQueryInformation result =  0
###SetFileInfo 0152  13
GetFileInfo : C:\Users\liryna\Desktop\vs\ConsoleApplication1\ConsoleApplication1.sdf
	GetFileInformationByHandle success, file size = 0

DeleteFile C:\Users\liryna\Desktop\vs\ConsoleApplication1\ConsoleApplication1.sdf
  dispositionInfo->DeleteFile = 1
	DispatchSetInformation result =  0
###Cleanup 0152
Cleanup: C:\Users\liryna\Desktop\vs\ConsoleApplication1\ConsoleApplication1.sdf

	DeleteOnClose
  DeleteFile success

###Close 0152
Close: C:\Users\liryna\Desktop\vs\ConsoleApplication1\ConsoleApplication1.sdf

###Create 0153
CreateFile : C:\Users\liryna\Desktop\vs\ConsoleApplication1\ConsoleApplication1.sdf
  AccountName: liryna, DomainName: DESKTOP-T9B1IFA
	ShareMode = 0x7
	FILE_SHARE_READ
	FILE_SHARE_WRITE
	FILE_SHARE_DELETE
	AccessMode = 0x10080
	DELETE
	FILE_READ_ATTRIBUTES
	FlagsAndAttributes = 0x200000
	FILE_FLAG_OPEN_REPARSE_POINT
	OPEN_EXISTING
	error code = 2


CreateFile status = c0000034 - lastError = 2
```

**Comment by marinkobabic** [comment] 2016-07-02 13:24
Please paste the driver log made after the last merged pull request made by @bailey27

**Comment by Liryna** [comment] 2016-07-02 13:31
New logs:
[kernel.txt](https://github.com/dokan-dev/dokany/files/344566/kernel.txt)
[mirror.txt](https://github.com/dokan-dev/dokany/files/344567/mirror.txt)

**Comment by marinkobabic** [comment] 2016-07-02 23:37
DokanFS] ==> DokanCompleteCreate
[DokanFS]   FileName:\liryna\Desktop\vs\ConsoleApplication1
[DokanFS]   FILE_DOES_NOT_EXIST
[DokanFS]    IRP_MJ_CREATE failed. Free CCB:FFFFE001A26044E0

How is this possible?

**Comment by jetwhiz** [comment] 2016-11-15 00:47
@Liryna -- I'm not sure if this is related, but I'm experiencing a similar issue (though intermittent) when running the CrystalDiskMark benchmark software on encfs4win.  I think it might be a problem for the order that cleanup/close and createfile are happening.  

It looks like the software does a Read -> Close -> Re-open -> Read, etc. 

Failure: 
````cmd
###Read 0133
ReadFile: \CrystalDiskMark006A6F99\CrystalDiskMark006A6F9A.tmp from 0 len 32768
###Read 0133
ReadFile: \CrystalDiskMark006A6F99\CrystalDiskMark006A6F9A.tmp from 52396032 len 32768
###Read 0133
ReadFile: \CrystalDiskMark006A6F99\CrystalDiskMark006A6F9A.tmp from 61440 len 32768
###Cleanup 0133
Cleanup: \CrystalDiskMark006A6F99\CrystalDiskMark006A6F9A.tmp

###Create 0135
CreateFile: \CrystalDiskMark006A6F99\CrystalDiskMark006A6F9A.tmp
	DesiredAccess: FILE_GENERIC_WRITE|FILE_GENERIC_READ
	ShareAccess: 0x0
	Disposition: FILE_OPEN (1)
	Attributes: 128 (0x80)
	Options: 108 (0x6c)
###Close 0133
Close: \CrystalDiskMark006A6F99\CrystalDiskMark006A6F9A.tmp

CreateFile status = c0000022
````

Success: 
````cmd
###Read 0079
ReadFile: \CrystalDiskMark00523388\CrystalDiskMark0052338B.tmp from 49283072 len 1048576
###Read 0079
ReadFile: \CrystalDiskMark00523388\CrystalDiskMark0052338B.tmp from 50331648 len 1048576
###Read 0079
ReadFile: \CrystalDiskMark00523388\CrystalDiskMark0052338B.tmp from 51380224 len 1048576
###Cleanup 0079
Cleanup: \CrystalDiskMark00523388\CrystalDiskMark0052338B.tmp

###Close 0079
Close: \CrystalDiskMark00523388\CrystalDiskMark0052338B.tmp

2016-11-15 01:05:20,875 VER [RawFileIO.cpp:116] open call, requestWrite = 0
2016-11-15 01:05:20,875 VER [RawFileIO.cpp:122] using existing file descriptor
###Create 0081
CreateFile: \CrystalDiskMark00523388\CrystalDiskMark0052338B.tmp
	DesiredAccess: FILE_GENERIC_WRITE|FILE_GENERIC_READ
	ShareAccess: 0x0
	Disposition: FILE_OPEN (1)
	Attributes: 128 (0x80)
	Options: 108 (0x6c)
````

Since the problem happens intermittently, that makes me think it is a race condition.  You can see that when it fails, the order is "CleanUp -> CreateFile -> Close" and when it's a success the order is "CleanUp -> Close -> CreateFile".  

I think the "Close" after the "CreateFile" is closing the new CreateFile (and not the old) since the second CreateFile is being called before "CleanUp -> Close" has completed.   Do you think this is a possibility?

**Comment by Liryna** [comment] 2016-11-17 07:21
Hi @jetwhiz ,

Humm the first case should work since normally cleanup passed. I have to look at this. Does this also happen with the mirror ?

**Comment by jetwhiz** [comment] 2016-11-17 13:01
@Liryna -- unfortuately I haven't been able to replicate the error with the mirror.  Each time I run the benchmark software with mirror it is in the order CleanUp -> Close -> CreateFile: 

````cmd
###Read 0017
ReadFile : C:\Users\jetwhiz\Desktop\test2\CrystalDiskMark009A3F02\CrystalDiskMark009A3F03.tmp
	Byte to read: 1048576, Byte read 1048576, offset 101711872

###Read 0017
ReadFile : C:\Users\jetwhiz\Desktop\test2\CrystalDiskMark009A3F02\CrystalDiskMark009A3F03.tmp
	Byte to read: 1048576, Byte read 1048576, offset 102760448

###Read 0017
ReadFile : C:\Users\jetwhiz\Desktop\test2\CrystalDiskMark009A3F02\CrystalDiskMark009A3F03.tmp
	Byte to read: 1048576, Byte read 1048576, offset 103809024

###Cleanup 0017
Cleanup: C:\Users\jetwhiz\Desktop\test2\CrystalDiskMark009A3F02\CrystalDiskMark009A3F03.tmp

###Close 0017
Close: C:\Users\jetwhiz\Desktop\test2\CrystalDiskMark009A3F02\CrystalDiskMark009A3F03.tmp

###Create 0019
CreateFile : C:\Users\jetwhiz\Desktop\test2\CrystalDiskMark009A3F02\CrystalDiskMark009A3F03.tmp
````

**Comment by Liryna** [comment] 2016-11-18 07:50
Humm so what you face could be an issue in the fuse wrapper on the cleanup <-> close.
There is a TODO on the cleanup and it seems to be exactly what you face.
https://github.com/dokan-dev/dokany/blob/4f1d82fe80b574d81dabb59debcfbf1972e4e4b1/dokan_fuse/src/fusemain.cpp#L392

What do you think ?

**Comment by jetwhiz** [comment] 2016-11-18 16:51
This might be related, since the problem seems to go away when I enable single-threaded mode in encfs4win.  

On Windows 7 this causes the benchmark software to fail (alerting user that it could not do the test), but on Windows 10 it seems to crash encfs4win for some reason.

**Comment by Liryna** [comment] 2016-11-19 16:51
Ok I see 😢 
Do you think to look into this ? (also create another issue for this issue you are facing ?) ❤️

**Comment by jetwhiz** [comment] 2016-11-25 23:30
@Liryna -- sure!  I have created a new issue to reflect our discussion (https://github.com/dokan-dev/dokany/issues/404)

**Closed** 2022-01-03 00:52 UTC
Labels: Bug

**Comment by shujaat-github** [comment] 2022-09-28 05:51
I wonder what was the actual fix? I face the same issue in EncFSy and I want to apply the same fix there too.
