### ISSUE TITLE
I can't uninstall Dokany 1.2.2.1000.

### ISSUE THREAD

**Issue by dryestfall2345** [dokan-dev/dokany#793] opened 2019-03-29 03:53 UTC
Feature request can skip this form. Bug report **must** complete it. `Check List` must be 100% match or it will be automatically closed without further discussion. Please remove this line.

# Environment
 * Windows version: Windows 10 Home 1803
 * Processor architecture: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz 2.81 GHz
 * Dokany version: 1.2.2.1000
 * Library type (Dokany/FUSE): DokanSetup.exe and Dokan_x64.msi
 
# Check List
  - [✓] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [✓] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [✓] I can always reproduce the issue with the provided description below.
  - [✓] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [✓] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
I installed Dokany version 1.2.2.1000 on DokanSetup.exe and Dokan_x64.msi, but i realised that i the program i needed Dokan for required an older version of Dokan Library. I hastily deleted the files of the Dokan with out uninstalling it properly and when i try to run DokanInstall_0.6.0.exe, it would tell me to uninstall the previous versions. When i try to uninstall dokan properly it fails every time i tried.
[Dokan_Library_1.2.2.1000_Bundle_20190329113503.log](https://github.com/dokan-dev/dokany/files/3021056/Dokan_Library_1.2.2.1000_Bundle_20190329113503.log)

# Logs
Please attach in separate files: mirror [output](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#mirrorfs), library logs and kernel [logs](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#get-logs).
In case of BSOD, please attach minidump or dump [analyze output](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#crash-report-bsod).

**Comment by js69** [comment] 2019-03-30 12:26
Could you please also post the the log file for the MSI, Dokan_Library_1.2.2.1000_Bundle_..._Dokan_x64.msi.log in your %temp%.

**Comment by js69** [comment] 2019-03-30 12:33
You can always try to uninstall the MSI from an admin command prompt with e.g.: "MsiExec.exe /X{65A3A964-3DC3-0102-0002-190308152204} /l*v uninstall.log".

**Comment by Liryna** [comment] 2019-04-14 17:11
Hi @dryestfall2345 ,

We will need the logs here to continue.

**Comment by SibCode** [comment] 2019-04-18 18:05
I've had a similar issue where it wouldn't properly uninstall and let me install a new version (specs: W10 Pro Intel i7-6800K @3.40 GHz). Using https://support.microsoft.com/en-us/help/17588/windows-fix-problems-that-block-programs-being-installed-or-removed to find and remove traces of previous installed instances (oddly enough 1.1.0.2000, even though I install a newer version without ) solved the problem for me. 

Full journey for readers from the future / people with a similar problem as mine with all steps involved: I couldn't mount keybase file system using Dokan Library (similar to issue https://github.com/dokan-dev/dokany/issues/771) and had to reinstall my current installation. When trying to install Dokan Library 1.2.2.100 again I always got the following error:

![2019-04-14 17_08_11-Window](https://user-images.githubusercontent.com/5826637/56377704-7ee27780-61fa-11e9-89c4-15226d3db091.png)

Errorcode: 0x8007064  (log on request)

I've initially uninstalled via Apps & Features (I think it was 1.2.2.100 even though the error suggests a previous version is installed) and restarted as suggested. The problem persisted and I was unable to install 1.2.2.100. As mentioned in the other issue I've uninstalled Visual C++ Redistribution Packages and as Dokan Library didn't properly uninstall for me, there were still many traces left in System32 that I deleted manually (I wouldn't recommend twiddling with it unless your sure about it and out of options - the solution below should probably work and suffice) but the same error again showed up. I did not find anything in the registry for Dokan.

Finally while running the troubleshooter from microsoft (https://support.microsoft.com/en-us/help/17588/windows-fix-problems-that-block-programs-being-installed-or-removed) it showed that traces of Dokan Library 1.1.0.2000 (x64) were still somewhere to be found. It fixed the issue (no corrupt patch or problem registry keys were found - it killed windows explorer leaving me in the dark however). When restarting Windows yet again, I could finally install the package and it worked. Also on a side note if you are a keybase user: let it install from the app.

**Comment by Liryna** [comment] 2019-04-19 16:03
Hi @SibCode ,

Thank you for full details. Yes, the log would be perfect !

**Comment by SibCode** [comment] 2019-04-19 17:23
Hello @Liryna ,

Here's the log from when it didn't work for me from yesterday: [Dokan_Library_1.2.2.1000_Bundle_20190418182953.log](https://github.com/dokan-dev/dokany/files/3095385/Dokan_Library_1.2.2.1000_Bundle_20190418182953.log) 

Breaking point: 

> `
[3CF0:3928][2019-04-18T18:29:56]i323: Registering package dependency provider: {65A3A964-3DC3-0102-0002-190308152204}, version: 1.2.2.1000, package: Dokan_x64.msi
[3CF0:3928][2019-04-18T18:29:56]i301: Applying execute package: Dokan_x64.msi, action: Install, path: C:\ProgramData\Package Cache\{65A3A964-3DC3-0102-0002-190308152204}v1.2.2.1000\Dokan_x64.msi, arguments: ' ARPSYSTEMCOMPONENT="1" MSIFASTINSTALL="7" MSIUNINSTALLSUPERSEDEDCOMPONENTS="1" INSTALLDIR="C:\Program Files\Dokan\Dokan Library-1.2.2" INSTALLDEVFILES="1"'
[3CF0:3928][2019-04-18T18:30:44]e000: Error 0x80070643: Failed to install MSI package.
[3CF0:3928][2019-04-18T18:30:44]e000: Error 0x80070643: Failed to execute MSI package.
[3DB0:3E80][2019-04-18T18:30:44]e000: Error 0x80070643: Failed to configure per-machine MSI package.
[3DB0:3E80][2019-04-18T18:30:44]i319: Applied execute package: Dokan_x64.msi, result: 0x80070643, restart: None
[3DB0:3E80][2019-04-18T18:30:44]e000: Error 0x80070643: Failed to execute MSI package.`

It looked similar to the log in issue https://github.com/dokan-dev/dokany/issues/771 but had the same error code as the log from @dryestfall2345 for this issue (Error 0x80070643).

As mentioned above the suggestion from issue https://github.com/dokan-dev/dokany/issues/771 using https://support.microsoft.com/en-us/help/17588/windows-fix-problems-that-block-programs-being-installed-or-removed to uninstall remaining parts from older installations worked for me.

However I've since noticed that although it worked yesterday today the KBFS does not mount / connect. The Dokan 1.2.2.100 installation was successfull so this could be a keybase related problem or another unrelated issue. I'll update / open another issue if I can't find a solution for my problem, however I hope this fixes at least dryestfall2345's issue.

**Comment by Liryna** [comment] 2019-04-19 17:44
The MSI is failing yes. Would need the log `msiexec /i Dokan_x64.msi /l*v DokanLogFile.txt` from the msi (can download in the release tab). Do you think you could reproduce it ?

**Comment by SibCode** [comment] 2019-04-25 12:33
Since the suggestions from https://github.com/dokan-dev/dokany/issues/771 worked for me and my problem seems to have been a complication with a bad installation of a previous / older version I don't think I would be able to reproduce it for that specific case.

**Comment by Liryna** [comment] 2019-04-25 12:35
Alright @SibCode I will close this for now so. If anyone face again the issue with a way to reproduce, ping here and will look together.

**Closed by Liryna** 2019-04-25 12:35 UTC
Labels: Informations required

**Comment by germannorwegian** [comment] 2023-05-20 09:43
Hello. Unfortunately, I seem to have the same issue. I have absolutely zero knowledge of anything related to code, I had to install the program as a dependency for an addon related to a flight simulator. I tried to delete dokan from the registry, but still there seems to be a trace of the program that the installer detects and tries to uninstall, but fails at. I have the same error code, 0x80070643, and the log file is attached. Thank you in advance
[Dokan_Library_2.0.6.1000_Bundle_20230520114216.log](https://github.com/dokan-dev/dokany/files/11521991/Dokan_Library_2.0.6.1000_Bundle_20230520114216.log)
![2d7395bb89266773691ce80e70ba2345](https://github.com/dokan-dev/dokany/assets/85123392/82f75b74-a95f-4674-aeb9-c3059271038c)

**Comment by germannorwegian** [comment] 2023-05-20 09:44
The reason for my struggles is that I was stubborn and deleted the program files manually without using the installer, which obviously was an extremely dumb move. Now I am left with some trace of the program which the installer tries to uninstall.

**Comment by Liryna** [comment] 2023-05-21 01:11
Hi @germannorwegian , there is another log for the child installer at `C:\Users\Bruker\AppData\Local\Temp\Dokan_Library_2.0.6.1000_Bundle_20230520114216_000_Dokan_x64.msi.log` that should give the reason of the failure.

**Comment by germannorwegian** [comment] 2023-05-21 08:08
Okay, thank you. Is this it?

[Dokan_Library_2.0.6.1000_Bundle_20230521100658_000_Dokan_x64.msi.log](https://github.com/dokan-dev/dokany/files/11524011/Dokan_Library_2.0.6.1000_Bundle_20230521100658_000_Dokan_x64.msi.log)

**Comment by germannorwegian** [comment] 2023-05-21 08:28
So it doesn't seem like the installer can find anything to uninstall, and yet it insists that dokany still exists on my pc, is there a way to override the uninstall function and just install the program again?

**Comment by Liryna** [comment] 2023-05-21 10:39
Microsoft had a tool to force remove installer from the registry but I can't recall the name. They might have even integrated it in the system now https://support.microsoft.com/en-us/windows/use-a-fix-it-tool-with-windows-10-cc3cb85b-91d7-7e56-8ce1-db50b4d18d0b

**Comment by germannorwegian** [comment] 2023-05-21 11:37
Yes, I tried using an uninstaller yesterday, and that did work. However when I reinstalled Dokan, the problem returned and Dokan did not install properly either, (Dokan did not create a folder in program files)

**Comment by germannorwegian** [comment] 2023-05-21 11:39
However the program does not appear in the uninstaller anymore, and when I search for Dokan across the entire system, no files appear, yet the installer thinks that the program is still installed.

**Comment by germannorwegian** [comment] 2023-05-21 11:42
And as mentioned, I cannot install a previous Dokan version (like 2.0.5) either, as it does not install properly. Really at a loss for words.

**Comment by germannorwegian** [comment] 2023-05-21 12:15
Alright, so an update. I went through the registry and used the search function to delete EVERY SINGLE entry of "dokan", "dokany" and "2.0.6.1000". After this, the dokansetup.exe worked again, and would let me install the program, however the x64 installer still thinks there is something to uninstall and does not let me install the program. Are there any possible dokan files i still need to remove which are not named "dokan", "dokany" or something like that?

**Comment by Liryna** [comment] 2023-05-21 12:20
You could have some in the Windows system https://github.com/dokan-dev/dokany/wiki/Installation#system-global 
the `.sys` might still be in used and you will need to run `sc stop dokan2` `sc delete dokan2`

**Comment by germannorwegian** [comment] 2023-05-21 12:25
Alright, I typed both commands into command-prompt, (sorry, I am not experienced with code), and Windows responds with; the program is not installed.

**Comment by germannorwegian** [comment] 2023-05-21 15:21
And still, I cannot install Dokan properly, the Dokan folder does not show up in program files.

**Comment by germannorwegian** [comment] 2023-05-21 15:28
And I can also confirm that there are no Dokan files whatsoever on my PC, atleast according to Windows Search. I checked the system32 folder for the dll, those three system files but those are gone too.

**Comment by Ynjxsjmh** [comment] 2023-10-22 04:44
@germannorwegian I also manually delete the dokan files and struggling to reinstall it. At last I use [RegScanner](http://www.nirsoft.net/utils/regscanner.html) to delete almost all the regedit entries related with dokan and finnaly reinstall dokan successfully.

**Comment by Hemantkdtr** [comment] 2025-05-26 11:12
Hola a todos. A mí me surgió el mismo problema y no podía eliminarlo ni desde msi ni desde exe; tampoco desde el cmd, ni accediendo al driver a su ubicación en System32.

La solución estriba en que Dokan está considerado como servicio y arrancado. Hay que para el servicio y eliminar el dirver después que en mi caso era dokan2.sys

![Image](https://github.com/user-attachments/assets/88149bf0-12e7-4c60-86e1-f32c997a1b11)

Después de reiniciar se puede introducir ya el SEtup.exe y la instalación queda realizada con éxito:

![Image](https://github.com/user-attachments/assets/ac376eba-6a59-4609-afc9-c8492f02b72a)

**Comment by Hemantkdtr** [comment] 2025-05-26 11:12
Hola a todos. A mí me surgió el mismo problema y no podía eliminarlo ni desde msi ni desde exe; tampoco desde el cmd, ni accediendo al driver a su ubicación en System32.

La solución estriba en que Dokan está considerado como servicio y arrancado. Hay que para el servicio y eliminar el dirver después que en mi caso era dokan2.sys

![Image](https://github.com/user-attachments/assets/88149bf0-12e7-4c60-86e1-f32c997a1b11)

Después de reiniciar se puede introducir ya el SEtup.exe y la instalación queda realizada con éxito:

![Image](https://github.com/user-attachments/assets/ac376eba-6a59-4609-afc9-c8492f02b72a)
