### ISSUE TITLE
Thumbnail in Windows 10 not displaying correctly

### ISSUE THREAD

**Issue by JoanM** [dokan-dev/dokany#154] opened 2016-02-02 09:50 UTC
Some images do not display correctly the thumbnail in Windows 10 explorer. I have reproduced the behaviour with mirror sample.
![screen shot 2016-02-02 at 10 43 29](https://cloud.githubusercontent.com/assets/2373716/12745564/25df0ec4-c99a-11e5-8299-d65b9dae9b5c.png)

For small size files preview is working fine, but for big images like (http://www.artandlemonade.com/wp-content/uploads/2014/06/MG_8940.jpg) it is not.

**Comment by Liryna** [comment] 2016-02-02 10:01
Same issue as https://github.com/dokan-dev/dokan-dotnet/issues/52

I have been able to reproduce the issue but I cannot find the reason for it.
If you can see what could be the source of it would be nice !

**Comment by Liryna** [comment] 2016-02-02 13:28
It seems that the issue only happen with a specific 'zoom'.

Also It looks like the file cannot be open with paint.

There is a request to that I have fake implemented:
https://github.com/dokan-dev/dokany/commit/76669edf5bd47e1dbdf6bb3f9bd71dc1faeb2995

But now he request FileRemoteProtocolInformation & FileStandardLinkInformation that probably need to be implemented to fix this issue.

**Comment by JoanM** [comment] 2016-02-02 14:19
File can't be opened with Paint but that is not Dokan problem because accessing it from real desktop (C:\) can't open it neither.

**Comment by Liryna** [comment] 2016-02-02 14:23
:disappointed: I had to test before.

**Comment by Liryna** [comment] 2016-02-02 16:25
From what I see in the logs, it seems that explorer begin to read the file for the thumbnail but stop it for a reason that we have to find.

There is a lot of request to GetFileInfo, so probably it come from there.

**Comment by Maxhy** [comment] 2016-05-10 19:50
Fixed with #165 :smile: (you can build the driver yourself for testing or wait for next RC release).

**Closed by Maxhy** 2016-05-10 19:50 UTC
Labels: bug

**Comment by js69** [comment] 2016-05-11 13:00
I can confirm this issue is fixed in latest revision. Not sure yet though if the new version isn't considerably slower than before listing files in Explorer.

**Comment by Liryna** [comment] 2016-05-11 14:41
Humm I just made a change https://github.com/dokan-dev/dokany/commit/8def16d6b0efed1c24f026d0b0b713dfd82039ca that could speed up if you was browsing a big folder.

Otherwise If it change nothing, it would be interesting to bench with and without oplock.
