### ISSUE TITLE
Dokan / Cryptomator strange Chinese characters in network explorer

### ISSUE THREAD

**Issue by rorygsales** [dokan-dev/dokany#890] opened 2020-04-25 18:30 UTC
Feature request can skip this form. Bug report **must** complete it. `Check List` must be 100% match or it will be automatically closed without further discussion. Please remove this line.

# Environment
 * Windows version: 10
 * Processor architecture: x64
 * Dokany version: 1.3.0.1000
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [-] The issue has shown itself twice that I have noticed but takes a while to appear ... worrying
  - [-] This version comes with Cryptomator and as such I cannot easily update in my mind with out the possibility of it not working for its intended purpose.
  - [-] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
Chinese Characters showing themselves randomly with the works Dokan1 in the Windows network area of explorer.
More here reported on Cryptomator issues - 
[Cryptomator issue 1150](https://github.com/cryptomator/cryptomator/issues/1150)

# Image
![Dokan](https://user-images.githubusercontent.com/42291081/80287765-7c7efb80-8733-11ea-93ba-98e5f6c84fd5.jpg)

# Logs
Please attach in separate files: mirror [output](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#mirrorfs), library logs and kernel [logs](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#get-logs).
In case of BSOD, please attach minidump or dump [analyze output](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#crash-report-bsod).

**Comment by Liryna** [comment] 2020-04-25 18:35
@rorygsales Hi!

Thanks for the report.

I have to say in never seen the behavior.
If it happens offen, can you try to use the mirror.exe installed with dokan? There is a sample in the wiki.
I just do not know exactly if cryptomator is using network drive with unc or not. You might have to try both.

**Comment by rorygsales** [comment] 2020-04-25 18:43
@Liryna  Hi there.

A pleasure.

I've only noticed it twice that I can recall... the last time I forgot to take a screenshot ... 
Will do the mirror.exe test asap.

Kind Regards
Rory

**Comment by Liryna** [comment] 2020-05-21 07:42
![image](https://user-images.githubusercontent.com/4311419/82535543-491f6900-9b47-11ea-91e1-24bc7c04d994.png)
I just had it on my own computer. That a dokan issue and have no idea for now what created it.

**Comment by rorygsales** [comment] 2020-05-21 07:48
> ![image](https://user-images.githubusercontent.com/4311419/82535543-491f6900-9b47-11ea-91e1-24bc7c04d994.png)
> I just had it on my own computer. That a dokan issue and have no idea for now what created it.

Hey I am no longer alone in this regard :)
Hopefully something easy to track down. I've not seen it my side in a while. 
My one is a little longer but similar format except for the 1 at the end.

**Comment by Liryna** [comment] 2020-05-31 07:17
https://github.com/dokan-dev/dokany/commit/6a4144f6ee723dc22ead433f835dccea75678f42
I haven't been able to reproduce the issue on my VM so looking at the code it is possible that we returned a dirty buffer as the copy would not happen since we have do not have a UNC.
https://github.com/dokan-dev/dokany/commit/6a4144f6ee723dc22ead433f835dccea75678f42#diff-0d281a5a20ad484e35eb5d133d0af346R883
The network provider would believe the dirty memory is a valid UNC and would try to display it's content that would lead to what we have.

As I said, I wasnt able to reproduce by that's a strong possibility.

**Comment by rorygsales** [comment] 2020-05-31 08:04
So you're saying I should go mac? 😉😋

**Comment by Liryna** [comment] 2020-05-31 08:06
Nahh :-D Just need to wait next release and see if this comes again or it is fixed by this patch.

**Comment by rorygsales** [comment] 2020-05-31 08:25
😃 great, thanks for all the research on this one, appreciated. Feel free to close issue all.

**Comment by jonharris0n** [comment] 2020-06-15 19:09
Same here.  I see '嘻Dokan1' in my Network explorer.

**Comment by Liryna** [comment] 2020-06-15 19:10
@jonharris0n Even with 1.4.0 dokan version ?

**Comment by jonharris0n** [comment] 2020-06-16 00:03
Dokany was installed with the latest release of Cryptomator.  Looks like it's still using 1.3.

**Comment by Liryna** [comment] 2020-07-25 13:07
Closing this as it is fixed in dokan. I will reopen if the feedback says differently.

**Closed by Liryna** 2020-07-25 13:07 UTC
