### ISSUE TITLE
Locally mounted memfs drive shows folders as "mounted volume" in properties

### ISSUE THREAD

**Issue by uhonermann** [dokan-dev/dokany#955] opened 2021-01-04 12:03 UTC
Feature request can skip this form. Bug report **must** complete it. `Check List` must be 100% match or it will be automatically closed without further discussion. Please remove this line.

# Environment
 * Windows version: Windows 10 1909
 * Processor architecture: x64
 * Dokany version: 1.4.0
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [X] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [X] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [X] I can always reproduce the issue with the provided description below.
  - [X] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description

Mount memfs.exe /l G
Create new folder in g:
copy a file to new folder
Open Properties of new folder
Properties dialog shows Type "Mounted volume" instead of Folder (and does not display size information)

# Logs
Please attach in separate files: mirror [output](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#mirrorfs), library logs and kernel [logs](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#get-logs).
In case of BSOD, please attach minidump or dump [analyze output](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#crash-report-bsod).

![image](https://user-images.githubusercontent.com/75378374/103533323-3450d500-4e8d-11eb-98c6-3cbb30224619.png)

**Comment by Liryna** [comment] 2021-01-04 12:09
Hi @uhonermann ,

Thanks for the report. This looks like to be a duplicate of https://github.com/dokan-dev/dokany/issues/355
Let me know if you think different and I will reopen the issue.

**Closed by Liryna** 2021-01-04 12:09 UTC
