### ISSUE TITLE
dokanctl.exe doesn't write to STDOUT. Output can't be read. 

### ISSUE THREAD

**Issue by RaviHale** [dokan-dev/dokany#59] opened 2015-09-16 05:41 UTC
For example, try dokanct.exe /v to get the version number

There's a milliseconds flash of a window on my screen but nothing else.

If I'm reading the source correctly, with ARGV<3 it should display usage... which also flashes up too fast to read.

Same issue with the other .exe files as well?

**Comment by Maxhy** [comment] 2015-09-16 05:46
That's probably because your command prompt is not executed with administrator rights. That's how Windows work with UAC... not really user friendly I agree.
You should run CMD with administrator rights before running dokanctl exe file.

**Comment by RaviHale** [comment] 2015-09-16 06:15
Thanks - perhaps it could say this via STDOUT if the user doesn't have admin rights?

**Comment by Liryna** [comment] 2015-09-16 06:17
Windows launch a popup asking to launch it with admin rights :smile: 
It is your configuration of the UAC that have disable it.

**Comment by RaviHale** [comment] 2015-09-16 06:20
@Liryna I granted the permissions on the UAC popup. It seems that there is a STDOUT redirection going on when cmd.exe isn't run as Admin... and no message to tell the user to run it as such

**Comment by Liryna** [comment] 2015-09-16 06:27
it is not a redirection.
Windows start dokanct.exe in another shell with admin rights and close it after the run.

It mean dokanct.exe never was launched, even not a part in your user cmd.

**Comment by RaviHale** [comment] 2015-09-16 06:47
Gotcha.

So does the UAC happen because of magic flags on the .exe file, or does the .exe request the UAC priviledges? 

Because if it's the latter, it would make sense to do the argument checking / usage before the UAC.

**Comment by suy** [comment] 2015-09-16 07:27
It's in the embedded manifest. Otherwise, yes, it could not ask for for permissions, so if you run it from a non-admin cmd.exe it would print normally. But the permissions are raised before the main function is run, so this can't be done. I have shortcut to run a cmd.exe as administrator, because sooner or later I face this problem, not only with dokanctl.exe.

**Comment by suy** [comment] 2015-09-16 07:29
"it could not ask for permissions" -> "it could not ask for permissions *for printing the version or the usage*", I meant. :)

**Comment by marinkobabic** [comment] 2015-09-16 09:33
If the option STDOUT is passed, the message "Press any key to continue..." should be shown and this way the problem is solved.

**Comment by suy** [comment] 2015-09-16 09:38
Yeah, I remember the first C tutorials I saw that all ended with a getchar() or system("PAUSE") to have that effect. It's ugly, but it could work too. :-)

**Comment by Liryna** [comment] 2015-09-16 11:15
It is a cool idea guys but there is not STDOUT  option :relaxed:
dokanctl always write in stdout.

There is two possibility:
- add an option to wait before quit getchar() or system("PAUSE") (like @suy say :heart: )
- use a very simple bat script like:
```
call dokanctl /v
pause
```
I think the second option is more simple and let dokanctl more clean.

**Closed** 2015-09-27 20:31 UTC
