### ISSUE TITLE
Explorer freezes when attempting to edit file 

### ISSUE THREAD

**Issue by jetwhiz** [dokan-dev/dokany#345] opened 2016-09-21 14:42 UTC
# Environment
 * Windows version: Windows 7
 * Processor architecture: x86
 * Dokany version: v1.0.0
 * Library type (Dokany/FUSE): FUSE
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the latest version (https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.

# Description

This appears to affect v1.0.0 specifically (and not the RC4 version).  

1. Mount folder with mirror.exe (or encfs4win)
2. Create new text file
3. Enter some random text into the file 
4. Save and close text file
5. Repoen text file and add more text to it 
6. Attempt to save text file (Explorer freezes)

# Logs

[log.txt](https://github.com/dokan-dev/dokany/files/485296/log.txt)

**Comment by Liryna** [comment] 2016-09-22 08:06
Hi @jetwhiz !

Thank you for the report, I have been able to reproduce easily with your steps :heart: 
This come from pull request https://github.com/dokan-dev/dokany/pull/325 @taruti 

This is a deadlock as I can see coming from the changes. There is probably somewhere where it is not released.

**Comment by Liryna** [comment] 2016-09-22 12:49
https://github.com/dokan-dev/dokany/blob/2c6ca3a6594741d0edc5c21f7116ffffee9fa579/sys/write.c#L125

`CcPurgeCacheSection` is freezing :cry: and is not leaving.

**Comment by Liryna** [comment] 2016-09-22 13:18
@taruti looks like CcPurgeCacheSection is calling another function that request also the lock and get stuck.
I tried to remove the lock from writing (since it has been added in the PR), it didn’t change. 

Do you know if there is a place where you added some lock ?

**Comment by taruti** [comment] 2016-09-22 13:30
Looking at this now.

**Comment by taruti** [comment] 2016-09-22 14:01
Relevant reading http://www.osronline.com/showThread.cfm?link=49848 and a PR.

**Comment by taruti** [comment] 2016-09-22 14:04
https://github.com/dokan-dev/dokany/pull/347 has a PR, but due to networking issues I cannot access my usual testing setup atm.

**Comment by Liryna** [comment] 2016-09-22 19:40
Fixed with @taruti ❤️ ! (will probably make a 1.0.1 next week)

**Closed by Liryna** 2016-09-22 19:40 UTC

**Comment by jetwhiz** [comment] 2016-09-23 10:14
Great!  Thank you for the quick fix, @Liryna @taruti !

**Comment by Rambalac** [comment] 2016-10-30 10:08
Any news about 1.0.1? I have Explorer lockups too, and my app hangs on unmount. Both cannot be killed and system cannot restart, only hardware reset button helps.

**Comment by Liryna** [comment] 2016-10-30 10:09
@Rambalac some task has to be done for the 1.0.1 https://github.com/dokan-dev/dokany/milestone/3

**Comment by Rondom** [comment] 2016-10-30 16:38
@Rambalac You can help by testing whether all your issues are gone in a snapshot build.
See https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot (The builds are self-signed, so you need to import the certs first)
