### ISSUE TITLE
Which ChartSet shoud I choose when input mount path using dokan_fuse fuse_setup function ? 

### ISSUE THREAD

**Issue by FaerieLee** [dokan-dev/dokany#893] opened 2020-05-14 06:44 UTC
Feature request can skip this form. Bug report **must** complete it. `Check List` must be 100% match or it will be automatically closed without further discussion. Please remove this line.

# Environment
 * Windows version: 1903
 * Processor architecture: x86
 * Dokany version: 1.3.1.1000
 * Library type (Dokany/FUSE): FUSE
 
# Check List
  - [ ] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [ ] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [ ] I can always reproduce the issue with the provided description below.
  - [ ] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
when i use fuse_setup function and mount path including chinese, mount would fail, so I ask for help. which charset should i choose for encoding my mount path ? Thanks !  

# Logs
Please attach in separate files: mirror [output](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#mirrorfs), library logs and kernel [logs](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#get-logs).
In case of BSOD, please attach minidump or dump [analyze output](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#crash-report-bsod).

**Comment by Liryna** [comment] 2020-05-14 07:00
Fuse / Dokan should work with chinese mount point. I do know Dokan work for sure. If there is an issue it might be in FUSE but looking at the code, it is just passing the buffer receive as param to the dokan mount function.
https://github.com/dokan-dev/dokany/blob/master/dokan_fuse/src/dokanfuse.cpp#L518

**Comment by FaerieLee** [comment] 2020-05-15 02:39
FUSE translate multibyteStr to WideCharStr using mbstowcs, but not call setlocale (set charset) before call it. In some cases, such non-ascii char , it can result in unexpected result. I think that it can be solved by using MultiByteToWideChar which Microsoft offer and set the value of chartset as utf-8.  I'd like to know what you think about this modification. Thanks !

**Comment by Liryna** [comment] 2020-05-15 15:37
@FaerieLee Good point!
There is functions like [wchar_to_utf8](https://github.com/dokan-dev/dokany/blob/08502afa1de0b32d8a59d090bfa73ecdd12374ab/dokan_fuse/src/utils.cpp#L160) that might be helpful solving the issue.
[MultiByteToWideChar](https://github.com/dokan-dev/dokany/blob/08502afa1de0b32d8a59d090bfa73ecdd12374ab/dokan_fuse/src/utils.cpp#L195-L207) was used but it tag as old: `utf8_to_wchar_buf_old`
Would be great to use one of them if possible.

**Comment by FaerieLee** [comment] 2020-05-16 07:29
I hace a question, what is the difference of utf8_to_wchar_buf_old and utf8_to_wchar_buf ? Why not use the utf8_to_wchar_buf_old which Microsoft offer, but to implement utf8_to_wchar ? So what advantages doing this ? Thanks

**Comment by Liryna** [comment] 2020-05-16 07:41
I must say, this was made by the original owner and I cannot say what was the reason behind.
`utf8_to_wchar_buf` is much larger used, so if we can continue in this way it would be great.
Probably `utf8_to_wchar_buf` was made to remove the Microsoft function as dokan_fuse goal is to build with other compiler than msvc that might not have `MultiByteToWideChar`.

**Comment by Liryna** [comment] 2020-05-29 15:16
@FaerieLee Did you had the time to take a look at this ?

**Comment by FaerieLee** [comment] 2020-05-30 02:40
Yes, I have the time, What should  I do for solving the problem ? upload code or something else ?

**Comment by Liryna** [comment] 2020-05-30 05:55
@FaerieLee Yes, as you have the issue it would be to fix the code with what we discussed and make a pull request with the changes when it work for you.

**Comment by Liryna** [comment] 2020-05-31 05:28
We need the steps to reproduce the crash and ensure that your PR fix the issue.
Making a blind change might not produce the wanted behavior.

**Comment by FaerieLee** [comment] 2020-05-31 05:50
Yes, Thanks for your comment and I am glad to have chance to contribute code. looking forward to your reviews and good news!

**Comment by Liryna** [comment] 2020-06-15 10:02
Fixed with https://github.com/dokan-dev/dokany/pull/900 Thanks @FaerieLee !

**Closed by Liryna** 2020-06-15 10:02 UTC
